"""pell CLI — v0.

Usage:
    pell build <file.pell>            -> emits to stdout
    pell build <file.pell> -o <out>   -> writes to file
    pell build <dir>                  -> compiles every .pell file in the dir
    pell parse <file.pell>            -> prints AST
    pell tokens <file.pell>           -> prints token stream
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import __version__
from .emitter import emit, emit_anon_block, EmitError
from .lexer import tokenize
from .parser import parse, parse_cell, ParseError
from .lexer import LexError


def cmd_build(args: argparse.Namespace) -> int:
    inputs = _collect_inputs(args.input)
    if not inputs:
        print(f"pell: no .pell files found in {args.input!r}", file=sys.stderr)
        return 2
    if args.output and len(inputs) > 1:
        print("pell: -o requires a single input file (or a directory output)", file=sys.stderr)
        return 2
    failures = 0
    for src_path in inputs:
        try:
            src = src_path.read_text()
            module = parse(src, str(src_path))
            sql = emit(module, target=args.target,
                       source_text=src, source_path=str(src_path),
                       reproducible=getattr(args, "reproducible", False))
        except (LexError, ParseError, EmitError) as e:
            print(f"pell: {e}", file=sys.stderr)
            failures += 1
            continue
        except ValueError as e:
            print(f"pell: {e}", file=sys.stderr)
            return 2
        # destination
        if args.output:
            out_path = Path(args.output)
        elif args.dir_output:
            out_path = Path(args.dir_output) / (src_path.stem + ".sql")
        else:
            out_path = None
        if out_path is None:
            print(sql)
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(sql)
            print(f"  → {out_path}")
    return 1 if failures else 0


def cmd_parse(args: argparse.Namespace) -> int:
    path = Path(args.input)
    src = path.read_text()
    try:
        m = parse(src, str(path))
    except (LexError, ParseError) as e:
        print(f"pell: {e}", file=sys.stderr)
        return 1
    _dump_ast(m)
    return 0


def cmd_runtime(args: argparse.Namespace) -> int:
    """Aggregate all error declarations from a project into a pell_runtime.sql."""
    from . import ast as A
    inputs = _collect_inputs(args.input)
    if not inputs:
        print(f"pell: no .pell files found in {args.input!r}", file=sys.stderr)
        return 2
    # gather (full-mangled-module-name, error_name, category) tuples.
    # We use the full mangled name (with schema prefix when present) so
    # `hr.employees::NotFound` and `acct.employees::NotFound` get distinct
    # global identifiers `hr_employees_notfound` vs `acct_employees_notfound`.
    errors: list[tuple[str, str, str]] = []
    failures = 0
    for src_path in inputs:
        try:
            module = parse(src_path.read_text(), str(src_path))
        except (LexError, ParseError) as e:
            print(f"pell: {e}", file=sys.stderr)
            failures += 1
            continue
        full = module.name.replace(".", "_")
        for item in module.items:
            if isinstance(item, A.ErrorDef):
                errors.append((full, item.name, getattr(item, "category", "propagate")))
    # emit a merged pell_runtime.sql
    code_start = 20100
    lines = [
        "-- pell_runtime — merged across the project",
        "-- Generated by `pell runtime`; do not edit by hand.",
        "",
        "CREATE OR REPLACE CONTEXT pell_err USING pell_runtime;",
        "/",
        "",
        "CREATE OR REPLACE PACKAGE pell_runtime AS",
        "  PROCEDURE set_err(p_key IN VARCHAR2, p_payload IN VARCHAR2);",
        "  PROCEDURE clear_err(p_key IN VARCHAR2);",
        "  FUNCTION  get_err(p_key IN VARCHAR2) RETURN VARCHAR2;",
        "",
    ]
    # Per-category SQLCODE counters — must mirror the per-module emitter's
    # ranges so single-module installs and project-wide pell_runtime agree.
    # propagate -20100..-20199 / skip -20200..-20299 / panic -20300..-20399.
    bases = {"propagate": 20100, "skip": 20200, "panic": 20300}
    counters = {"propagate": 0, "skip": 0, "panic": 0}
    for pkg, err, cat in errors:
        exn = f"{pkg}_{err}".lower()
        code = -(bases[cat] + counters[cat])
        counters[cat] += 1
        lines.append(f"  {exn} EXCEPTION;  -- {cat}")
        lines.append(f"  PRAGMA EXCEPTION_INIT({exn}, {code});")
    lines += [
        "END pell_runtime;",
        "/",
        "",
        "CREATE OR REPLACE PACKAGE BODY pell_runtime AS",
        "  PROCEDURE set_err(p_key IN VARCHAR2, p_payload IN VARCHAR2) IS",
        "  BEGIN",
        "    DBMS_SESSION.SET_CONTEXT('pell_err', p_key, p_payload);",
        "  END set_err;",
        "",
        "  PROCEDURE clear_err(p_key IN VARCHAR2) IS",
        "  BEGIN",
        "    DBMS_SESSION.CLEAR_CONTEXT('pell_err', p_key);",
        "  END clear_err;",
        "",
        "  FUNCTION get_err(p_key IN VARCHAR2) RETURN VARCHAR2 IS",
        "  BEGIN",
        "    RETURN SYS_CONTEXT('pell_err', p_key);",
        "  END get_err;",
        "END pell_runtime;",
        "/",
    ]
    output = "\n".join(lines) + "\n"
    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(output)
        print(f"  → {args.output} ({len(errors)} error variants)")
    else:
        print(output)
    return 1 if failures else 0


def cmd_tokens(args: argparse.Namespace) -> int:
    path = Path(args.input)
    src = path.read_text()
    try:
        for t in tokenize(src, str(path)):
            print(t)
    except LexError as e:
        print(f"pell: {e}", file=sys.stderr)
        return 1
    return 0


# ---------------------------------------------------------------------------


def _collect_inputs(input_arg: str) -> list[Path]:
    """Collect .pell files from a path. Directories are walked
    recursively, but a few well-known noise directories are skipped
    (.git, .venv, node_modules, build, out, expected, __pycache__).
    """
    skip_dirs = {".git", ".venv", "node_modules", "build", "out",
                 "expected", "__pycache__", "target"}
    p = Path(input_arg)
    if p.is_file():
        return [p]
    if not p.is_dir():
        return []
    out: list[Path] = []
    for path in p.rglob("*.pell"):
        if any(part in skip_dirs for part in path.parts):
            continue
        out.append(path)
    return sorted(out)


def _dump_ast(node, depth: int = 0) -> None:
    """Crude AST pretty-printer."""
    from dataclasses import is_dataclass, fields
    pad = "  " * depth
    if is_dataclass(node):
        cls = type(node).__name__
        print(f"{pad}{cls}")
        for f in fields(node):
            if f.name == "loc":
                continue
            v = getattr(node, f.name)
            print(f"{pad}  {f.name}:", end="")
            if isinstance(v, list):
                print()
                for item in v:
                    _dump_ast(item, depth + 2)
            elif is_dataclass(v):
                print()
                _dump_ast(v, depth + 2)
            else:
                print(f" {v!r}")
    else:
        print(f"{pad}{node!r}")


def cmd_deploy(args: argparse.Namespace) -> int:
    """Build every .pell in <input> and install the resulting .sql files
    against PELL_DB_URL in the correct order:

      1. pell_runtime.sql (if any module declares pell errors)
      2. pell_re.sql      (if --with-re given, or any module uses re::)
      3. each module .sql (in alphabetical order; cross-module deps are
                           the user's problem — pell doesn't infer them)

    Emits progress per file; on the first failure, reports the offending
    statement and bails (unless --keep-going).
    """
    import re as _re_mod

    project = Path(args.input).resolve()
    inputs = _collect_inputs(args.input)
    if not inputs:
        print(f"pell: no .pell files found in {args.input!r}", file=sys.stderr)
        return 2

    # Build everything first to catch compile errors before connecting.
    out_dir = Path(args.out_dir) if args.out_dir else (project / "built" if project.is_dir() else project.parent / "built")
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"pell deploy: build → {out_dir}")
    built_files: list[Path] = []
    uses_re = False
    has_errors = False
    failures = 0
    for src_path in inputs:
        try:
            src = src_path.read_text()
            module = parse(src, str(src_path))
            sql = emit(module, target=args.target, source_text=src,
                       source_path=str(src_path), reproducible=args.reproducible)
        except (LexError, ParseError, EmitError) as e:
            print(f"  ✗ {src_path.name}: {e}", file=sys.stderr)
            failures += 1
            if not args.keep_going:
                return 1
            continue
        if "pell_re." in sql:
            uses_re = True
        if "pell_runtime." in sql:
            has_errors = True
        out_path = out_dir / (src_path.stem + ".sql")
        out_path.write_text(sql)
        built_files.append(out_path)
        print(f"  ✓ {src_path.name} → {out_path.name}")
    if failures:
        print(f"pell deploy: {failures} build error(s); aborting before install", file=sys.stderr)
        return 1

    if args.build_only:
        return 0

    # Generate pell_runtime.sql if any module declared errors.
    runtime_sql = out_dir / "pell_runtime.sql"
    if has_errors:
        print(f"pell deploy: generating pell_runtime.sql ...")
        runtime_args = argparse.Namespace(input=str(project), output=str(runtime_sql))
        cmd_runtime(runtime_args)

    # Locate pell_re.sql if regex is in use. Look first in the repo's
    # runtime/ dir (canonical), then alongside the built files.
    re_sql: Path | None = None
    if uses_re or args.with_re:
        for candidate in (Path(__file__).resolve().parents[2] / "runtime" / "pell_re.sql",
                          out_dir / "pell_re.sql"):
            if candidate.exists():
                re_sql = candidate
                break

    # Install — connect via PELL_DB_URL / --connect, then apply each file.
    try:
        from . import driver
    except ImportError as e:
        print(f"pell: `pell deploy` needs the optional driver dependency; "
              f"install with: pip install -e .[repl]\n  ({e})", file=sys.stderr)
        return 2
    try:
        conn = driver.connect(args.connect)
    except Exception as e:
        print(f"pell: connection failed: {e}", file=sys.stderr)
        return 1

    install_order: list[Path] = []
    if has_errors:
        install_order.append(runtime_sql)
    if re_sql is not None:
        install_order.append(re_sql)
    install_order.extend(sorted(built_files))

    print(f"pell deploy: install {len(install_order)} file(s) → "
          f"{(args.connect or '$PELL_DB_URL')}")
    deploy_failures = 0
    try:
        for path in install_order:
            try:
                conn.execute_install(path.read_text())
                print(f"  ✓ {path.name}")
            except Exception as e:
                deploy_failures += 1
                print(f"  ✗ {path.name}: {e}", file=sys.stderr)
                if not args.keep_going:
                    return 1
        conn.commit()
    finally:
        conn.close()

    return 1 if deploy_failures else 0


def cmd_sql(args: argparse.Namespace) -> int:
    """Run a `.sql` file (typically a pell build output) against the
    connected database. Splits on the SQL*Plus `/` terminator, executes
    each statement in order, and prints any DBMS_OUTPUT a statement
    produced. On any statement failure, prints the position + error
    and stops.
    """
    try:
        source = Path(args.input).read_text()
    except OSError as e:
        print(f"pell: {e}", file=sys.stderr)
        return 1
    try:
        from . import driver
    except ImportError as e:
        print(f"pell: `pell sql` needs the optional driver dependency; "
              f"install with: pip install -e .[repl]\n  ({e})", file=sys.stderr)
        return 2
    try:
        conn = driver.connect(args.connect)
    except Exception as e:
        print(f"pell: connection failed: {e}", file=sys.stderr)
        return 1
    stmts = driver._split_script(source)
    failures = 0
    try:
        for idx, stmt in enumerate(stmts, start=1):
            head = stmt.lstrip().split(None, 1)[0] if stmt.strip() else "<empty>"
            label = f"[{idx}/{len(stmts)}] {head[:60]}"
            try:
                with conn.raw.cursor() as cur:
                    cur.execute(driver._strip_terminator(stmt))
                    output = driver._drain_dbms_output(cur)
                print(f"{label}  ok")
                for ln in output:
                    print(f"  {ln}")
            except Exception as e:
                failures += 1
                print(f"{label}  FAIL", file=sys.stderr)
                print(f"  {e}", file=sys.stderr)
                if args.stop_on_error:
                    break
        conn.commit()
    finally:
        conn.close()
    return 1 if failures else 0


def cmd_repl(args: argparse.Namespace) -> int:
    try:
        from .repl import run_repl
    except ImportError as e:
        print(f"pell: `pell repl` needs the optional repl dependencies; "
              f"install with: pip install -e .[repl]\n  ({e})", file=sys.stderr)
        return 2
    return run_repl(args.connect, target=args.target)


def cmd_exec(args: argparse.Namespace) -> int:
    """Compile a pell cell (file or `-e` snippet) into an anonymous PL/SQL
    block and run it against the connected database."""
    if args.expr is not None and args.input is not None:
        print("pell: pass either a file or -e, not both", file=sys.stderr)
        return 2
    if args.expr is not None:
        source = args.expr
        source_path = "<-e>"
    elif args.input is not None:
        source_path = args.input
        source = Path(args.input).read_text()
    else:
        source = sys.stdin.read()
        source_path = "<stdin>"
    try:
        items, stmts = parse_cell(source, source_path)
    except (LexError, ParseError) as e:
        print(f"pell: {e}", file=sys.stderr)
        return 1
    if not items and not stmts:
        return 0
    # Scan the cwd for sibling .pell files so cross-package call
    # inference works the same way it does in the REPL.
    try:
        from .repl import scan_project_signatures
        project_signatures = scan_project_signatures()
    except Exception:
        project_signatures = {}
    try:
        block = emit_anon_block(items, stmts, target=args.target,
                                source_path=source_path,
                                project_signatures=project_signatures)
    except EmitError as e:
        print(f"pell: {e}", file=sys.stderr)
        return 1
    if args.dry_run:
        print(block)
        return 0
    try:
        from . import driver
    except ImportError as e:
        print(f"pell: `pell exec` needs the optional driver dependency; "
              f"install with: pip install -e .[repl]\n  ({e})", file=sys.stderr)
        return 2
    try:
        conn = driver.connect(args.connect)
    except Exception as e:
        print(f"pell: connection failed: {e}", file=sys.stderr)
        return 1
    try:
        lines = conn.run_block(block)
    except Exception as e:
        print(f"pell: execution failed: {e}", file=sys.stderr)
        if args.show_block:
            print(block, file=sys.stderr)
        return 1
    finally:
        conn.close()
    for ln in lines:
        print(ln)
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="pell", description=f"pell compiler v{__version__}")
    sub = p.add_subparsers(dest="cmd", required=True)

    b = sub.add_parser("build", help="compile .pell to PL/SQL")
    b.add_argument("input", help="path to a .pell file or a directory of them")
    b.add_argument("-o", "--output", help="output .sql file (single input only)")
    b.add_argument("-d", "--dir-output", help="output directory (when compiling a dir)")
    b.add_argument(
        "--target",
        choices=("23", "19c"),
        default="23",
        help="Oracle target version (default: 23). 19c downgrades JSON to "
        "VARCHAR2(32767) and BOOLEAN-in-OBJECT to NUMBER(1).",
    )
    b.add_argument(
        "--reproducible",
        action="store_true",
        help="omit the build timestamp and uncommitted-working-tree hash from "
        "the preamble so output is byte-stable across runs from the same "
        "source + commit. Useful for golden snapshots.",
    )
    b.set_defaults(func=cmd_build)

    pa = sub.add_parser("parse", help="print AST for a .pell file")
    pa.add_argument("input")
    pa.set_defaults(func=cmd_parse)

    t = sub.add_parser("tokens", help="print token stream for a .pell file")
    t.add_argument("input")
    t.set_defaults(func=cmd_tokens)

    r = sub.add_parser("runtime", help="aggregate error decls into a pell_runtime.sql")
    r.add_argument("input", help="path to a .pell file or a directory of them")
    r.add_argument("-o", "--output", help="write to this file instead of stdout")
    r.set_defaults(func=cmd_runtime)

    ex = sub.add_parser(
        "exec",
        help="compile a pell cell to an anonymous PL/SQL block and run it",
    )
    ex.add_argument("input", nargs="?", help="path to a .pell file (or omit for stdin)")
    ex.add_argument("-e", "--expr", help="inline pell source to execute")
    ex.add_argument("-c", "--connect", help="user/pass@host:port/service (or set PELL_DB_URL)")
    ex.add_argument("--target", choices=("23", "19c"), default="23")
    ex.add_argument("--dry-run", action="store_true",
                    help="print the emitted block and exit; don't connect to a database")
    ex.add_argument("--show-block", action="store_true",
                    help="on error, also print the emitted block to stderr")
    ex.set_defaults(func=cmd_exec)

    rp = sub.add_parser("repl", help="interactive pell notebook against a live Oracle")
    rp.add_argument("-c", "--connect", help="user/pass@host:port/service (or set PELL_DB_URL)")
    rp.add_argument("--target", choices=("23", "19c"), default="23")
    rp.set_defaults(func=cmd_repl)

    dp = sub.add_parser(
        "deploy",
        help="build a .pell project and install every emitted .sql against PELL_DB_URL "
             "(pell_runtime + pell_re + module spec/body) in the right order",
    )
    dp.add_argument("input", help="path to a .pell file or a directory of them")
    dp.add_argument("-c", "--connect", help="user/pass@host:port/service (or set PELL_DB_URL)")
    dp.add_argument("--target", choices=("23", "19c"), default="23")
    dp.add_argument("--reproducible", action="store_true",
                    help="omit volatile preamble fields so output is byte-stable")
    dp.add_argument("--out-dir", "-d",
                    help="where to write built .sql files (default: <input>/built)")
    dp.add_argument("--with-re", action="store_true",
                    help="install pell_re.sql even if no module references re::")
    dp.add_argument("--build-only", action="store_true",
                    help="run the build half; skip the install half")
    dp.add_argument("--keep-going", action="store_true",
                    help="don't stop on the first failure; collect them and exit non-zero at the end")
    dp.set_defaults(func=cmd_deploy)

    sq = sub.add_parser(
        "sql",
        help="run a .sql script against the connected database (pell build output, "
             "deploy scripts, ad-hoc DDL/DML)",
    )
    sq.add_argument("input", help="path to a .sql file")
    sq.add_argument("-c", "--connect", help="user/pass@host:port/service (or set PELL_DB_URL)")
    sq.add_argument("--stop-on-error", action="store_true",
                    help="stop at the first failed statement (default: continue, report at end)")
    sq.set_defaults(func=cmd_sql)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
