package dev.pell.intellij.parser

import com.intellij.testFramework.ParsingTestCase

/**
 * Smoke tests for the Grammar-Kit-generated PellParser.
 *
 * Each test parses a fixture file (located in `intellij/src/test/resources/parser/`)
 * and asserts the resulting tree matches the expected `.txt` snapshot
 * Generated by ParsingTestCase. To regenerate snapshots after a
 * deliberate grammar change:
 *
 *   $ ./gradlew test --tests "*PellParserTest*" -Doverwrite.test.data=true
 *
 * PSI TRACK — owned by the PSI work stream. See intellij/PSI_TRACK.md.
 */
class PellParserTest : ParsingTestCase(
    /* dataPath */ "parser",
    /* fileExt */ "pell",
    /* parserDefinition */ dev.pell.intellij.PellParserDefinition(),
) {

    override fun getTestDataPath(): String = "src/test/resources"

    fun testEmptyModule() = doTest(true)
    fun testHelloFn() = doTest(true)
    fun testRecord() = doTest(true)
    fun testErrorWithFields() = doTest(true)
    fun testSqlBlock() = doTest(true)
    fun testJqBlock() = doTest(true)
    fun testMatchExpr() = doTest(true)
    fun testForLoop() = doTest(true)
    fun testGenericTypes() = doTest(true)
    fun testTurbofish() = doTest(true)
    fun testStructLit() = doTest(true)
    fun testQualifiedExpr() = doTest(true)
    fun testScriptFile() = doTest(true)
}
