-- Generated by pell v0 from module reports.rating_dist
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE reports_rating_dist AS
  TYPE t_bucket IS RECORD (
    rating NUMBER,
    n NUMBER,
    pct NUMBER
  );
  TYPE t_Bucket_list IS TABLE OF t_bucket INDEX BY PLS_INTEGER;
  FUNCTION dist RETURN t_Bucket_list;
END reports_rating_dist;
/

CREATE OR REPLACE PACKAGE BODY reports_rating_dist AS

  FUNCTION dist RETURN t_Bucket_list IS
    l_total NUMBER;
    l_rows t_Bucket_list;
  BEGIN
    BEGIN
      select count(*)
      INTO l_total
      FROM ml_ratings_src;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    select rating,
           count(*),
           round(100 * count(*) / l_total, 2)
      BULK COLLECT INTO l_rows
      FROM ml_ratings_src
    group  by rating
    order  by rating;
    RETURN l_rows;
  END dist;
END reports_rating_dist;
/