-- Generated by pell v0 from module reports.top_movies
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE reports_top_movies AS
  TYPE t_topmovie IS RECORD (
    movie_id NUMBER,
    title VARCHAR2(4000),
    rating_count NUMBER,
    avg_rating NUMBER
  );
  TYPE t_TopMovie_list IS TABLE OF t_topmovie INDEX BY PLS_INTEGER;
  FUNCTION top_n(p_min_ratings IN NUMBER) RETURN t_TopMovie_list;
END reports_top_movies;
/

CREATE OR REPLACE PACKAGE BODY reports_top_movies AS

  FUNCTION top_n(p_min_ratings IN NUMBER) RETURN t_TopMovie_list IS
    l_rows t_TopMovie_list;
  BEGIN
    select r.movie_id,
           m.title,
           count(*),
           round(avg(r.rating), 3)
      BULK COLLECT INTO l_rows
      FROM ml_ratings_src r
    join   ml_movies m on m.id = r.movie_id
    group  by r.movie_id, m.title
    having count(*) >= p_min_ratings
    order  by avg(r.rating) desc, count(*) desc
    fetch  first 10 rows only;
    RETURN l_rows;
  END top_n;
END reports_top_movies;
/