-- Generated by pell v0 from module reports.user_activity
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE reports_user_activity AS
  TYPE t_userstat IS RECORD (
    user_id NUMBER,
    rating_count NUMBER,
    avg_rating NUMBER
  );
  TYPE t_UserStat_list IS TABLE OF t_userstat INDEX BY PLS_INTEGER;
  FUNCTION top_raters(p_top_n IN NUMBER) RETURN t_UserStat_list;
END reports_user_activity;
/

CREATE OR REPLACE PACKAGE BODY reports_user_activity AS

  FUNCTION top_raters(p_top_n IN NUMBER) RETURN t_UserStat_list IS
    l_rows t_UserStat_list;
  BEGIN
    select user_id,
           count(*),
           round(avg(rating), 3)
      BULK COLLECT INTO l_rows
      FROM ml_ratings_src
    group  by user_id
    order  by count(*) desc
    fetch  first p_top_n rows only;
    RETURN l_rows;
  END top_raters;
END reports_user_activity;
/