package dev.pell.intellij.psi

import com.intellij.psi.PsiNameIdentifierOwner

/**
 * Every pell declaration whose name is referenceable — fn, record,
 * error, type, sealed type, aggregate, seq, enum, method, case,
 * enumVariant, param, field, let, var, for-loop var. Phase 4 reference
 * resolution targets these; Phase 5 rename rewrites their names.
 *
 * Concrete classes are generated by Grammar-Kit and extend
 * [dev.pell.intellij.psi.impl.PellNamedElementImpl], which supplies
 * default getName/setName/getNameIdentifier implementations that look
 * for a child [PellNameIdentifier].
 *
 * PSI TRACK — owned by the PSI work stream. See intellij/PSI_TRACK.md.
 */
interface PellNamedElement : PellPsiElement, PsiNameIdentifierOwner
