-- ======================================================================
-- Generated by pell 0.0.1 from module hello
--   Source:     examples/01_hello.pell
--   SHA-256:    669acd4153ec2a4bb14672cff2952e3377ac994721a228e7b074ee8f7215af29
--   pell git:   05345b4 + uncommitted:124a7baf
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
--   Built at:   2026-06-10 11:53:03 UTC
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     logger
-- ======================================================================

CREATE OR REPLACE PACKAGE hello AS
  FUNCTION greet(p_name IN VARCHAR2) RETURN VARCHAR2;
END hello;
/

CREATE OR REPLACE PACKAGE BODY hello AS

  FUNCTION greet(p_name IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    logger.info(('greeting ' || p_name));
    RETURN ('hello, ' || p_name);
  END greet;
END hello;
/