-- ======================================================================
-- Generated by pell 0.0.1 from module hello
--   Source:     examples/01_hello.pell
--   SHA-256:    7e108337eebe2eba97616cf69a8dfd69dc0cb6655551696046768505fa188fa1
--   pell git:   989cd68 + uncommitted:d860073c
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
--   Built at:   2026-06-03 02:27:08 UTC
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     logger
-- ======================================================================

CREATE OR REPLACE PACKAGE hello AS
  PROCEDURE greet(p_name IN VARCHAR2);
END hello;
/

CREATE OR REPLACE PACKAGE BODY hello AS

  PROCEDURE greet(p_name IN VARCHAR2) IS
  BEGIN
    logger.info(p_name);
  END greet;
END hello;
/