-- ======================================================================
-- Generated by pell 0.0.1 from module hello
--   Source:     compiler/examples/01_hello.pell
--   SHA-256:    669acd4153ec2a4bb14672cff2952e3377ac994721a228e7b074ee8f7215af29
--   pell git:   5dad80a + uncommitted:22036bef
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
--   Built at:   2026-06-11 04:57:57 UTC
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     logger
-- ======================================================================

CREATE OR REPLACE PACKAGE hello AS
  FUNCTION greet(p_name IN VARCHAR2) RETURN VARCHAR2;
END hello;
/

CREATE OR REPLACE PACKAGE BODY hello AS

  FUNCTION greet(p_name IN VARCHAR2) RETURN VARCHAR2 IS  -- @pell:9
  BEGIN
    logger.info(('greeting ' || p_name));  -- @pell:10
    RETURN ('hello, ' || p_name);  -- @pell:11
  END greet;
END hello;
/