-- ======================================================================
-- Generated by pell 0.0.1 from module emp_demo
--   Source:     examples/14_sequence.pell
--   SHA-256:    d123a9351edcca6d49b7a4a8c272349a580773a5a012658ec4135a34ecedb66e
--   pell git:   6b073a2 + uncommitted:64697636
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
--   Built at:   2026-06-10 11:48:58 UTC
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   sequences:
--     employee_id_seq
-- ======================================================================

CREATE OR REPLACE PACKAGE emp_demo AS
  FUNCTION next_employee_id RETURN NUMBER;
  FUNCTION current_id RETURN NUMBER;
END emp_demo;
/

CREATE OR REPLACE PACKAGE BODY emp_demo AS

  FUNCTION next_employee_id RETURN NUMBER IS
    l_id NUMBER;
  BEGIN
    l_id := employee_id_seq.nextval;
    RETURN l_id;
  END next_employee_id;

  FUNCTION current_id RETURN NUMBER IS
  BEGIN
    RETURN employee_id_seq.currval;
  END current_id;
END emp_demo;
/