-- ======================================================================
-- Generated by pell 0.0.1 from module signups.validate
--   Source:     examples/25_validation.pell
--   SHA-256:    a85fdd323474a450d0c2ad676aa23dcbb686ab62178c8573ae248ca6f8e110d4
--   pell git:   6b073a2 + uncommitted:0831ecc7
--   Target:     Oracle 23
--   Schema:     signups
--   Built at:   2026-06-10 11:49:10 UTC
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     pell_runtime
-- ======================================================================

-- Additions to pell_runtime for module signups.validate:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   signups_validate_missingfield EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validate_missingfield, -20100);
--   signups_validate_invalidemail EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validate_invalidemail, -20101);
--   signups_validate_ageoutofrange EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validate_ageoutofrange, -20102);

CREATE OR REPLACE PACKAGE signups.validate AS
  TYPE t_signupform IS RECORD (
    name VARCHAR2(4000),
    email VARCHAR2(4000),
    age NUMBER
  );
  FUNCTION require_text(p_field IN VARCHAR2, p_value IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION require_email(p_value IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION require_age(p_value IN NUMBER) RETURN NUMBER;
  FUNCTION validate_signup(p_form IN t_signupform) RETURN t_signupform;
END validate;
/

CREATE OR REPLACE PACKAGE BODY signups.validate AS

  -- Forward declarations (private fns; lets them be
  -- called before their definition in this body).
  FUNCTION get_name(p_form IN t_any) RETURN VARCHAR2;

  FUNCTION require_text(p_field IN VARCHAR2, p_value IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF (p_value IS NULL OR LENGTH(p_value) = 0) THEN
      pell_runtime.set_err('signups_validate_missingfield:1', JSON_OBJECT('field' VALUE p_field));
      RAISE pell_runtime.signups_validate_missingfield;
    END IF;
    RETURN p_value;
  END require_text;

  FUNCTION require_email(p_value IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF (p_value IS NULL OR LENGTH(p_value) = 0) THEN
      pell_runtime.set_err('signups_validate_invalidemail:1', JSON_OBJECT('value' VALUE p_value, 'reason' VALUE 'empty'));
      RAISE pell_runtime.signups_validate_invalidemail;
    END IF;
    IF ((INSTR(p_value, '@') > 0) = FALSE) THEN
      pell_runtime.set_err('signups_validate_invalidemail:1', JSON_OBJECT('value' VALUE p_value, 'reason' VALUE 'no @'));
      RAISE pell_runtime.signups_validate_invalidemail;
    END IF;
    IF ((p_value LIKE '%' || '.') OR (p_value LIKE '.' || '%')) THEN
      pell_runtime.set_err('signups_validate_invalidemail:1', JSON_OBJECT('value' VALUE p_value, 'reason' VALUE 'leading/trailing dot'));
      RAISE pell_runtime.signups_validate_invalidemail;
    END IF;
    RETURN p_value;
  END require_email;

  FUNCTION require_age(p_value IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF ((p_value < 13) OR (p_value > 120)) THEN
      pell_runtime.set_err('signups_validate_ageoutofrange:1', JSON_OBJECT('value' VALUE p_value, 'min' VALUE 13, 'max' VALUE 120));
      RAISE pell_runtime.signups_validate_ageoutofrange;
    END IF;
    RETURN p_value;
  END require_age;

  FUNCTION validate_signup(p_form IN t_signupform) RETURN t_signupform IS
    l_name VARCHAR2(4000);
    l_email VARCHAR2(4000);
    l_age NUMBER;
    l_ret_1 t_signupform;
  BEGIN
    l_name := get_name(p_form);
    l_email := require_email(p_form.email);
    l_age := require_age(p_form.age);
    l_ret_1.name := l_name;
    l_ret_1.email := l_email;
    l_ret_1.age := l_age;
    RETURN l_ret_1;
  END validate_signup;

  FUNCTION get_name(p_form IN t_any) RETURN VARCHAR2 IS
  BEGIN
    RETURN require_text('name', p_form.name);
  END get_name;
END validate;
/