-- ======================================================================
-- Generated by pell 0.0.1 from module catalog_all
--   Source:     compiler/runtime/catalog_all.pell
--   SHA-256:    8eb990f997cd3d2db3f70f910af6aae36bbb21eabe5c506845d8cf1a2bf8f37b
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     all_cons_columns
--     all_constraints
--     all_dependencies
--     all_errors
--     all_ind_columns
--     all_indexes
--     all_objects
--     all_sequences
--     all_source
--     all_tab_columns
--     all_tables
--     all_triggers
--     all_types
--     all_views
--     dual
-- ======================================================================

CREATE OR REPLACE PACKAGE catalog_all AS
  TYPE t_text_list IS TABLE OF VARCHAR2(4000) INDEX BY PLS_INTEGER;
  TYPE t_catalog_ObjectInfo_list IS TABLE OF catalog.t_objectinfo INDEX BY PLS_INTEGER;
  TYPE t_catalog_ColumnInfo_list IS TABLE OF catalog.t_columninfo INDEX BY PLS_INTEGER;
  TYPE t_catalog_ConstraintInfo_list IS TABLE OF catalog.t_constraintinfo INDEX BY PLS_INTEGER;
  TYPE t_catalog_IndexInfo_list IS TABLE OF catalog.t_indexinfo INDEX BY PLS_INTEGER;
  TYPE t_catalog_ForeignKeyInfo_list IS TABLE OF catalog.t_foreignkeyinfo INDEX BY PLS_INTEGER;
  TYPE t_catalog_ErrorInfo_list IS TABLE OF catalog.t_errorinfo INDEX BY PLS_INTEGER;
  FUNCTION index_detail(p_owner IN VARCHAR2, p_index IN VARCHAR2) RETURN catalog.t_indexdetail;
  FUNCTION list_tables RETURN t_text_list;
  FUNCTION list_views RETURN t_text_list;
  FUNCTION list_packages RETURN t_text_list;
  FUNCTION list_functions RETURN t_text_list;
  FUNCTION list_procedures RETURN t_text_list;
  FUNCTION list_sequences RETURN t_text_list;
  FUNCTION list_types RETURN t_text_list;
  FUNCTION list_triggers RETURN t_text_list;
  FUNCTION list_invalid RETURN t_text_list;
  FUNCTION list_objects_info RETURN t_catalog_ObjectInfo_list;
  FUNCTION list_invalid_info RETURN t_catalog_ObjectInfo_list;
  FUNCTION columns_of(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_catalog_ColumnInfo_list;
  FUNCTION constraints_of(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_catalog_ConstraintInfo_list;
  FUNCTION indexes_of(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_catalog_IndexInfo_list;
  FUNCTION foreign_keys_of(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_catalog_ForeignKeyInfo_list;
  FUNCTION errors_for(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_catalog_ErrorInfo_list;
  FUNCTION source_of(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION spec_of(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION body_of(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION fk_tree(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list;
  FUNCTION deps_tree(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION dependents_tree(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION fk_mermaid(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list;
  FUNCTION depends_on(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION dependents_of(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
END catalog_all;
/

CREATE OR REPLACE PACKAGE BODY catalog_all AS

  FUNCTION index_detail(p_owner IN VARCHAR2, p_index IN VARCHAR2) RETURN catalog.t_indexdetail IS
    l_pell_ret_1 catalog.t_indexdetail;
  BEGIN
    BEGIN
      select count(*) as cols_found,
               max(i.table_name) as table_name,
               listagg(c.column_name, ', ')
                 within group (order by c.column_position) as cols,
               max(i.uniqueness) as uniqueness
      INTO l_pell_ret_1
      FROM all_indexes i
          join all_ind_columns c
            on c.index_owner = i.owner and c.index_name = i.index_name
         where i.owner = upper(p_owner) and i.index_name = upper(p_index);
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_pell_ret_1;
  END index_detail;

  FUNCTION list_tables RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || table_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_tables order by 1;
    RETURN l_pell_ret_1;
  END list_tables;

  FUNCTION list_views RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || view_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_views order by 1;
    RETURN l_pell_ret_1;
  END list_views;

  FUNCTION list_packages RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select distinct owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects
         where object_type = 'PACKAGE' order by 1;
    RETURN l_pell_ret_1;
  END list_packages;

  FUNCTION list_functions RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects
         where object_type = 'FUNCTION' order by 1;
    RETURN l_pell_ret_1;
  END list_functions;

  FUNCTION list_procedures RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects
         where object_type = 'PROCEDURE' order by 1;
    RETURN l_pell_ret_1;
  END list_procedures;

  FUNCTION list_sequences RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select sequence_owner || '.' || sequence_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_sequences order by 1;
    RETURN l_pell_ret_1;
  END list_sequences;

  FUNCTION list_types RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || type_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_types order by 1;
    RETURN l_pell_ret_1;
  END list_types;

  FUNCTION list_triggers RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || trigger_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_triggers order by 1;
    RETURN l_pell_ret_1;
  END list_triggers;

  FUNCTION list_invalid RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects
         where status = 'INVALID' order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_invalid;

  FUNCTION list_objects_info RETURN t_catalog_ObjectInfo_list IS
    l_pell_ret_1 t_catalog_ObjectInfo_list;
  BEGIN
    select owner || '.' || object_name as name,
               object_type, status, last_ddl_time
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_objects_info;

  FUNCTION list_invalid_info RETURN t_catalog_ObjectInfo_list IS
    l_pell_ret_1 t_catalog_ObjectInfo_list;
  BEGIN
    select owner || '.' || object_name as name,
               object_type, status, last_ddl_time
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects where status = 'INVALID'
         order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_invalid_info;

  FUNCTION columns_of(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_catalog_ColumnInfo_list IS
    l_pell_ret_1 t_catalog_ColumnInfo_list;
  BEGIN
    select column_name as name, data_type, nullable, column_id, data_length
      BULK COLLECT INTO l_pell_ret_1
      FROM all_tab_columns
         where owner = upper(p_owner) and table_name = upper(p_table)
         order by column_id;
    RETURN l_pell_ret_1;
  END columns_of;

  FUNCTION constraints_of(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_catalog_ConstraintInfo_list IS
    l_pell_ret_1 t_catalog_ConstraintInfo_list;
  BEGIN
    select c.constraint_name as name, c.constraint_type, cc.column_name,
               c.search_condition, c.r_constraint_name as r_constraint
      BULK COLLECT INTO l_pell_ret_1
      FROM all_constraints c
          left join all_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
         where c.owner = upper(p_owner) and c.table_name = upper(p_table)
         order by c.constraint_name, cc.position;
    RETURN l_pell_ret_1;
  END constraints_of;

  FUNCTION indexes_of(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_catalog_IndexInfo_list IS
    l_pell_ret_1 t_catalog_IndexInfo_list;
  BEGIN
    select i.index_name as name, i.uniqueness, ic.column_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_indexes i
          join all_ind_columns ic
            on ic.index_owner = i.owner and ic.index_name = i.index_name
         where i.table_owner = upper(p_owner) and i.table_name = upper(p_table)
         order by i.index_name, ic.column_position;
    RETURN l_pell_ret_1;
  END indexes_of;

  FUNCTION foreign_keys_of(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_catalog_ForeignKeyInfo_list IS
    l_pell_ret_1 t_catalog_ForeignKeyInfo_list;
  BEGIN
    select c.constraint_name as name, cc.column_name,
               rc.table_name as r_table, rcc.column_name as r_column_name, c.delete_rule
      BULK COLLECT INTO l_pell_ret_1
      FROM all_constraints c
          join all_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join all_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
          join all_cons_columns rcc
            on rcc.owner = rc.owner and rcc.constraint_name = rc.constraint_name
           and rcc.position = cc.position
         where c.constraint_type = 'R'
           and c.owner = upper(p_owner) and c.table_name = upper(p_table)
         order by c.constraint_name, cc.position;
    RETURN l_pell_ret_1;
  END foreign_keys_of;

  FUNCTION errors_for(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_catalog_ErrorInfo_list IS
    l_pell_ret_1 t_catalog_ErrorInfo_list;
  BEGIN
    select name, line, position, text as message
      BULK COLLECT INTO l_pell_ret_1
      FROM all_errors
         where owner = upper(p_owner) and name = upper(p_name)
         order by sequence;
    RETURN l_pell_ret_1;
  END errors_for;

  FUNCTION source_of(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM all_source
         where owner = upper(p_owner) and name = upper(p_name)
         order by type, line;
    RETURN l_pell_ret_1;
  END source_of;

  FUNCTION spec_of(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM all_source
         where owner = upper(p_owner) and name = upper(p_name) and type = 'PACKAGE'
         order by line;
    RETURN l_pell_ret_1;
  END spec_of;

  FUNCTION body_of(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM all_source
         where owner = upper(p_owner) and name = upper(p_name) and type = 'PACKAGE BODY'
         order by line;
    RETURN l_pell_ret_1;
  END body_of;

  FUNCTION fk_tree(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || c.table_name
               || ' -> ' || rc.table_name || ' (' || cc.column_name || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM all_constraints c
          join all_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join all_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
         where c.constraint_type = 'R'
         start with c.owner = upper(p_owner) and c.table_name = upper(p_table)
         connect by nocycle prior rc.owner = c.owner and prior rc.table_name = c.table_name
         order siblings by c.table_name;
    RETURN l_pell_ret_1;
  END fk_tree;

  FUNCTION deps_tree(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || referenced_name
               || ' (' || referenced_type || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies
         start with owner = upper(p_owner) and name = upper(p_name)
         connect by nocycle prior referenced_owner = owner and prior referenced_name = name
         order siblings by referenced_name;
    RETURN l_pell_ret_1;
  END deps_tree;

  FUNCTION dependents_tree(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || d.name || ' (' || d.type || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies d
         start with d.referenced_owner = upper(p_owner) and d.referenced_name = upper(p_name)
         connect by nocycle d.referenced_owner = prior d.owner and d.referenced_name = prior d.name
         order siblings by d.name;
    RETURN l_pell_ret_1;
  END dependents_tree;

  FUNCTION fk_mermaid(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select 'flowchart LR' as line
      BULK COLLECT INTO l_pell_ret_1
      FROM dual
        union all
        select '  ' || c.table_name || ' -->|' || cc.column_name || '| ' || rc.table_name
          from all_constraints c
          join all_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join all_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
         where c.constraint_type = 'R'
           and ((c.owner = upper(p_owner) and c.table_name = upper(p_table))
             or (rc.owner = upper(p_owner) and rc.table_name = upper(p_table)))
         order by 1;
    RETURN l_pell_ret_1;
  END fk_mermaid;

  FUNCTION depends_on(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select referenced_owner || '.' || referenced_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies
         where owner = upper(p_owner) and name = upper(p_name)
         order by 1;
    RETURN l_pell_ret_1;
  END depends_on;

  FUNCTION dependents_of(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies
         where referenced_owner = upper(p_owner) and referenced_name = upper(p_name)
         order by 1;
    RETURN l_pell_ret_1;
  END dependents_of;
END catalog_all;
/