-- ======================================================================
-- Generated by pell 0.0.1 from module catalog
--   Source:     compiler/runtime/catalog.pell
--   SHA-256:    84d4797c8335cb8c9a20f94205a3a5c916dc67b5601c14b9a8476c11a2ef2eb5
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     all_cons_columns
--     all_constraints
--     all_dependencies
--     all_errors
--     all_ind_columns
--     all_indexes
--     all_objects
--     all_sequences
--     all_source
--     all_tab_columns
--     all_tables
--     all_triggers
--     all_types
--     all_views
--     dba_cons_columns
--     dba_constraints
--     dba_dependencies
--     dba_errors
--     dba_ind_columns
--     dba_indexes
--     dba_objects
--     dba_sequences
--     dba_source
--     dba_tab_columns
--     dba_tables
--     dba_triggers
--     dba_types
--     dba_views
--     dual
--     user_cons_columns
--     user_constraints
--     user_dependencies
--     user_errors
--     user_ind_columns
--     user_indexes
--     user_objects
--     user_sequences
--     user_source
--     user_tab_columns
--     user_tables
--     user_triggers
--     user_types
--     user_views
-- ======================================================================

CREATE OR REPLACE PACKAGE catalog AS
  TYPE t_objectinfo IS RECORD (
    name VARCHAR2(4000),
    object_type VARCHAR2(4000),
    status VARCHAR2(4000),
    last_ddl_time DATE
  );
  TYPE t_columninfo IS RECORD (
    name VARCHAR2(4000),
    data_type VARCHAR2(4000),
    nullable VARCHAR2(4000),
    column_id NUMBER,
    data_length NUMBER
  );
  TYPE t_constraintinfo IS RECORD (
    name VARCHAR2(4000),
    constraint_type VARCHAR2(4000),
    column_name VARCHAR2(4000),
    search_condition VARCHAR2(4000),
    r_constraint VARCHAR2(4000)
  );
  TYPE t_indexinfo IS RECORD (
    name VARCHAR2(4000),
    uniqueness VARCHAR2(4000),
    column_name VARCHAR2(4000)
  );
  TYPE t_indexdetail IS RECORD (
    cols_found NUMBER,
    table_name VARCHAR2(4000),
    cols VARCHAR2(4000),
    uniqueness VARCHAR2(4000)
  );
  TYPE t_foreignkeyinfo IS RECORD (
    name VARCHAR2(4000),
    column_name VARCHAR2(4000),
    r_table VARCHAR2(4000),
    r_column_name VARCHAR2(4000),
    delete_rule VARCHAR2(4000)
  );
  TYPE t_errorinfo IS RECORD (
    name VARCHAR2(4000),
    line NUMBER,
    position NUMBER,
    message VARCHAR2(4000)
  );
  TYPE t_text_list IS TABLE OF VARCHAR2(4000) INDEX BY PLS_INTEGER;
  TYPE t_ObjectInfo_list IS TABLE OF t_objectinfo INDEX BY PLS_INTEGER;
  TYPE t_ColumnInfo_list IS TABLE OF t_columninfo INDEX BY PLS_INTEGER;
  TYPE t_ConstraintInfo_list IS TABLE OF t_constraintinfo INDEX BY PLS_INTEGER;
  TYPE t_IndexInfo_list IS TABLE OF t_indexinfo INDEX BY PLS_INTEGER;
  TYPE t_ForeignKeyInfo_list IS TABLE OF t_foreignkeyinfo INDEX BY PLS_INTEGER;
  TYPE t_ErrorInfo_list IS TABLE OF t_errorinfo INDEX BY PLS_INTEGER;
  FUNCTION list_tables RETURN t_text_list;
  FUNCTION list_views RETURN t_text_list;
  FUNCTION list_packages RETURN t_text_list;
  FUNCTION list_functions RETURN t_text_list;
  FUNCTION list_procedures RETURN t_text_list;
  FUNCTION list_sequences RETURN t_text_list;
  FUNCTION list_types RETURN t_text_list;
  FUNCTION list_triggers RETURN t_text_list;
  FUNCTION list_invalid RETURN t_text_list;
  FUNCTION list_objects_info RETURN t_ObjectInfo_list;
  FUNCTION list_invalid_info RETURN t_ObjectInfo_list;
  FUNCTION columns_of(p_table IN VARCHAR2) RETURN t_ColumnInfo_list;
  FUNCTION constraints_of(p_table IN VARCHAR2) RETURN t_ConstraintInfo_list;
  FUNCTION indexes_of(p_table IN VARCHAR2) RETURN t_IndexInfo_list;
  FUNCTION index_detail(p_owner IN VARCHAR2, p_index IN VARCHAR2) RETURN t_indexdetail;
  FUNCTION foreign_keys_of(p_table IN VARCHAR2) RETURN t_ForeignKeyInfo_list;
  FUNCTION errors_for(p_name IN VARCHAR2) RETURN t_ErrorInfo_list;
  FUNCTION source_of(p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION spec_of(p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION body_of(p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION fk_tree(p_table IN VARCHAR2) RETURN t_text_list;
  FUNCTION deps_tree(p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION dependents_tree(p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION fk_mermaid(p_table IN VARCHAR2) RETURN t_text_list;
  FUNCTION depends_on(p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION dependents_of(p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION list_tables_all RETURN t_text_list;
  FUNCTION list_views_all RETURN t_text_list;
  FUNCTION list_packages_all RETURN t_text_list;
  FUNCTION list_functions_all RETURN t_text_list;
  FUNCTION list_procedures_all RETURN t_text_list;
  FUNCTION list_sequences_all RETURN t_text_list;
  FUNCTION list_types_all RETURN t_text_list;
  FUNCTION list_triggers_all RETURN t_text_list;
  FUNCTION list_invalid_all RETURN t_text_list;
  FUNCTION list_objects_info_all RETURN t_ObjectInfo_list;
  FUNCTION list_invalid_info_all RETURN t_ObjectInfo_list;
  FUNCTION columns_of_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ColumnInfo_list;
  FUNCTION constraints_of_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ConstraintInfo_list;
  FUNCTION indexes_of_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_IndexInfo_list;
  FUNCTION foreign_keys_of_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ForeignKeyInfo_list;
  FUNCTION errors_for_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_ErrorInfo_list;
  FUNCTION source_of_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION spec_of_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION body_of_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION fk_tree_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list;
  FUNCTION deps_tree_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION dependents_tree_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION fk_mermaid_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list;
  FUNCTION depends_on_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION dependents_of_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION list_tables_dba RETURN t_text_list;
  FUNCTION list_views_dba RETURN t_text_list;
  FUNCTION list_packages_dba RETURN t_text_list;
  FUNCTION list_functions_dba RETURN t_text_list;
  FUNCTION list_procedures_dba RETURN t_text_list;
  FUNCTION list_sequences_dba RETURN t_text_list;
  FUNCTION list_types_dba RETURN t_text_list;
  FUNCTION list_triggers_dba RETURN t_text_list;
  FUNCTION list_invalid_dba RETURN t_text_list;
  FUNCTION list_objects_info_dba RETURN t_ObjectInfo_list;
  FUNCTION list_invalid_info_dba RETURN t_ObjectInfo_list;
  FUNCTION columns_of_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ColumnInfo_list;
  FUNCTION constraints_of_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ConstraintInfo_list;
  FUNCTION indexes_of_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_IndexInfo_list;
  FUNCTION foreign_keys_of_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ForeignKeyInfo_list;
  FUNCTION errors_for_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_ErrorInfo_list;
  FUNCTION source_of_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION spec_of_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION body_of_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION fk_tree_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list;
  FUNCTION deps_tree_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION dependents_tree_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION fk_mermaid_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list;
  FUNCTION depends_on_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION dependents_of_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list;
END catalog;
/

CREATE OR REPLACE PACKAGE BODY catalog AS

  FUNCTION list_tables RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select table_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_tables order by 1;
    RETURN l_pell_ret_1;
  END list_tables;

  FUNCTION list_views RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select view_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_views order by 1;
    RETURN l_pell_ret_1;
  END list_views;

  FUNCTION list_packages RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select distinct object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_objects
         where object_type = 'PACKAGE'
         order by 1;
    RETURN l_pell_ret_1;
  END list_packages;

  FUNCTION list_functions RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_objects
         where object_type = 'FUNCTION'
         order by 1;
    RETURN l_pell_ret_1;
  END list_functions;

  FUNCTION list_procedures RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_objects
         where object_type = 'PROCEDURE'
         order by 1;
    RETURN l_pell_ret_1;
  END list_procedures;

  FUNCTION list_sequences RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select sequence_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_sequences order by 1;
    RETURN l_pell_ret_1;
  END list_sequences;

  FUNCTION list_types RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select type_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_types order by 1;
    RETURN l_pell_ret_1;
  END list_types;

  FUNCTION list_triggers RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select trigger_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_triggers order by 1;
    RETURN l_pell_ret_1;
  END list_triggers;

  FUNCTION list_invalid RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_objects
         where status = 'INVALID'
         order by object_type, object_name;
    RETURN l_pell_ret_1;
  END list_invalid;

  FUNCTION list_objects_info RETURN t_ObjectInfo_list IS
    l_pell_ret_1 t_ObjectInfo_list;
  BEGIN
    select object_name as name,
               object_type,
               status,
               last_ddl_time
      BULK COLLECT INTO l_pell_ret_1
      FROM user_objects
         order by object_type, object_name;
    RETURN l_pell_ret_1;
  END list_objects_info;

  FUNCTION list_invalid_info RETURN t_ObjectInfo_list IS
    l_pell_ret_1 t_ObjectInfo_list;
  BEGIN
    select object_name as name,
               object_type,
               status,
               last_ddl_time
      BULK COLLECT INTO l_pell_ret_1
      FROM user_objects
         where status = 'INVALID'
         order by object_type, object_name;
    RETURN l_pell_ret_1;
  END list_invalid_info;

  FUNCTION columns_of(p_table IN VARCHAR2) RETURN t_ColumnInfo_list IS
    l_pell_ret_1 t_ColumnInfo_list;
  BEGIN
    select column_name as name,
               data_type,
               nullable,
               column_id,
               data_length
      BULK COLLECT INTO l_pell_ret_1
      FROM user_tab_columns
         where table_name = upper(p_table)
         order by column_id;
    RETURN l_pell_ret_1;
  END columns_of;

  FUNCTION constraints_of(p_table IN VARCHAR2) RETURN t_ConstraintInfo_list IS
    l_pell_ret_1 t_ConstraintInfo_list;
  BEGIN
    select c.constraint_name as name,
               c.constraint_type,
               cc.column_name,
               c.search_condition,
               c.r_constraint_name as r_constraint
      BULK COLLECT INTO l_pell_ret_1
      FROM user_constraints c
          left join user_cons_columns cc
            on cc.constraint_name = c.constraint_name
         where c.table_name = upper(p_table)
         order by c.constraint_name, cc.position;
    RETURN l_pell_ret_1;
  END constraints_of;

  FUNCTION indexes_of(p_table IN VARCHAR2) RETURN t_IndexInfo_list IS
    l_pell_ret_1 t_IndexInfo_list;
  BEGIN
    select i.index_name as name,
               i.uniqueness,
               ic.column_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_indexes i
          join user_ind_columns ic
            on ic.index_name = i.index_name
         where i.table_name = upper(p_table)
         order by i.index_name, ic.column_position;
    RETURN l_pell_ret_1;
  END indexes_of;

  FUNCTION index_detail(p_owner IN VARCHAR2, p_index IN VARCHAR2) RETURN t_indexdetail IS
    l_pell_ret_1 t_indexdetail;
  BEGIN
    BEGIN
      select count(*) as cols_found,
               max(i.table_name) as table_name,
               listagg(c.column_name, ', ')
                 within group (order by c.column_position) as cols,
               max(i.uniqueness) as uniqueness
      INTO l_pell_ret_1
      FROM all_indexes i
          join all_ind_columns c
            on c.index_owner = i.owner and c.index_name = i.index_name
         where i.owner = upper(p_owner) and i.index_name = upper(p_index);
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_pell_ret_1;
  END index_detail;

  FUNCTION foreign_keys_of(p_table IN VARCHAR2) RETURN t_ForeignKeyInfo_list IS
    l_pell_ret_1 t_ForeignKeyInfo_list;
  BEGIN
    select c.constraint_name as name,
               cc.column_name,
               rc.table_name as r_table,
               rcc.column_name as r_column_name,
               c.delete_rule
      BULK COLLECT INTO l_pell_ret_1
      FROM user_constraints c
          join user_cons_columns cc
            on cc.constraint_name = c.constraint_name
          join user_constraints rc
            on rc.constraint_name = c.r_constraint_name
          join user_cons_columns rcc
            on rcc.constraint_name = rc.constraint_name
           and rcc.position = cc.position
         where c.constraint_type = 'R'
           and c.table_name = upper(p_table)
         order by c.constraint_name, cc.position;
    RETURN l_pell_ret_1;
  END foreign_keys_of;

  FUNCTION errors_for(p_name IN VARCHAR2) RETURN t_ErrorInfo_list IS
    l_pell_ret_1 t_ErrorInfo_list;
  BEGIN
    select name,
               line,
               position,
               text as message
      BULK COLLECT INTO l_pell_ret_1
      FROM user_errors
         where name = upper(p_name)
         order by sequence;
    RETURN l_pell_ret_1;
  END errors_for;

  FUNCTION source_of(p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM user_source
         where name = upper(p_name)
         order by type, line;
    RETURN l_pell_ret_1;
  END source_of;

  FUNCTION spec_of(p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM user_source
         where name = upper(p_name) and type = 'PACKAGE'
         order by line;
    RETURN l_pell_ret_1;
  END spec_of;

  FUNCTION body_of(p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM user_source
         where name = upper(p_name) and type = 'PACKAGE BODY'
         order by line;
    RETURN l_pell_ret_1;
  END body_of;

  FUNCTION fk_tree(p_table IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || c.table_name
               || ' -> ' || rc.table_name
               || ' (' || cc.column_name || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM user_constraints c
          join user_cons_columns cc on cc.constraint_name = c.constraint_name
          join user_constraints rc on rc.constraint_name = c.r_constraint_name
         where c.constraint_type = 'R'
         start with c.table_name = upper(p_table)
         connect by nocycle prior rc.table_name = c.table_name
         order siblings by c.table_name;
    RETURN l_pell_ret_1;
  END fk_tree;

  FUNCTION deps_tree(p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || referenced_name
               || ' (' || referenced_type || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM user_dependencies
         start with name = upper(p_name)
         connect by nocycle prior referenced_name = name
         order siblings by referenced_name;
    RETURN l_pell_ret_1;
  END deps_tree;

  FUNCTION dependents_tree(p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || d.name
               || ' (' || d.type || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies d
         where d.referenced_owner = user
         start with d.referenced_name = upper(p_name)
         connect by nocycle d.referenced_name = prior d.name
         order siblings by d.name;
    RETURN l_pell_ret_1;
  END dependents_tree;

  FUNCTION fk_mermaid(p_table IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select 'flowchart LR' as line
      BULK COLLECT INTO l_pell_ret_1
      FROM dual
        union all
        select '  ' || c.table_name || ' -->|' || cc.column_name
               || '| ' || rc.table_name
          from user_constraints c
          join user_cons_columns cc on cc.constraint_name = c.constraint_name
          join user_constraints rc on rc.constraint_name = c.r_constraint_name
         where c.constraint_type = 'R'
           and (c.table_name = upper(p_table) or rc.table_name = upper(p_table))
         order by 1;
    RETURN l_pell_ret_1;
  END fk_mermaid;

  FUNCTION depends_on(p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select referenced_owner || '.' || referenced_name
      BULK COLLECT INTO l_pell_ret_1
      FROM user_dependencies
         where name = upper(p_name)
         order by 1;
    RETURN l_pell_ret_1;
  END depends_on;

  FUNCTION dependents_of(p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies
         where referenced_name = upper(p_name)
           and referenced_owner = user
         order by 1;
    RETURN l_pell_ret_1;
  END dependents_of;

  FUNCTION list_tables_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || table_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_tables order by 1;
    RETURN l_pell_ret_1;
  END list_tables_all;

  FUNCTION list_views_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || view_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_views order by 1;
    RETURN l_pell_ret_1;
  END list_views_all;

  FUNCTION list_packages_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select distinct owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects
         where object_type = 'PACKAGE' order by 1;
    RETURN l_pell_ret_1;
  END list_packages_all;

  FUNCTION list_functions_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects
         where object_type = 'FUNCTION' order by 1;
    RETURN l_pell_ret_1;
  END list_functions_all;

  FUNCTION list_procedures_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects
         where object_type = 'PROCEDURE' order by 1;
    RETURN l_pell_ret_1;
  END list_procedures_all;

  FUNCTION list_sequences_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select sequence_owner || '.' || sequence_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_sequences order by 1;
    RETURN l_pell_ret_1;
  END list_sequences_all;

  FUNCTION list_types_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || type_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_types order by 1;
    RETURN l_pell_ret_1;
  END list_types_all;

  FUNCTION list_triggers_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || trigger_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_triggers order by 1;
    RETURN l_pell_ret_1;
  END list_triggers_all;

  FUNCTION list_invalid_all RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects
         where status = 'INVALID' order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_invalid_all;

  FUNCTION list_objects_info_all RETURN t_ObjectInfo_list IS
    l_pell_ret_1 t_ObjectInfo_list;
  BEGIN
    select owner || '.' || object_name as name,
               object_type, status, last_ddl_time
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_objects_info_all;

  FUNCTION list_invalid_info_all RETURN t_ObjectInfo_list IS
    l_pell_ret_1 t_ObjectInfo_list;
  BEGIN
    select owner || '.' || object_name as name,
               object_type, status, last_ddl_time
      BULK COLLECT INTO l_pell_ret_1
      FROM all_objects where status = 'INVALID'
         order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_invalid_info_all;

  FUNCTION columns_of_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ColumnInfo_list IS
    l_pell_ret_1 t_ColumnInfo_list;
  BEGIN
    select column_name as name, data_type, nullable, column_id, data_length
      BULK COLLECT INTO l_pell_ret_1
      FROM all_tab_columns
         where owner = upper(p_owner) and table_name = upper(p_table)
         order by column_id;
    RETURN l_pell_ret_1;
  END columns_of_all;

  FUNCTION constraints_of_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ConstraintInfo_list IS
    l_pell_ret_1 t_ConstraintInfo_list;
  BEGIN
    select c.constraint_name as name, c.constraint_type, cc.column_name,
               c.search_condition, c.r_constraint_name as r_constraint
      BULK COLLECT INTO l_pell_ret_1
      FROM all_constraints c
          left join all_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
         where c.owner = upper(p_owner) and c.table_name = upper(p_table)
         order by c.constraint_name, cc.position;
    RETURN l_pell_ret_1;
  END constraints_of_all;

  FUNCTION indexes_of_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_IndexInfo_list IS
    l_pell_ret_1 t_IndexInfo_list;
  BEGIN
    select i.index_name as name, i.uniqueness, ic.column_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_indexes i
          join all_ind_columns ic
            on ic.index_owner = i.owner and ic.index_name = i.index_name
         where i.table_owner = upper(p_owner) and i.table_name = upper(p_table)
         order by i.index_name, ic.column_position;
    RETURN l_pell_ret_1;
  END indexes_of_all;

  FUNCTION foreign_keys_of_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ForeignKeyInfo_list IS
    l_pell_ret_1 t_ForeignKeyInfo_list;
  BEGIN
    select c.constraint_name as name, cc.column_name,
               rc.table_name as r_table, rcc.column_name as r_column_name, c.delete_rule
      BULK COLLECT INTO l_pell_ret_1
      FROM all_constraints c
          join all_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join all_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
          join all_cons_columns rcc
            on rcc.owner = rc.owner and rcc.constraint_name = rc.constraint_name
           and rcc.position = cc.position
         where c.constraint_type = 'R'
           and c.owner = upper(p_owner) and c.table_name = upper(p_table)
         order by c.constraint_name, cc.position;
    RETURN l_pell_ret_1;
  END foreign_keys_of_all;

  FUNCTION errors_for_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_ErrorInfo_list IS
    l_pell_ret_1 t_ErrorInfo_list;
  BEGIN
    select name, line, position, text as message
      BULK COLLECT INTO l_pell_ret_1
      FROM all_errors
         where owner = upper(p_owner) and name = upper(p_name)
         order by sequence;
    RETURN l_pell_ret_1;
  END errors_for_all;

  FUNCTION source_of_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM all_source
         where owner = upper(p_owner) and name = upper(p_name)
         order by type, line;
    RETURN l_pell_ret_1;
  END source_of_all;

  FUNCTION spec_of_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM all_source
         where owner = upper(p_owner) and name = upper(p_name) and type = 'PACKAGE'
         order by line;
    RETURN l_pell_ret_1;
  END spec_of_all;

  FUNCTION body_of_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM all_source
         where owner = upper(p_owner) and name = upper(p_name) and type = 'PACKAGE BODY'
         order by line;
    RETURN l_pell_ret_1;
  END body_of_all;

  FUNCTION fk_tree_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || c.table_name
               || ' -> ' || rc.table_name || ' (' || cc.column_name || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM all_constraints c
          join all_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join all_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
         where c.constraint_type = 'R'
         start with c.owner = upper(p_owner) and c.table_name = upper(p_table)
         connect by nocycle prior rc.owner = c.owner and prior rc.table_name = c.table_name
         order siblings by c.table_name;
    RETURN l_pell_ret_1;
  END fk_tree_all;

  FUNCTION deps_tree_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || referenced_name
               || ' (' || referenced_type || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies
         start with owner = upper(p_owner) and name = upper(p_name)
         connect by nocycle prior referenced_owner = owner and prior referenced_name = name
         order siblings by referenced_name;
    RETURN l_pell_ret_1;
  END deps_tree_all;

  FUNCTION dependents_tree_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || d.name || ' (' || d.type || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies d
         start with d.referenced_owner = upper(p_owner) and d.referenced_name = upper(p_name)
         connect by nocycle d.referenced_owner = prior d.owner and d.referenced_name = prior d.name
         order siblings by d.name;
    RETURN l_pell_ret_1;
  END dependents_tree_all;

  FUNCTION fk_mermaid_all(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select 'flowchart LR' as line
      BULK COLLECT INTO l_pell_ret_1
      FROM dual
        union all
        select '  ' || c.table_name || ' -->|' || cc.column_name || '| ' || rc.table_name
          from all_constraints c
          join all_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join all_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
         where c.constraint_type = 'R'
           and ((c.owner = upper(p_owner) and c.table_name = upper(p_table))
             or (rc.owner = upper(p_owner) and rc.table_name = upper(p_table)))
         order by 1;
    RETURN l_pell_ret_1;
  END fk_mermaid_all;

  FUNCTION depends_on_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select referenced_owner || '.' || referenced_name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies
         where owner = upper(p_owner) and name = upper(p_name)
         order by 1;
    RETURN l_pell_ret_1;
  END depends_on_all;

  FUNCTION dependents_of_all(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || name
      BULK COLLECT INTO l_pell_ret_1
      FROM all_dependencies
         where referenced_owner = upper(p_owner) and referenced_name = upper(p_name)
         order by 1;
    RETURN l_pell_ret_1;
  END dependents_of_all;

  FUNCTION list_tables_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || table_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_tables order by 1;
    RETURN l_pell_ret_1;
  END list_tables_dba;

  FUNCTION list_views_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || view_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_views order by 1;
    RETURN l_pell_ret_1;
  END list_views_dba;

  FUNCTION list_packages_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select distinct owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_objects
         where object_type = 'PACKAGE' order by 1;
    RETURN l_pell_ret_1;
  END list_packages_dba;

  FUNCTION list_functions_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_objects
         where object_type = 'FUNCTION' order by 1;
    RETURN l_pell_ret_1;
  END list_functions_dba;

  FUNCTION list_procedures_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_objects
         where object_type = 'PROCEDURE' order by 1;
    RETURN l_pell_ret_1;
  END list_procedures_dba;

  FUNCTION list_sequences_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select sequence_owner || '.' || sequence_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_sequences order by 1;
    RETURN l_pell_ret_1;
  END list_sequences_dba;

  FUNCTION list_types_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || type_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_types order by 1;
    RETURN l_pell_ret_1;
  END list_types_dba;

  FUNCTION list_triggers_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || trigger_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_triggers order by 1;
    RETURN l_pell_ret_1;
  END list_triggers_dba;

  FUNCTION list_invalid_dba RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || object_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_objects
         where status = 'INVALID' order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_invalid_dba;

  FUNCTION list_objects_info_dba RETURN t_ObjectInfo_list IS
    l_pell_ret_1 t_ObjectInfo_list;
  BEGIN
    select owner || '.' || object_name as name,
               object_type, status, last_ddl_time
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_objects order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_objects_info_dba;

  FUNCTION list_invalid_info_dba RETURN t_ObjectInfo_list IS
    l_pell_ret_1 t_ObjectInfo_list;
  BEGIN
    select owner || '.' || object_name as name,
               object_type, status, last_ddl_time
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_objects where status = 'INVALID'
         order by owner, object_type, object_name;
    RETURN l_pell_ret_1;
  END list_invalid_info_dba;

  FUNCTION columns_of_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ColumnInfo_list IS
    l_pell_ret_1 t_ColumnInfo_list;
  BEGIN
    select column_name as name, data_type, nullable, column_id, data_length
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_tab_columns
         where owner = upper(p_owner) and table_name = upper(p_table)
         order by column_id;
    RETURN l_pell_ret_1;
  END columns_of_dba;

  FUNCTION constraints_of_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ConstraintInfo_list IS
    l_pell_ret_1 t_ConstraintInfo_list;
  BEGIN
    select c.constraint_name as name, c.constraint_type, cc.column_name,
               c.search_condition, c.r_constraint_name as r_constraint
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_constraints c
          left join dba_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
         where c.owner = upper(p_owner) and c.table_name = upper(p_table)
         order by c.constraint_name, cc.position;
    RETURN l_pell_ret_1;
  END constraints_of_dba;

  FUNCTION indexes_of_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_IndexInfo_list IS
    l_pell_ret_1 t_IndexInfo_list;
  BEGIN
    select i.index_name as name, i.uniqueness, ic.column_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_indexes i
          join dba_ind_columns ic
            on ic.index_owner = i.owner and ic.index_name = i.index_name
         where i.table_owner = upper(p_owner) and i.table_name = upper(p_table)
         order by i.index_name, ic.column_position;
    RETURN l_pell_ret_1;
  END indexes_of_dba;

  FUNCTION foreign_keys_of_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_ForeignKeyInfo_list IS
    l_pell_ret_1 t_ForeignKeyInfo_list;
  BEGIN
    select c.constraint_name as name, cc.column_name,
               rc.table_name as r_table, rcc.column_name as r_column_name, c.delete_rule
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_constraints c
          join dba_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join dba_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
          join dba_cons_columns rcc
            on rcc.owner = rc.owner and rcc.constraint_name = rc.constraint_name
           and rcc.position = cc.position
         where c.constraint_type = 'R'
           and c.owner = upper(p_owner) and c.table_name = upper(p_table)
         order by c.constraint_name, cc.position;
    RETURN l_pell_ret_1;
  END foreign_keys_of_dba;

  FUNCTION errors_for_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_ErrorInfo_list IS
    l_pell_ret_1 t_ErrorInfo_list;
  BEGIN
    select name, line, position, text as message
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_errors
         where owner = upper(p_owner) and name = upper(p_name)
         order by sequence;
    RETURN l_pell_ret_1;
  END errors_for_dba;

  FUNCTION source_of_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_source
         where owner = upper(p_owner) and name = upper(p_name)
         order by type, line;
    RETURN l_pell_ret_1;
  END source_of_dba;

  FUNCTION spec_of_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_source
         where owner = upper(p_owner) and name = upper(p_name) and type = 'PACKAGE'
         order by line;
    RETURN l_pell_ret_1;
  END spec_of_dba;

  FUNCTION body_of_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select text
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_source
         where owner = upper(p_owner) and name = upper(p_name) and type = 'PACKAGE BODY'
         order by line;
    RETURN l_pell_ret_1;
  END body_of_dba;

  FUNCTION fk_tree_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || c.table_name
               || ' -> ' || rc.table_name || ' (' || cc.column_name || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_constraints c
          join dba_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join dba_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
         where c.constraint_type = 'R'
         start with c.owner = upper(p_owner) and c.table_name = upper(p_table)
         connect by nocycle prior rc.owner = c.owner and prior rc.table_name = c.table_name
         order siblings by c.table_name;
    RETURN l_pell_ret_1;
  END fk_tree_dba;

  FUNCTION deps_tree_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || referenced_name
               || ' (' || referenced_type || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_dependencies
         start with owner = upper(p_owner) and name = upper(p_name)
         connect by nocycle prior referenced_owner = owner and prior referenced_name = name
         order siblings by referenced_name;
    RETURN l_pell_ret_1;
  END deps_tree_dba;

  FUNCTION dependents_tree_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select lpad(' ', 2 * (level - 1)) || d.name || ' (' || d.type || ')'
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_dependencies d
         start with d.referenced_owner = upper(p_owner) and d.referenced_name = upper(p_name)
         connect by nocycle d.referenced_owner = prior d.owner and d.referenced_name = prior d.name
         order siblings by d.name;
    RETURN l_pell_ret_1;
  END dependents_tree_dba;

  FUNCTION fk_mermaid_dba(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select 'flowchart LR' as line
      BULK COLLECT INTO l_pell_ret_1
      FROM dual
        union all
        select '  ' || c.table_name || ' -->|' || cc.column_name || '| ' || rc.table_name
          from dba_constraints c
          join dba_cons_columns cc
            on cc.owner = c.owner and cc.constraint_name = c.constraint_name
          join dba_constraints rc
            on rc.owner = c.r_owner and rc.constraint_name = c.r_constraint_name
         where c.constraint_type = 'R'
           and ((c.owner = upper(p_owner) and c.table_name = upper(p_table))
             or (rc.owner = upper(p_owner) and rc.table_name = upper(p_table)))
         order by 1;
    RETURN l_pell_ret_1;
  END fk_mermaid_dba;

  FUNCTION depends_on_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select referenced_owner || '.' || referenced_name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_dependencies
         where owner = upper(p_owner) and name = upper(p_name)
         order by 1;
    RETURN l_pell_ret_1;
  END depends_on_dba;

  FUNCTION dependents_of_dba(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
  BEGIN
    select owner || '.' || name
      BULK COLLECT INTO l_pell_ret_1
      FROM dba_dependencies
         where referenced_owner = upper(p_owner) and referenced_name = upper(p_name)
         order by 1;
    RETURN l_pell_ret_1;
  END dependents_of_dba;
END catalog;
/