-- ======================================================================
-- Generated by pell 0.0.1 from module logger
--   Source:     runtime/logger.pell
--   SHA-256:    de4551b34f7ef3400e97f9a964fc6e18ddbe3d25d162f7ab72cf5e1887470c39
--   pell git:   989cd68 + uncommitted:4b4092f2
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
--   Built at:   2026-06-03 02:24:15 UTC
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     dbms_output
-- ======================================================================

CREATE OR REPLACE PACKAGE logger AS
  PROCEDURE info(p_msg IN VARCHAR2);
  PROCEDURE warn(p_msg IN VARCHAR2);
  PROCEDURE err(p_msg IN VARCHAR2);
  PROCEDURE debug(p_msg IN VARCHAR2);
  PROCEDURE trace(p_msg IN VARCHAR2);
END logger;
/

CREATE OR REPLACE PACKAGE BODY logger AS

  PROCEDURE info(p_msg IN VARCHAR2) IS
  BEGIN
    dbms_output.put_line(('INFO:  ' || p_msg));
  END info;

  PROCEDURE warn(p_msg IN VARCHAR2) IS
  BEGIN
    dbms_output.put_line(('WARN:  ' || p_msg));
  END warn;

  PROCEDURE err(p_msg IN VARCHAR2) IS
  BEGIN
    dbms_output.put_line(('ERROR: ' || p_msg));
  END err;

  PROCEDURE debug(p_msg IN VARCHAR2) IS
  BEGIN
    dbms_output.put_line(('DEBUG: ' || p_msg));
  END debug;

  PROCEDURE trace(p_msg IN VARCHAR2) IS
  BEGIN
    dbms_output.put_line(('TRACE: ' || p_msg));
  END trace;
END logger;
/
