-- pell_runtime — merged across the project
-- Generated by `pell runtime`; do not edit by hand.

CREATE OR REPLACE CONTEXT pell_err USING pell_runtime;

CREATE OR REPLACE PACKAGE pell_runtime AS
  PROCEDURE set_err(p_key IN VARCHAR2, p_payload IN VARCHAR2);
  PROCEDURE clear_err(p_key IN VARCHAR2);
  FUNCTION  get_err(p_key IN VARCHAR2) RETURN VARCHAR2;

  hr_employees_notfound EXCEPTION;
  PRAGMA EXCEPTION_INIT(hr_employees_notfound, -20100);
  hr_employees_policyviolation EXCEPTION;
  PRAGMA EXCEPTION_INIT(hr_employees_policyviolation, -20101);
  billing_charges_overdraft EXCEPTION;
  PRAGMA EXCEPTION_INIT(billing_charges_overdraft, -20102);
  billing_charges_accountfrozen EXCEPTION;
  PRAGMA EXCEPTION_INIT(billing_charges_accountfrozen, -20103);
  inventory_skus_duplicatecode EXCEPTION;
  PRAGMA EXCEPTION_INIT(inventory_skus_duplicatecode, -20104);
  orders_fulfillment_ordernotfound EXCEPTION;
  PRAGMA EXCEPTION_INIT(orders_fulfillment_ordernotfound, -20105);
  orders_fulfillment_invalidstatus EXCEPTION;
  PRAGMA EXCEPTION_INIT(orders_fulfillment_invalidstatus, -20106);
  orders_fulfillment_insufficientinventory EXCEPTION;
  PRAGMA EXCEPTION_INIT(orders_fulfillment_insufficientinventory, -20107);
END pell_runtime;
/

CREATE OR REPLACE PACKAGE BODY pell_runtime AS
  PROCEDURE set_err(p_key IN VARCHAR2, p_payload IN VARCHAR2) IS
  BEGIN
    DBMS_SESSION.SET_CONTEXT('pell_err', p_key, p_payload);
  END set_err;

  PROCEDURE clear_err(p_key IN VARCHAR2) IS
  BEGIN
    DBMS_SESSION.CLEAR_CONTEXT('pell_err', p_key);
  END clear_err;

  FUNCTION get_err(p_key IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN SYS_CONTEXT('pell_err', p_key);
  END get_err;
END pell_runtime;
/
