-- ======================================================================
-- Generated by pell 0.0.1 from module hello
--   Source:     compiler/examples/01_hello.pell
--   SHA-256:    1102b38e28a0b1055be1a8a458dbd224a9bdd40d4163eb400dc3a5bd86cf3f20
--   pell git:   4b9e74a
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     collections_linked_list
--     logger
-- ======================================================================

CREATE OR REPLACE PACKAGE hello AS
  FUNCTION greet(p_name IN VARCHAR2) RETURN VARCHAR2;
END hello;
/

CREATE OR REPLACE PACKAGE BODY hello AS
  TYPE t_number_list IS TABLE OF NUMBER INDEX BY PLS_INTEGER;

  FUNCTION greet(p_name IN VARCHAR2) RETURN VARCHAR2 IS
    l_a collections_linked_list.t_summary;
    l_result t_intlist;
    l_pell_arg_1 t_number_list;
  BEGIN
    logger.info(p_name);
    logger.err('test');
    l_a.count := 0;
    l_a.total := 0;
    l_a.contains_zero := FALSE;
    l_pell_arg_1(1) := 1;
    l_pell_arg_1(2) := 2;
    l_pell_arg_1(3) := 3;
    l_pell_arg_1(4) := 4;
    l_pell_arg_1(5) := 5;
    l_pell_arg_1(6) := 6;
    l_pell_arg_1(7) := 7;
    l_pell_arg_1(8) := 8;
    l_result := collections_linked_list.from_list(l_pell_arg_1);
    RETURN (l_a.count || ' ' || TO_CHAR(l_result) || ' ' || l_a.total);
  END greet;
END hello;
/