-- Generated by pell v0 from module hello
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE hello AS
  PROCEDURE greet(p_name IN VARCHAR2);
END hello;
/

CREATE OR REPLACE PACKAGE BODY hello AS

  PROCEDURE greet(p_name IN VARCHAR2) IS
  BEGIN
    log.info(p_name);
  END greet;
END hello;
/