-- ======================================================================
-- Generated by pell 0.0.1 from module hello
--   Source:     examples/01_hello.pell
--   SHA-256:    e39af9c9e3454212b4ae2ec64054f840c96f4957f53311612cbda8af2ab81791
--   pell git:   f73a136
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     log
-- ======================================================================

CREATE OR REPLACE PACKAGE hello AS
  PROCEDURE greet(p_name IN VARCHAR2);
END hello;
/

CREATE OR REPLACE PACKAGE BODY hello AS

  PROCEDURE greet(p_name IN VARCHAR2) IS
  BEGIN
    log.info(p_name);
  END greet;
END hello;
/