-- ======================================================================
-- Generated by pell 0.0.1 from module hr.employees
--   Source:     compiler/examples/02_employees.pell
--   SHA-256:    8f6063c614024132e0a7a864093d2ce8d6dd3cab4327c692ee39ec8c606f47f9
--   pell git:   56a1ae1
--   Target:     Oracle 23
--   Schema:     hr
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     employees
--   packages:
--     pell_runtime
-- ======================================================================

-- Additions to pell_runtime for module hr.employees:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   hr_employees_notfound EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(hr_employees_notfound, -20100);
--   hr_employees_policyviolation EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(hr_employees_policyviolation, -20101);

CREATE OR REPLACE PACKAGE hr.employees AS
  TYPE t_employee IS RECORD (
    id NUMBER,
    name VARCHAR2(4000),
    email VARCHAR2(4000),
    grade NUMBER
  );
  FUNCTION find_employee(p_id IN NUMBER) RETURN t_employee;
  PROCEDURE promote(p_id IN NUMBER);
END employees;
/

CREATE OR REPLACE PACKAGE BODY hr.employees AS

  FUNCTION find_employee(p_id IN NUMBER) RETURN t_employee IS
    l_row t_employee;
  BEGIN
    BEGIN
      select id, name, email, grade
      INTO l_row
      FROM employees where id = p_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        pell_runtime.set_err('hr_employees_notfound:1', '{}');
        RAISE pell_runtime.hr_employees_notfound;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_row;
  END find_employee;

  PROCEDURE promote(p_id IN NUMBER) IS
    l_e t_employee;
  BEGIN
    l_e := find_employee(p_id);
    IF (l_e.grade >= 9) THEN
      pell_runtime.set_err('hr_employees_policyviolation:1', JSON_OBJECT('reason' VALUE 'already at max grade'));
      RAISE pell_runtime.hr_employees_policyviolation;
    END IF;
    update employees set grade = grade + 1 where id = p_id;
    RETURN;
  END promote;
END employees;
/