-- Generated by pell v0 from module hr.employees
-- DO NOT EDIT — regenerate with `pell build`

-- Additions to pell_runtime for module hr.employees:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   hr_employees_notfound EXCEPTION;
--   PRAGMA EXCEPTION_INIT(hr_employees_notfound, -20100);
--   hr_employees_policyviolation EXCEPTION;
--   PRAGMA EXCEPTION_INIT(hr_employees_policyviolation, -20101);

CREATE OR REPLACE PACKAGE hr_employees AS
  TYPE t_employee IS RECORD (
    id NUMBER,
    name VARCHAR2(4000),
    email VARCHAR2(4000),
    level NUMBER
  );
  FUNCTION find_employee(p_id IN NUMBER) RETURN t_employee;
  PROCEDURE promote(p_id IN NUMBER);
END hr_employees;
/

CREATE OR REPLACE PACKAGE BODY hr_employees AS

  FUNCTION find_employee(p_id IN NUMBER) RETURN t_employee IS
    l_row t_employee;
  BEGIN
    BEGIN
      select id, name, email, level
      INTO l_row
      FROM employees where id = p_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_row;
  END find_employee;

  PROCEDURE promote(p_id IN NUMBER) IS
    l_e t_employee;
  BEGIN
    l_e := find_employee(p_id);
    IF (l_e.level >= 9) THEN
      pell_runtime.set_err('hr_employees_policyviolation:1', 'reason=' || 'already at max level');
      RAISE pell_runtime.hr_employees_policyviolation;
    END IF;
    update employees set level = level + 1 where id = p_id;
    RETURN;
  END promote;
END hr_employees;
/