-- Generated by pell v0 from module billing.charges
-- DO NOT EDIT — regenerate with `pell build`

-- Additions to pell_runtime for module billing.charges:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   billing_charges_overdraft EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(billing_charges_overdraft, -20100);
--   billing_charges_accountfrozen EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(billing_charges_accountfrozen, -20101);

CREATE OR REPLACE PACKAGE billing_charges AS
  TYPE t_account IS RECORD (
    id NUMBER,
    balance NUMBER
  );
  PROCEDURE transfer(p_from_id IN NUMBER, p_to_id IN NUMBER, p_amt IN NUMBER);
END billing_charges;
/

CREATE OR REPLACE PACKAGE BODY billing_charges AS

  PROCEDURE transfer(p_from_id IN NUMBER, p_to_id IN NUMBER, p_amt IN NUMBER) IS
    l_src t_account;
  BEGIN
    DECLARE
      l_committed_0 BOOLEAN := FALSE;
    BEGIN
      SAVEPOINT pell_sp_0;
      BEGIN
        select id, balance
      INTO l_src
      FROM accounts where id = p_from_id and frozen = 0;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE;
        WHEN TOO_MANY_ROWS THEN RAISE;
      END;
      IF (l_src.balance < p_amt) THEN
        pell_runtime.set_err('billing_charges_overdraft:1', JSON_OBJECT('account' VALUE p_from_id, 'requested' VALUE p_amt, 'available' VALUE l_src.balance));
        RAISE pell_runtime.billing_charges_overdraft;
      END IF;
      update accounts set balance = balance - p_amt where id = p_from_id;
      update accounts set balance = balance + p_amt where id = p_to_id;
      COMMIT;
      l_committed_0 := TRUE;
    EXCEPTION
      WHEN OTHERS THEN
        IF NOT l_committed_0 THEN ROLLBACK TO pell_sp_0; END IF;
        RAISE;
    END;
    RETURN;
  END transfer;
END billing_charges;
/