-- ======================================================================
-- Generated by pell 0.0.1 from module charges
--   Source:     compiler/examples/03_transfer.pell
--   SHA-256:    323f65c1f24b35550444e60fa9a4a61db55b60d4362f8cae0668703629fbc99a
--   pell git:   49d3402
--   Target:     Oracle 23
--   Schema:     billing
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     accounts
--   packages:
--     pell_runtime
-- ======================================================================

-- Additions to pell_runtime for module charges:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   billing_charges_overdraft EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(billing_charges_overdraft, -20100);
--   billing_charges_accountfrozen EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(billing_charges_accountfrozen, -20101);

CREATE OR REPLACE PACKAGE billing.charges AS
  TYPE t_account IS RECORD (
    id NUMBER,
    balance NUMBER
  );
  TYPE t_transfer IS RECORD (
    from_id NUMBER,
    to_id NUMBER,
    amt NUMBER
  );
  PROCEDURE transfer(p_args IN t_transfer);
END charges;
/

CREATE OR REPLACE PACKAGE BODY billing.charges AS

  PROCEDURE transfer(p_args IN t_transfer) IS
    l_from_id NUMBER;
    l_to_id NUMBER;
    l_amt NUMBER;
    l_src t_account;
  BEGIN
    l_from_id := p_args.from_id;
    l_to_id := p_args.to_id;
    l_amt := p_args.amt;
    DECLARE
      l_committed_0 BOOLEAN := FALSE;
    BEGIN
      SAVEPOINT pell_sp_0;  -- @ 03_transfer.pell:28
      BEGIN
        select id, balance
      INTO l_src
      FROM accounts where id = l_from_id and frozen = 0;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE;
        WHEN TOO_MANY_ROWS THEN RAISE;
      END;
      IF (l_src.balance < p_args.amt) THEN
        pell_runtime.set_err('billing_charges_overdraft:1', JSON_OBJECT('account' VALUE p_args.from_id, 'requested' VALUE p_args.amt, 'available' VALUE l_src.balance));
        RAISE pell_runtime.billing_charges_overdraft;
      END IF;
      update accounts set balance = balance - l_amt where id = l_from_id;
      update accounts set balance = balance + l_amt where id = l_to_id;
      COMMIT;
      l_committed_0 := TRUE;
    EXCEPTION
      WHEN OTHERS THEN
        IF NOT l_committed_0 THEN ROLLBACK TO pell_sp_0; END IF;  -- @ 03_transfer.pell:28
        RAISE;
    END;
    RETURN;
  END transfer;
END charges;
/