-- ======================================================================
-- Generated by pell 0.0.1 from module inventory.skus
--   Source:     examples/04_inventory.pell
--   SHA-256:    24ce181d9f8d07339eba3533ec8b257b886bce7844c8eb52ad93c9015d43904b
--   pell git:   7a64612 + uncommitted:dfad82a9
--   Target:     Oracle 23
--   Schema:     inventory
--   Built at:   2026-06-05 12:45:34 UTC
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     skus
--   packages:
--     pell_runtime
-- ======================================================================

-- Additions to pell_runtime for module inventory.skus:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   inventory_skus_duplicatecode EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(inventory_skus_duplicatecode, -20100);

CREATE OR REPLACE PACKAGE inventory.skus AS
  TYPE t_sku IS RECORD (
    id NUMBER,
    code VARCHAR2(4000),
    qty NUMBER
  );
  FUNCTION create_sku(p_code IN VARCHAR2, p_qty IN NUMBER) RETURN NUMBER;
  FUNCTION deplete_expired RETURN NUMBER;
END skus;
/

CREATE OR REPLACE PACKAGE BODY inventory.skus AS

  FUNCTION create_sku(p_code IN VARCHAR2, p_qty IN NUMBER) RETURN NUMBER IS
    l_new_id NUMBER;
  BEGIN
    insert into skus(code, qty) values (p_code, p_qty)
    returning id INTO l_new_id;
    RETURN l_new_id;
  END create_sku;

  FUNCTION deplete_expired RETURN NUMBER IS
    l_n PLS_INTEGER;
  BEGIN
    update skus set qty = 0
    where expires_at < sysdate;
    l_n := SQL%ROWCOUNT;
    RETURN l_n;
  END deplete_expired;
END skus;
/
