-- Generated by pell v0 from module inventory.skus
-- DO NOT EDIT — regenerate with `pell build`

-- Additions to pell_runtime for module inventory.skus:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   inventory_skus_duplicatecode EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(inventory_skus_duplicatecode, -20100);

CREATE OR REPLACE PACKAGE inventory_skus AS
  TYPE t_sku IS RECORD (
    id NUMBER,
    code VARCHAR2(4000),
    qty NUMBER
  );
  FUNCTION create_sku(p_code IN VARCHAR2, p_qty IN NUMBER) RETURN NUMBER;
  FUNCTION deplete_expired RETURN NUMBER;
END inventory_skus;
/

CREATE OR REPLACE PACKAGE BODY inventory_skus AS

  FUNCTION create_sku(p_code IN VARCHAR2, p_qty IN NUMBER) RETURN NUMBER IS
    l_new_id NUMBER;
  BEGIN
    insert into skus(code, qty) values (p_code, p_qty)
    returning id INTO l_new_id;
    RETURN l_new_id;
  END create_sku;

  FUNCTION deplete_expired RETURN NUMBER IS
    l_n PLS_INTEGER;
  BEGIN
    update skus set qty = 0
    where expires_at < sysdate;
    l_n := SQL%ROWCOUNT;
    RETURN l_n;
  END deplete_expired;
END inventory_skus;
/