-- ======================================================================
-- Generated by pell 0.0.1 from module stock
--   Source:     compiler/examples/04_inventory.pell
--   SHA-256:    eac9d7d8d949839b4ccf9e7c8f1822e5d8f3cddb10ef866a66a313ac23589a16
--   pell git:   dd8ab63
--   Target:     Oracle 23
--   Schema:     inventory
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     skus
--   packages:
--     pell_runtime
-- ======================================================================

-- Additions to pell_runtime for module stock:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   inventory_stock_duplicatecode EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(inventory_stock_duplicatecode, -20100);

CREATE OR REPLACE PACKAGE inventory.stock AS
  TYPE t_sku IS RECORD (
    id NUMBER,
    code VARCHAR2(4000),
    qty NUMBER
  );
  FUNCTION create_sku(p_code IN VARCHAR2, p_qty IN NUMBER) RETURN NUMBER;
  FUNCTION deplete_expired RETURN NUMBER;
END stock;
/

CREATE OR REPLACE PACKAGE BODY inventory.stock AS

  FUNCTION create_sku(p_code IN VARCHAR2, p_qty IN NUMBER) RETURN NUMBER IS
    l_new_id NUMBER;
  BEGIN
    insert into skus(code, qty) values (p_code, p_qty)
    returning id INTO l_new_id;
    RETURN l_new_id;
  END create_sku;

  FUNCTION deplete_expired RETURN NUMBER IS
    l_n PLS_INTEGER;
  BEGIN
    update skus set qty = 0
    where expires_at < sysdate;
    l_n := SQL%ROWCOUNT;
    RETURN l_n;
  END deplete_expired;
END stock;
/