-- Generated by pell v0 from module reports.daily
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE reports_daily AS
  TYPE t_ordersummary IS RECORD (
    order_id NUMBER,
    total NUMBER
  );
  PROCEDURE print_recent(p_cutoff IN DATE);
END reports_daily;
/

CREATE OR REPLACE PACKAGE BODY reports_daily AS

  PROCEDURE print_recent(p_cutoff IN DATE) IS
  BEGIN
    FOR row IN (
      select order_id, total
          from orders
          where created_at >= p_cutoff
          order by created_at desc
    ) LOOP
      log.info(row.order_id);
    END LOOP;
  END print_recent;
END reports_daily;
/