-- ======================================================================
-- Generated by pell 0.0.1 from module reports.daily
--   Source:     compiler/examples/05_iter.pell
--   SHA-256:    0f792642daa50f2303e082019f33cbb3decf5453bdf83c9c1bd7ef2c4ac7f4e2
--   pell git:   56a1ae1
--   Target:     Oracle 23
--   Schema:     reports
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     orders
--   packages:
--     log
-- ======================================================================

CREATE OR REPLACE PACKAGE reports.daily AS
  TYPE t_ordersummary IS RECORD (
    order_id NUMBER,
    total NUMBER
  );
  PROCEDURE print_recent(p_cutoff IN DATE);
END daily;
/

CREATE OR REPLACE PACKAGE BODY reports.daily AS

  PROCEDURE print_recent(p_cutoff IN DATE) IS
  BEGIN
    FOR row IN (
      select order_id, total
          from orders
          where created_at >= p_cutoff
          order by created_at desc
    ) LOOP
      log.info(row.order_id);
    END LOOP;
  END print_recent;
END daily;
/