-- ======================================================================
-- Generated by pell 0.0.1 from module daily
--   Source:     compiler/examples/05_iter.pell
--   SHA-256:    a01bd4c9c4213f93a58c023558a16e4447f64b80f0579fa1e88a8c36dedbf899
--   pell git:   9f44963
--   Target:     Oracle 23
--   Schema:     reports
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     orders
--   packages:
--     logger
-- ======================================================================

CREATE OR REPLACE PACKAGE reports.daily AS
  TYPE t_ordersummary IS RECORD (
    order_id NUMBER,
    total NUMBER
  );
  PROCEDURE print_recent(p_cutoff IN DATE);
END daily;
/

CREATE OR REPLACE PACKAGE BODY reports.daily AS

  PROCEDURE print_recent(p_cutoff IN DATE) IS
  BEGIN
    FOR row IN (
      select order_id, total
          from orders
          where created_at >= p_cutoff
          order by created_at desc
    ) LOOP
      logger.info(row.order_id);
    END LOOP;
  END print_recent;
END daily;
/