-- Generated by pell v0 from module lookups.country
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE lookups_country AS
  FUNCTION country_name(p_code IN VARCHAR2) RETURN VARCHAR2 DETERMINISTIC RESULT_CACHE;
  PROCEDURE audit_log(p_event IN VARCHAR2);
END lookups_country;
/

CREATE OR REPLACE PACKAGE BODY lookups_country AS

  FUNCTION country_name(p_code IN VARCHAR2) RETURN VARCHAR2 DETERMINISTIC RESULT_CACHE IS
    l_row VARCHAR2(4000);
    PRAGMA UDF;
  BEGIN
    BEGIN
      select name
      INTO l_row
      FROM countries where code = p_code;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_row;
  END country_name;

  PROCEDURE audit_log(p_event IN VARCHAR2) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    insert into audit(event, ts) values (p_event, sysdate);
  END audit_log;
END lookups_country;
/