-- ======================================================================
-- Generated by pell 0.0.1 from module lookups.country
--   Source:     compiler/examples/06_annotated.pell
--   SHA-256:    7a0515aa5dcf27642d954f041f55aa926853f1b7d88f230f9b74281cb28c1af7
--   pell git:   2b77ce0
--   Target:     Oracle 23
--   Schema:     lookups
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     audit_tbl
--     countries
-- ======================================================================

CREATE OR REPLACE PACKAGE lookups.country AS
  FUNCTION country_name(p_code IN VARCHAR2) RETURN VARCHAR2 DETERMINISTIC RESULT_CACHE;
  PROCEDURE audit_log(p_event IN VARCHAR2);
END country;
/

CREATE OR REPLACE PACKAGE BODY lookups.country AS

  FUNCTION country_name(p_code IN VARCHAR2) RETURN VARCHAR2 DETERMINISTIC RESULT_CACHE IS
    l_row VARCHAR2(4000);
    PRAGMA UDF;
  BEGIN
    BEGIN
      select name
      INTO l_row
      FROM countries where code = p_code;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_row;
  END country_name;

  PROCEDURE audit_log(p_event IN VARCHAR2) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    BEGIN
    insert into audit_tbl(event, ts) values (p_event, sysdate);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
    END;
  END audit_log;
END country;
/