-- ======================================================================
-- Generated by pell 0.0.1 from module orders.fulfillment
--   Source:     compiler/examples/07_full.pell
--   SHA-256:    278b1842a11757e9e5fc2381e4587e83c7914bba61e03c746fc699ad768dc891
--   pell git:   366977c
--   Target:     Oracle 23
--   Schema:     orders
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     audit_log
--     order_lines
--     orders
--     skus
--   packages:
--     logger
--     pell_runtime
-- ======================================================================

-- Additions to pell_runtime for module orders.fulfillment:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   orders_fulfillment_ordernotfound EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(orders_fulfillment_ordernotfound, -20100);
--   orders_fulfillment_invalidstatus EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(orders_fulfillment_invalidstatus, -20101);
--   orders_fulfillment_insufficientinventory EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(orders_fulfillment_insufficientinventory, -20102);

CREATE OR REPLACE PACKAGE orders.fulfillment AS
  TYPE t_order IS RECORD (
    id NUMBER,
    customer_id NUMBER,
    status VARCHAR2(4000),
    total NUMBER
  );
  TYPE t_orderline IS RECORD (
    id NUMBER,
    order_id NUMBER,
    sku_id NUMBER,
    qty NUMBER
  );
  FUNCTION fetch_order(p_id IN NUMBER) RETURN t_order;
  FUNCTION count_lines(p_order_id IN NUMBER) RETURN NUMBER DETERMINISTIC RESULT_CACHE;
  FUNCTION add_line(p_order_id IN NUMBER, p_sku_id IN NUMBER, p_qty IN NUMBER) RETURN NUMBER;
  PROCEDURE audit(p_event IN VARCHAR2, p_order_id IN NUMBER);
  FUNCTION cancel_stale RETURN NUMBER;
  PROCEDURE print_recent(p_after IN DATE);
END fulfillment;
/

CREATE OR REPLACE PACKAGE BODY orders.fulfillment AS

  FUNCTION fetch_order(p_id IN NUMBER) RETURN t_order IS
    l_row t_order;
  BEGIN
    BEGIN
      select id, customer_id, status, total
      INTO l_row
      FROM orders where id = p_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        pell_runtime.set_err('orders_fulfillment_ordernotfound:1', '{}');
        RAISE pell_runtime.orders_fulfillment_ordernotfound;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_row;
  END fetch_order;

  FUNCTION count_lines(p_order_id IN NUMBER) RETURN NUMBER DETERMINISTIC RESULT_CACHE IS
    l_n NUMBER;
  BEGIN
    BEGIN
      select count(*)
      INTO l_n
      FROM order_lines where order_id = p_order_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_n;
  END count_lines;

  FUNCTION add_line(p_order_id IN NUMBER, p_sku_id IN NUMBER, p_qty IN NUMBER) RETURN NUMBER IS
    l_ord t_order;
    l_available NUMBER;
    l_new_line_id NUMBER;
  BEGIN
    DECLARE
      l_committed_0 BOOLEAN := FALSE;
    BEGIN
      SAVEPOINT pell_sp_0;  -- @ 07_full.pell:49
      BEGIN
        select id, customer_id, status, total
      INTO l_ord
      FROM orders where id = p_order_id FOR UPDATE;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          pell_runtime.set_err('orders_fulfillment_ordernotfound:1', '{}');
          RAISE pell_runtime.orders_fulfillment_ordernotfound;
        WHEN TOO_MANY_ROWS THEN RAISE;
      END;
      BEGIN
        select qty
      INTO l_available
      FROM skus where id = p_sku_id FOR UPDATE;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          pell_runtime.set_err('orders_fulfillment_ordernotfound:1', '{}');
          RAISE pell_runtime.orders_fulfillment_ordernotfound;
        WHEN TOO_MANY_ROWS THEN RAISE;
      END;
      IF (l_available < p_qty) THEN
        pell_runtime.set_err('orders_fulfillment_insufficientinventory:1', JSON_OBJECT('sku_id' VALUE p_sku_id, 'requested' VALUE p_qty, 'available' VALUE l_available));
        RAISE pell_runtime.orders_fulfillment_insufficientinventory;
      END IF;
      update skus set qty = qty - p_qty where id = p_sku_id;
      insert into order_lines(order_id, sku_id, qty)
      values (p_order_id, p_sku_id, p_qty)
      returning id INTO l_new_line_id;
      logger.info(('added line ' || TO_CHAR(l_new_line_id) || ' to order ' || TO_CHAR(p_order_id)));
      COMMIT;
      l_committed_0 := TRUE;
      RETURN l_new_line_id;
    EXCEPTION
      WHEN OTHERS THEN
        IF NOT l_committed_0 THEN ROLLBACK TO pell_sp_0;  -- @ 07_full.pell:49 END IF;
        RAISE;
    END;
    pell_runtime.set_err('orders_fulfillment_ordernotfound:1', JSON_OBJECT('id' VALUE p_order_id));
    RAISE pell_runtime.orders_fulfillment_ordernotfound;
  END add_line;

  PROCEDURE audit(p_event IN VARCHAR2, p_order_id IN NUMBER) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    BEGIN
    insert into audit_log(event, order_id, occurred_at)
        values (p_event, p_order_id, sysdate);
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
    END;
  END audit;

  FUNCTION cancel_stale RETURN NUMBER IS
    l_n PLS_INTEGER;
  BEGIN
    update orders set status = 'cancelled'
    where status = 'pending'
    and created_at < sysdate - 7;
    l_n := SQL%ROWCOUNT;
    RETURN l_n;
  END cancel_stale;

  PROCEDURE print_recent(p_after IN DATE) IS
  BEGIN
    FOR row IN (
      select id, status, total
          from orders
          where created_at >= p_after
          order by created_at desc
    ) LOOP
      logger.info(('order ' || row.id || ': ' || row.status));
    END LOOP;
  END print_recent;
END fulfillment;
/