-- ======================================================================
-- Generated by pell 0.0.1 from module audit.charges
--   Source:     compiler/examples/08_finally.pell
--   SHA-256:    43184b1bbca67c45ee1fa032dd242089baf247fe39153b055b28914d31f67adf
--   pell git:   85061d6
--   Target:     Oracle 23
--   Schema:     audit
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     ledger
-- ======================================================================

CREATE OR REPLACE PACKAGE audit.charges AS
  FUNCTION charge_account(p_id IN NUMBER, p_amount IN NUMBER) RETURN NUMBER;
END charges;
/

CREATE OR REPLACE PACKAGE BODY audit.charges AS

  FUNCTION charge_account(p_id IN NUMBER, p_amount IN NUMBER) RETURN NUMBER IS
    l_new_id NUMBER;
    PROCEDURE pell_finally_body IS
    BEGIN
      dbms_output.put_line('charge_account exit');
    END pell_finally_body;
  BEGIN
    BEGIN
      insert into ledger(account_id, amount, ts)
    values (p_id, p_amount, sysdate)
    returning entry_id INTO l_new_id;
      pell_finally_body;
      RETURN l_new_id;
    EXCEPTION
      WHEN OTHERS THEN
        BEGIN pell_finally_body; EXCEPTION WHEN OTHERS THEN NULL; END;
        RAISE;
    END;
    pell_finally_body;
  END charge_account;
END charges;
/