-- Generated by pell v0 from module audit.charges
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE audit_charges AS
  FUNCTION charge_account(p_id IN NUMBER, p_amount IN NUMBER) RETURN NUMBER;
END audit_charges;
/

CREATE OR REPLACE PACKAGE BODY audit_charges AS

  FUNCTION charge_account(p_id IN NUMBER, p_amount IN NUMBER) RETURN NUMBER IS
    l_new_id NUMBER;
    PROCEDURE pell_finally_body IS
    BEGIN
      dbms_output.put_line('charge_account exit');
    END pell_finally_body;
  BEGIN
    BEGIN
      insert into ledger(account_id, amount, ts)
    values (p_id, p_amount, sysdate)
    returning entry_id INTO l_new_id;
      pell_finally_body;
      RETURN l_new_id;
    EXCEPTION
      WHEN OTHERS THEN
        BEGIN pell_finally_body; EXCEPTION WHEN OTHERS THEN NULL; END;
        RAISE;
    END;
    pell_finally_body;
  END charge_account;
END audit_charges;
/