-- ======================================================================
-- Generated by pell 0.0.1 from module charge_log
--   Source:     compiler/examples/08_finally.pell
--   SHA-256:    1d9b404125abb750a60693f7d8d37a13e25540a19eaa4d220165ac5c38b205c1
--   pell git:   dd6ae26
--   Target:     Oracle 23
--   Schema:     auditing
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     ledger
--   packages:
--     dbms_output
-- ======================================================================

CREATE OR REPLACE PACKAGE auditing.charge_log AS
  FUNCTION charge_account(p_id IN NUMBER, p_amount IN NUMBER) RETURN NUMBER;
END charge_log;
/

CREATE OR REPLACE PACKAGE BODY auditing.charge_log AS

  FUNCTION charge_account(p_id IN NUMBER, p_amount IN NUMBER) RETURN NUMBER IS
    l_new_id NUMBER;
    PROCEDURE pell_finally_body IS
    BEGIN
      dbms_output.put_line('charge_account exit');
    END pell_finally_body;
  BEGIN
    BEGIN
      insert into ledger(account_id, amount, ts)
    values (p_id, p_amount, sysdate)
    returning entry_id INTO l_new_id;
      pell_finally_body;
      RETURN l_new_id;
    EXCEPTION
      WHEN OTHERS THEN
        BEGIN pell_finally_body; EXCEPTION WHEN OTHERS THEN NULL; END;
        RAISE;
    END;
    pell_finally_body;
  END charge_account;
END charge_log;
/