-- Generated by pell v0 from module bulk.demo
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE bulk_demo AS
  PROCEDURE insert_many;
END bulk_demo;
/

CREATE OR REPLACE PACKAGE BODY bulk_demo AS
  TYPE t_number_list IS TABLE OF NUMBER INDEX BY PLS_INTEGER;

  PROCEDURE insert_many IS
    l_nums t_number_list;
    l_n_iter NUMBER;
  BEGIN
    l_nums(1) := 1;
    l_nums(2) := 3;
    l_nums(3) := 5;
    l_nums(4) := 7;
    l_nums(5) := 11;
    FOR i_n IN l_nums.FIRST .. l_nums.LAST LOOP
      l_n_iter := l_nums(i_n);
      insert into num_table(n) values (l_n_iter);
      log.info(('inserted ' || l_n_iter));
    END LOOP;
  END insert_many;
END bulk_demo;
/