-- ======================================================================
-- Generated by pell 0.0.1 from module bulk.demo
--   Source:     examples/09_bulk.pell
--   SHA-256:    ded679bb7048be20b9ad54743eb099795c2b1b5dca3c91e8d692c33bc2b9e4a7
--   pell git:   f73a136
--   Target:     Oracle 23
--   Schema:     bulk
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     num_table
--   packages:
--     log
-- ======================================================================

CREATE OR REPLACE PACKAGE bulk.demo AS
  PROCEDURE insert_many;
  FUNCTION read_all RETURN NUMBER;
END demo;
/

CREATE OR REPLACE PACKAGE BODY bulk.demo AS
  TYPE t_number_list IS TABLE OF NUMBER INDEX BY PLS_INTEGER;

  PROCEDURE insert_many IS
    l_nums t_number_list;
  BEGIN
    l_nums(1) := 1;
    l_nums(2) := 3;
    l_nums(3) := 5;
    l_nums(4) := 7;
    l_nums(5) := 11;
    FORALL i_n IN l_nums.FIRST .. l_nums.LAST
      insert into num_table(n) values (l_nums(i_n));
    FOR i IN l_nums.FIRST .. l_nums.LAST LOOP
      log.info(('Inserted ' || SQL%BULK_ROWCOUNT(i) || ' row(s) on iteration ' || i));
    END LOOP;
  END insert_many;

  FUNCTION read_all RETURN NUMBER IS
    l_rows t_number_list;
    l_total NUMBER;
  BEGIN
    select n
      BULK COLLECT INTO l_rows
      FROM num_table order by n;
    l_total := 0;
    FOR i IN l_rows.FIRST .. l_rows.LAST LOOP
      l_total := (l_total + l_rows(i));
    END LOOP;
    RETURN l_total;
  END read_all;
END demo;
/