-- ======================================================================
-- Generated by pell 0.0.1 from module demo
--   Source:     compiler/examples/09_bulk.pell
--   SHA-256:    e34ae3fbde0cccc5c0fead8d87513a1c42c441798627b0c3683d3b1b6f5c80f6
--   pell git:   8e29044
--   Target:     Oracle 23
--   Schema:     bulk
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     num_table
--   packages:
--     logger
-- ======================================================================

CREATE OR REPLACE PACKAGE bulk.demo AS
  PROCEDURE insert_many;
  FUNCTION read_all RETURN NUMBER;
END demo;
/

CREATE OR REPLACE PACKAGE BODY bulk.demo AS
  TYPE t_number_list IS TABLE OF NUMBER INDEX BY PLS_INTEGER;

  PROCEDURE insert_many IS
    l_nums t_number_list;
  BEGIN
    l_nums(1) := 1;
    l_nums(2) := 3;
    l_nums(3) := 5;
    l_nums(4) := 7;
    l_nums(5) := 11;
    FORALL i_n IN l_nums.FIRST .. l_nums.LAST
      insert into num_table(n) values (l_nums(i_n));
    FOR i IN l_nums.FIRST .. l_nums.LAST LOOP
      logger.info(('Inserted ' || TO_CHAR(SQL%BULK_ROWCOUNT(i)) || ' row(s) on iteration ' || i));
    END LOOP;
  END insert_many;

  FUNCTION read_all RETURN NUMBER IS
    l_rows t_number_list;
    l_total NUMBER;
  BEGIN
    select n
      BULK COLLECT INTO l_rows
      FROM num_table order by n;
    l_total := 0;
    FOR i IN l_rows.FIRST .. l_rows.LAST LOOP
      l_total := (l_total + l_rows(i));
    END LOOP;
    RETURN l_total;
  END read_all;
END demo;
/