-- Generated by pell v0 from module market.feeds
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE TYPE market_feeds_ticker_obj AS OBJECT (
  sym VARCHAR2(4000),
  price NUMBER
);
/
CREATE OR REPLACE TYPE market_feeds_ticker_nt AS TABLE OF market_feeds_ticker_obj;
/

CREATE OR REPLACE PACKAGE market_feeds AS
  TYPE t_stock IS RECORD (
    sym VARCHAR2(4000),
    price NUMBER
  );
  TYPE t_ticker IS RECORD (
    sym VARCHAR2(4000),
    price NUMBER
  );
  FUNCTION stockpivot(p_rows IN SYS_REFCURSOR) RETURN market_feeds_ticker_nt PIPELINED;
  FUNCTION shifted_prices RETURN NUMBER;
END market_feeds;
/

CREATE OR REPLACE PACKAGE BODY market_feeds AS
  TYPE t_Ticker_list IS TABLE OF t_ticker INDEX BY PLS_INTEGER;

  FUNCTION stockpivot(p_rows IN SYS_REFCURSOR) RETURN market_feeds_ticker_nt PIPELINED IS
    TYPE t_stock_buf IS TABLE OF t_stock INDEX BY PLS_INTEGER;
    l_s_buf t_stock_buf;
  BEGIN
    LOOP
      FETCH p_rows BULK COLLECT INTO l_s_buf LIMIT 100;
      EXIT WHEN l_s_buf.COUNT = 0;
      FOR i_s IN 1 .. l_s_buf.COUNT LOOP
        PIPE ROW(market_feeds_ticker_obj(l_s_buf(i_s).sym, (l_s_buf(i_s).price * 1.10)));
      END LOOP;
    END LOOP;
    CLOSE p_rows;
    RETURN;
  END stockpivot;

  FUNCTION shifted_prices RETURN NUMBER IS
    l_tickers t_Ticker_list;
  BEGIN
    select t.sym, t.price
      BULK COLLECT INTO l_tickers
      FROM table(stockpivot(cursor(select sym, price from stocktable))) t;
    RETURN l_tickers.COUNT;
  END shifted_prices;
END market_feeds;
/