-- ======================================================================
-- Generated by pell 0.0.1 from module market.feeds
--   Source:     compiler/examples/10_pipelined.pell
--   SHA-256:    ccafce4a94a9014cfac3d81e802abc3df5dc6cda3bf84615e0667f062c38274b
--   pell git:   3088760
--   Target:     Oracle 23
--   Schema:     market
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     stocktable
-- ======================================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE market.feeds_ticker_obj FORCE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE OR REPLACE TYPE market.feeds_ticker_obj AS OBJECT (
  sym VARCHAR2(4000),
  price NUMBER
);
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE market.feeds_ticker_nt FORCE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE OR REPLACE TYPE market.feeds_ticker_nt AS TABLE OF feeds_ticker_obj;
/

CREATE OR REPLACE PACKAGE market.feeds AS
  TYPE t_stock IS RECORD (
    sym VARCHAR2(4000),
    price NUMBER
  );
  TYPE t_ticker IS RECORD (
    sym VARCHAR2(4000),
    price NUMBER
  );
  FUNCTION stockpivot(p_rows IN SYS_REFCURSOR) RETURN feeds_ticker_nt PIPELINED;
  FUNCTION shifted_prices RETURN NUMBER;
END feeds;
/

CREATE OR REPLACE PACKAGE BODY market.feeds AS
  TYPE t_Ticker_list IS TABLE OF t_ticker INDEX BY PLS_INTEGER;

  FUNCTION stockpivot(p_rows IN SYS_REFCURSOR) RETURN feeds_ticker_nt PIPELINED IS
    TYPE t_stock_buf IS TABLE OF t_stock INDEX BY PLS_INTEGER;
    l_s_buf t_stock_buf;
  BEGIN
    LOOP
      FETCH p_rows BULK COLLECT INTO l_s_buf LIMIT 100;
      EXIT WHEN l_s_buf.COUNT = 0;
      FOR i_s IN 1 .. l_s_buf.COUNT LOOP
        PIPE ROW(feeds_ticker_obj(l_s_buf(i_s).sym, (l_s_buf(i_s).price * 1.10)));
      END LOOP;
    END LOOP;
    CLOSE p_rows;
    RETURN;
  END stockpivot;

  FUNCTION shifted_prices RETURN NUMBER IS
    l_tickers t_Ticker_list;
  BEGIN
    select t.sym, t.price
      BULK COLLECT INTO l_tickers
      FROM table(stockpivot(cursor(select sym, price from stocktable))) t;
    RETURN l_tickers.COUNT;
  END shifted_prices;
END feeds;
/