-- ======================================================================
-- Generated by pell 0.0.1 from module shapes_demo
--   Source:     compiler/examples/11_types_aggregate.pell
--   SHA-256:    790043933f72c999a3251e77ce44aca9159e792614533bae2e1e73b837d34dc9
--   pell git:   4f64e03
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
-- ======================================================================

CREATE OR REPLACE TYPE t_number_nt AS TABLE OF NUMBER;
/
CREATE OR REPLACE TYPE t_money AS OBJECT (
  amount NUMBER,
  currency VARCHAR2(4000),
  MEMBER FUNCTION plus(p_other IN t_money) RETURN t_money,
  MAP MEMBER FUNCTION rank RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY t_money AS
  MEMBER FUNCTION plus(p_other IN t_money) RETURN t_money IS
  BEGIN
    RETURN t_money((SELF.amount + p_other.amount), SELF.currency);
  END;

  MAP MEMBER FUNCTION rank RETURN NUMBER IS
  BEGIN
    RETURN SELF.amount;
  END;
END;
/
CREATE OR REPLACE TYPE t_shape AS OBJECT (
  sys_tag_ NUMBER,
  NOT INSTANTIABLE MEMBER FUNCTION area RETURN NUMBER
) NOT INSTANTIABLE NOT FINAL;
/
CREATE OR REPLACE TYPE t_circle UNDER t_shape (
  radius NUMBER,
  OVERRIDING MEMBER FUNCTION area RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY t_circle AS
  OVERRIDING MEMBER FUNCTION area RETURN NUMBER IS
  BEGIN
    RETURN ((3.14159 * SELF.radius) * SELF.radius);
  END;
END;
/
CREATE OR REPLACE TYPE t_rectangle UNDER t_shape (
  width NUMBER,
  height NUMBER,
  OVERRIDING MEMBER FUNCTION area RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY t_rectangle AS
  OVERRIDING MEMBER FUNCTION area RETURN NUMBER IS
  BEGIN
    RETURN (SELF.width * SELF.height);
  END;
END;
/
CREATE OR REPLACE TYPE t_triangle UNDER t_shape (
  base NUMBER,
  height NUMBER,
  OVERRIDING MEMBER FUNCTION area RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY t_triangle AS
  OVERRIDING MEMBER FUNCTION area RETURN NUMBER IS
  BEGIN
    RETURN ((SELF.base * SELF.height) / 2);
  END;
END;
/
CREATE OR REPLACE TYPE total_amount_agg_t AS OBJECT (
  acc NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT total_amount_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT total_amount_agg_t, p_v IN NUMBER) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT total_amount_agg_t, ctx2 IN total_amount_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT total_amount_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY total_amount_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT total_amount_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := total_amount_agg_t(0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT total_amount_agg_t, p_v IN NUMBER) RETURN NUMBER IS
  BEGIN
    SELF.acc := (SELF.acc + p_v);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT total_amount_agg_t, ctx2 IN total_amount_agg_t) RETURN NUMBER IS
    p_o total_amount_agg_t := ctx2;
  BEGIN
    SELF.acc := (SELF.acc + p_o.acc);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT total_amount_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    returnValue := SELF.acc;
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION total_amount(p_x IN NUMBER) RETURN NUMBER PARALLEL_ENABLE AGGREGATE USING total_amount_agg_t;
/
CREATE OR REPLACE TYPE sample_count_agg_t AS OBJECT (
  vals t_number_nt,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT sample_count_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT sample_count_agg_t, p_v IN NUMBER) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT sample_count_agg_t, ctx2 IN sample_count_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT sample_count_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY sample_count_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT sample_count_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := sample_count_agg_t(t_number_nt());
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT sample_count_agg_t, p_v IN NUMBER) RETURN NUMBER IS
  BEGIN
    SELF.vals.EXTEND;
    SELF.vals(SELF.vals.LAST) := p_v;
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT sample_count_agg_t, ctx2 IN sample_count_agg_t) RETURN NUMBER IS
  BEGIN
    RAISE_APPLICATION_ERROR(-20100,
      'pell aggregate sample_count has no merge block; cannot run in parallel');
    RETURN ODCIConst.Error;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT sample_count_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    returnValue := SELF.vals.COUNT;
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION sample_count(p_x IN NUMBER) RETURN NUMBER AGGREGATE USING sample_count_agg_t;
/

CREATE OR REPLACE PACKAGE shapes_demo AS
  FUNCTION describe(p_s IN t_shape) RETURN VARCHAR2;
END shapes_demo;
/

CREATE OR REPLACE PACKAGE BODY shapes_demo AS

  FUNCTION describe(p_s IN t_shape) RETURN VARCHAR2 IS
    l_label VARCHAR2(4000);
  BEGIN
    l_label := '';
    IF (p_s) IS OF (t_circle) THEN
      l_label := 'round';
    ELSIF (p_s) IS OF (t_rectangle) THEN
      l_label := 'boxy';
    ELSIF (p_s) IS OF (t_triangle) THEN
      l_label := 'pointy';
    END IF;
    RETURN l_label;
  END describe;
END shapes_demo;
/