-- ======================================================================
-- Generated by pell 0.0.1 from module agg_library
--   Source:     compiler/examples/12_agg_library.pell
--   SHA-256:    411d79f837d6967d6057a7a74e52b74bb1abc631838fba9b03eaa87b5c56b47b
--   pell git:   f140966
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     dbms_utility
-- ======================================================================

CREATE OR REPLACE TYPE xor_hash_agg_t AS OBJECT (
  acc NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT xor_hash_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT xor_hash_agg_t, p_v IN VARCHAR2) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT xor_hash_agg_t, ctx2 IN xor_hash_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT xor_hash_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY xor_hash_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT xor_hash_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := xor_hash_agg_t(0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT xor_hash_agg_t, p_v IN VARCHAR2) RETURN NUMBER IS
    l_h NUMBER;
  BEGIN
    l_h := dbms_utility.get_hash_value(p_v, 0, 1073741824);
    SELF.acc := ((SELF.acc + l_h) - (2 * bitand(SELF.acc, l_h)));
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT xor_hash_agg_t, ctx2 IN xor_hash_agg_t) RETURN NUMBER IS
    p_o xor_hash_agg_t := ctx2;
  BEGIN
    SELF.acc := ((SELF.acc + p_o.acc) - (2 * bitand(SELF.acc, p_o.acc)));
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT xor_hash_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    returnValue := SELF.acc;
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION xor_hash(p_s IN VARCHAR2) RETURN NUMBER PARALLEL_ENABLE AGGREGATE USING xor_hash_agg_t;
/
CREATE OR REPLACE TYPE bitwise_or_agg_t AS OBJECT (
  bits NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT bitwise_or_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT bitwise_or_agg_t, p_v IN NUMBER) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT bitwise_or_agg_t, ctx2 IN bitwise_or_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT bitwise_or_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY bitwise_or_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT bitwise_or_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := bitwise_or_agg_t(0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT bitwise_or_agg_t, p_v IN NUMBER) RETURN NUMBER IS
  BEGIN
    SELF.bits := ((SELF.bits + p_v) - bitand(SELF.bits, p_v));
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT bitwise_or_agg_t, ctx2 IN bitwise_or_agg_t) RETURN NUMBER IS
    p_o bitwise_or_agg_t := ctx2;
  BEGIN
    SELF.bits := ((SELF.bits + p_o.bits) - bitand(SELF.bits, p_o.bits));
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT bitwise_or_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    returnValue := SELF.bits;
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION bitwise_or(p_n IN NUMBER) RETURN NUMBER PARALLEL_ENABLE AGGREGATE USING bitwise_or_agg_t;
/
CREATE OR REPLACE TYPE unique_or_null_agg_t AS OBJECT (
  val VARCHAR2(4000),
  seen NUMBER,
  conflict NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT unique_or_null_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT unique_or_null_agg_t, p_v IN VARCHAR2) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT unique_or_null_agg_t, ctx2 IN unique_or_null_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT unique_or_null_agg_t, returnValue OUT VARCHAR2, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY unique_or_null_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT unique_or_null_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := unique_or_null_agg_t('', 0, 0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT unique_or_null_agg_t, p_v IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    IF (SELF.seen = 0) THEN
      SELF.val := p_v;
      SELF.seen := 1;
    ELSE
      IF (SELF.val <> p_v) THEN
        SELF.conflict := 1;
      END IF;
    END IF;
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT unique_or_null_agg_t, ctx2 IN unique_or_null_agg_t) RETURN NUMBER IS
  BEGIN
    RAISE_APPLICATION_ERROR(-20100,
      'pell aggregate unique_or_null has no merge block; cannot run in parallel');
    RETURN ODCIConst.Error;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT unique_or_null_agg_t, returnValue OUT VARCHAR2, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF (SELF.conflict = 1) THEN
      returnValue := '';
      RETURN ODCIConst.Success;
    END IF;
    returnValue := SELF.val;
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION unique_or_null(p_s IN VARCHAR2) RETURN VARCHAR2 AGGREGATE USING unique_or_null_agg_t;
/
CREATE OR REPLACE TYPE numeric_range_agg_t AS OBJECT (
  lo NUMBER,
  hi NUMBER,
  seen NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT numeric_range_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT numeric_range_agg_t, p_v IN NUMBER) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT numeric_range_agg_t, ctx2 IN numeric_range_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT numeric_range_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY numeric_range_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT numeric_range_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := numeric_range_agg_t(0, 0, 0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT numeric_range_agg_t, p_v IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF (SELF.seen = 0) THEN
      SELF.lo := p_v;
      SELF.hi := p_v;
      SELF.seen := 1;
    ELSE
      IF (p_v < SELF.lo) THEN
        SELF.lo := p_v;
      END IF;
      IF (p_v > SELF.hi) THEN
        SELF.hi := p_v;
      END IF;
    END IF;
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT numeric_range_agg_t, ctx2 IN numeric_range_agg_t) RETURN NUMBER IS
    p_o numeric_range_agg_t := ctx2;
  BEGIN
    IF (SELF.seen = 0) THEN
      SELF.lo := p_o.lo;
      SELF.hi := p_o.hi;
      SELF.seen := p_o.seen;
    ELSE
      IF (p_o.seen = 1) THEN
        IF (p_o.lo < SELF.lo) THEN
          SELF.lo := p_o.lo;
        END IF;
        IF (p_o.hi > SELF.hi) THEN
          SELF.hi := p_o.hi;
        END IF;
      END IF;
    END IF;
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT numeric_range_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    returnValue := (SELF.hi - SELF.lo);
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION numeric_range(p_n IN NUMBER) RETURN NUMBER PARALLEL_ENABLE AGGREGATE USING numeric_range_agg_t;
/
CREATE OR REPLACE TYPE harmonic_mean_agg_t AS OBJECT (
  recip_sum NUMBER,
  count NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT harmonic_mean_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT harmonic_mean_agg_t, p_v IN NUMBER) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT harmonic_mean_agg_t, ctx2 IN harmonic_mean_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT harmonic_mean_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY harmonic_mean_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT harmonic_mean_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := harmonic_mean_agg_t(0, 0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT harmonic_mean_agg_t, p_v IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF (p_v <> 0) THEN
      SELF.recip_sum := (SELF.recip_sum + (1 / p_v));
      SELF.count := (SELF.count + 1);
    END IF;
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT harmonic_mean_agg_t, ctx2 IN harmonic_mean_agg_t) RETURN NUMBER IS
    p_o harmonic_mean_agg_t := ctx2;
  BEGIN
    SELF.recip_sum := (SELF.recip_sum + p_o.recip_sum);
    SELF.count := (SELF.count + p_o.count);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT harmonic_mean_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF (SELF.count = 0) THEN
      returnValue := 0;
      RETURN ODCIConst.Success;
    END IF;
    returnValue := (SELF.count / SELF.recip_sum);
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION harmonic_mean(p_n IN NUMBER) RETURN NUMBER PARALLEL_ENABLE AGGREGATE USING harmonic_mean_agg_t;
/
CREATE OR REPLACE TYPE argmax_args_t AS OBJECT (
  v VARCHAR2(4000),
  k NUMBER
);
/
CREATE OR REPLACE TYPE argmax_agg_t AS OBJECT (
  best_val VARCHAR2(4000),
  best_key NUMBER,
  seen NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT argmax_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT argmax_agg_t, p_args IN argmax_args_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT argmax_agg_t, ctx2 IN argmax_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT argmax_agg_t, returnValue OUT VARCHAR2, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY argmax_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT argmax_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := argmax_agg_t('', 0, 0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT argmax_agg_t, p_args IN argmax_args_t) RETURN NUMBER IS
    p_v VARCHAR2(4000);
    p_k NUMBER;
  BEGIN
    p_v := p_args.v;
    p_k := p_args.k;
    IF (SELF.seen = 0) THEN
      SELF.best_val := p_v;
      SELF.best_key := p_k;
      SELF.seen := 1;
    ELSE
      IF (p_k > SELF.best_key) THEN
        SELF.best_val := p_v;
        SELF.best_key := p_k;
      END IF;
    END IF;
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT argmax_agg_t, ctx2 IN argmax_agg_t) RETURN NUMBER IS
  BEGIN
    RAISE_APPLICATION_ERROR(-20100,
      'pell aggregate argmax has no merge block; cannot run in parallel');
    RETURN ODCIConst.Error;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT argmax_agg_t, returnValue OUT VARCHAR2, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    returnValue := SELF.best_val;
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION argmax(p_args IN argmax_args_t) RETURN VARCHAR2 AGGREGATE USING argmax_agg_t;
/
CREATE OR REPLACE TYPE weighted_mean_args_t AS OBJECT (
  v NUMBER,
  w NUMBER
);
/
CREATE OR REPLACE TYPE weighted_mean_agg_t AS OBJECT (
  weighted_sum NUMBER,
  weight_sum NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT weighted_mean_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT weighted_mean_agg_t, p_args IN weighted_mean_args_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT weighted_mean_agg_t, ctx2 IN weighted_mean_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT weighted_mean_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY weighted_mean_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT weighted_mean_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := weighted_mean_agg_t(0, 0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT weighted_mean_agg_t, p_args IN weighted_mean_args_t) RETURN NUMBER IS
    p_v NUMBER;
    p_w NUMBER;
  BEGIN
    p_v := p_args.v;
    p_w := p_args.w;
    SELF.weighted_sum := (SELF.weighted_sum + (p_v * p_w));
    SELF.weight_sum := (SELF.weight_sum + p_w);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT weighted_mean_agg_t, ctx2 IN weighted_mean_agg_t) RETURN NUMBER IS
    p_o weighted_mean_agg_t := ctx2;
  BEGIN
    SELF.weighted_sum := (SELF.weighted_sum + p_o.weighted_sum);
    SELF.weight_sum := (SELF.weight_sum + p_o.weight_sum);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT weighted_mean_agg_t, returnValue OUT NUMBER, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF (SELF.weight_sum = 0) THEN
      returnValue := 0;
      RETURN ODCIConst.Success;
    END IF;
    returnValue := (SELF.weighted_sum / SELF.weight_sum);
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION weighted_mean(p_args IN weighted_mean_args_t) RETURN NUMBER PARALLEL_ENABLE AGGREGATE USING weighted_mean_agg_t;
/
CREATE OR REPLACE TYPE majority_vote_agg_t AS OBJECT (
  candidate VARCHAR2(4000),
  votes NUMBER,
  candidate_count NUMBER,
  total NUMBER,
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT majority_vote_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT majority_vote_agg_t, p_v IN VARCHAR2) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT majority_vote_agg_t, ctx2 IN majority_vote_agg_t) RETURN NUMBER,
  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT majority_vote_agg_t, returnValue OUT VARCHAR2, flags IN NUMBER) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY majority_vote_agg_t AS
  STATIC FUNCTION ODCIAggregateInitialize(sctx IN OUT majority_vote_agg_t) RETURN NUMBER IS
  BEGIN
    sctx := majority_vote_agg_t('', 0, 0, 0);
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateIterate(self IN OUT majority_vote_agg_t, p_v IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    SELF.total := (SELF.total + 1);
    IF (SELF.votes = 0) THEN
      SELF.candidate := p_v;
      SELF.votes := 1;
      SELF.candidate_count := 1;
    ELSE
      IF (SELF.candidate = p_v) THEN
        SELF.votes := (SELF.votes + 1);
        SELF.candidate_count := (SELF.candidate_count + 1);
      ELSE
        SELF.votes := (SELF.votes - 1);
      END IF;
    END IF;
    RETURN ODCIConst.Success;
  END;

  MEMBER FUNCTION ODCIAggregateMerge(self IN OUT majority_vote_agg_t, ctx2 IN majority_vote_agg_t) RETURN NUMBER IS
  BEGIN
    RAISE_APPLICATION_ERROR(-20100,
      'pell aggregate majority_vote has no merge block; cannot run in parallel');
    RETURN ODCIConst.Error;
  END;

  MEMBER FUNCTION ODCIAggregateTerminate(self IN OUT majority_vote_agg_t, returnValue OUT VARCHAR2, flags IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF ((SELF.candidate_count * 2) > SELF.total) THEN
      returnValue := SELF.candidate;
      RETURN ODCIConst.Success;
    END IF;
    returnValue := '';
    RETURN ODCIConst.Success;
  END;
END;
/
CREATE OR REPLACE FUNCTION majority_vote(p_s IN VARCHAR2) RETURN VARCHAR2 AGGREGATE USING majority_vote_agg_t;
/

CREATE OR REPLACE PACKAGE agg_library AS
END agg_library;
/

CREATE OR REPLACE PACKAGE BODY agg_library AS
END agg_library;
/