-- ======================================================================
-- Generated by pell 0.0.1 from module rolling
--   Source:     compiler/examples/13_pipelined_parallel.pell
--   SHA-256:    72ff9aa57c58a812cfe169ab6159ce2d564bee5d74c9c919f0b6374c7ec9a8bd
--   pell git:   0f8ffda
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
-- ======================================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE rolling_runningrow_obj FORCE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE OR REPLACE TYPE rolling_runningrow_obj AS OBJECT (
  country VARCHAR2(4000),
  ts TIMESTAMP,
  balance NUMBER
);
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE rolling_runningrow_nt FORCE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE OR REPLACE TYPE rolling_runningrow_nt AS TABLE OF rolling_runningrow_obj;
/

CREATE OR REPLACE PACKAGE rolling AS
  TYPE t_txn IS RECORD (
    country_code VARCHAR2(4000),
    ts TIMESTAMP,
    amount NUMBER
  );
  TYPE t_runningrow IS RECORD (
    country VARCHAR2(4000),
    ts TIMESTAMP,
    balance NUMBER
  );
  TYPE t_txn_cur IS REF CURSOR RETURN t_txn;
  FUNCTION rolling_balance(p_rows IN t_txn_cur) RETURN rolling_runningrow_nt PIPELINED PARALLEL_ENABLE(PARTITION p_rows BY HASH(country_code))
    ORDER p_rows BY (country_code, ts);
  FUNCTION distinct_per_country(p_rows IN t_txn_cur) RETURN rolling_runningrow_nt PIPELINED PARALLEL_ENABLE(PARTITION p_rows BY HASH(country_code))
    CLUSTER p_rows BY (country_code);
END rolling;
/

CREATE OR REPLACE PACKAGE BODY rolling AS

  FUNCTION rolling_balance(p_rows IN t_txn_cur) RETURN rolling_runningrow_nt PIPELINED PARALLEL_ENABLE(PARTITION p_rows BY HASH(country_code))
    ORDER p_rows BY (country_code, ts) IS
    l_seen NUMBER;
    l_cur_country VARCHAR2(4000);
    l_total NUMBER;
    TYPE t_txn_buf IS TABLE OF t_txn INDEX BY PLS_INTEGER;
    l_r_buf t_txn_buf;
  BEGIN
    l_seen := 0;
    l_cur_country := '';
    l_total := 0;
    LOOP
      FETCH p_rows BULK COLLECT INTO l_r_buf LIMIT 100;
      EXIT WHEN l_r_buf.COUNT = 0;
      FOR i_r IN 1 .. l_r_buf.COUNT LOOP
        IF (l_seen = 0) THEN
          l_cur_country := l_r_buf(i_r).country_code;
          l_seen := 1;
        ELSE
          IF (l_r_buf(i_r).country_code <> l_cur_country) THEN
            l_cur_country := l_r_buf(i_r).country_code;
            l_total := 0;
          END IF;
        END IF;
        l_total := (l_total + l_r_buf(i_r).amount);
        PIPE ROW(rolling_runningrow_obj(l_r_buf(i_r).country_code, l_r_buf(i_r).ts, l_total));
      END LOOP;
    END LOOP;
    CLOSE p_rows;
    RETURN;
  END rolling_balance;

  FUNCTION distinct_per_country(p_rows IN t_txn_cur) RETURN rolling_runningrow_nt PIPELINED PARALLEL_ENABLE(PARTITION p_rows BY HASH(country_code))
    CLUSTER p_rows BY (country_code) IS
    l_seen NUMBER;
    l_cur_country VARCHAR2(4000);
    l_n NUMBER;
    TYPE t_txn_buf IS TABLE OF t_txn INDEX BY PLS_INTEGER;
    l_r_buf t_txn_buf;
  BEGIN
    l_seen := 0;
    l_cur_country := '';
    l_n := 0;
    LOOP
      FETCH p_rows BULK COLLECT INTO l_r_buf LIMIT 100;
      EXIT WHEN l_r_buf.COUNT = 0;
      FOR i_r IN 1 .. l_r_buf.COUNT LOOP
        IF (l_seen = 0) THEN
          l_cur_country := l_r_buf(i_r).country_code;
          l_seen := 1;
        ELSE
          IF (l_r_buf(i_r).country_code <> l_cur_country) THEN
            l_cur_country := l_r_buf(i_r).country_code;
            l_n := 0;
          END IF;
        END IF;
        l_n := (l_n + 1);
        PIPE ROW(rolling_runningrow_obj(l_r_buf(i_r).country_code, l_r_buf(i_r).ts, l_n));
      END LOOP;
    END LOOP;
    CLOSE p_rows;
    RETURN;
  END distinct_per_country;
END rolling;
/