-- Generated by pell v0 from module emp_demo
-- DO NOT EDIT — regenerate with `pell build`

CREATE OR REPLACE PACKAGE emp_demo AS
  FUNCTION next_employee_id RETURN NUMBER;
  FUNCTION current_id RETURN NUMBER;
END emp_demo;
/

CREATE OR REPLACE PACKAGE BODY emp_demo AS

  FUNCTION next_employee_id RETURN NUMBER IS
    l_id NUMBER;
  BEGIN
    l_id := employee_id_seq.nextval;
    RETURN l_id;
  END next_employee_id;

  FUNCTION current_id RETURN NUMBER IS
  BEGIN
    RETURN employee_id_seq.currval;
  END current_id;
END emp_demo;
/