-- ======================================================================
-- Generated by pell 0.0.1 from module retry_demo
--   Source:     compiler/examples/15_retry.pell
--   SHA-256:    fd3bb122eebb627ce87b48a0f9f57a8fa4c06ed75f4bdcaf77f7aba52844e0b5
--   pell git:   7cccd8f
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     retry_audit_log
--     retry_jobs
--   packages:
--     pell_runtime
-- ======================================================================

-- Additions to pell_runtime for module retry_demo:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   retry_demo_invariantbroken EXCEPTION;  -- panic
--   PRAGMA EXCEPTION_INIT(retry_demo_invariantbroken, -20300);
--   retry_demo_auditfailed EXCEPTION;  -- skip
--   PRAGMA EXCEPTION_INIT(retry_demo_auditfailed, -20200);
--   retry_demo_jobfailed EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(retry_demo_jobfailed, -20100);

CREATE OR REPLACE PACKAGE retry_demo AS
  PROCEDURE enqueue_job(p_name IN VARCHAR2);
  PROCEDURE audit_event(p_action IN VARCHAR2);
  FUNCTION divide_by_zero RETURN NUMBER;
END retry_demo;
/

CREATE OR REPLACE PACKAGE BODY retry_demo AS

  FUNCTION pell_is_panic(p_code IN NUMBER) RETURN BOOLEAN IS
  BEGIN
    IF p_code BETWEEN -20399 AND -20300 THEN RETURN TRUE; END IF;
    IF p_code IN (-1476, -6502, -6592, -4068, -1410, -1483, -6500, -6501, -6504, -7445) THEN RETURN TRUE; END IF;
    RETURN FALSE;
  END pell_is_panic;

  PROCEDURE enqueue_job(p_name IN VARCHAR2) IS
    l_pell_attempt PLS_INTEGER := 0;
  BEGIN
    LOOP
      SAVEPOINT pell_attempt;  -- @ 15_retry.pell:40
      BEGIN
        insert into retry_jobs (name, status, attempted_at)
                   values (p_name, 'PENDING', systimestamp);
        RETURN;
        EXIT;
      EXCEPTION
        WHEN OTHERS THEN
          IF pell_is_panic(SQLCODE) THEN RAISE; END IF;
          l_pell_attempt := l_pell_attempt + 1;
          ROLLBACK TO pell_attempt;  -- @ 15_retry.pell:40
          IF l_pell_attempt >= 5 THEN RAISE; END IF;
          DBMS_SESSION.SLEEP(LEAST((5000 / 1000), (((100 / 1000) * POWER(2, l_pell_attempt - 1)) * (0.75 + DBMS_RANDOM.VALUE * 0.5))));
      END;
    END LOOP;
  END enqueue_job;

  PROCEDURE audit_event(p_action IN VARCHAR2) IS
    l_pell_attempt PLS_INTEGER := 0;
  BEGIN
    LOOP
      SAVEPOINT pell_attempt;  -- @ 15_retry.pell:47
      BEGIN
        insert into retry_audit_log (action, ts)
                   values (p_action, systimestamp);
        RETURN;
        EXIT;
      EXCEPTION
        WHEN OTHERS THEN
          IF pell_is_panic(SQLCODE) THEN RAISE; END IF;
          l_pell_attempt := l_pell_attempt + 1;
          ROLLBACK TO pell_attempt;  -- @ 15_retry.pell:47
          IF l_pell_attempt >= 3 THEN RAISE; END IF;
          DBMS_SESSION.SLEEP((50 / 1000));
      END;
    END LOOP;
  END audit_event;

  FUNCTION divide_by_zero RETURN NUMBER IS
    l_pell_attempt PLS_INTEGER := 0;
    l_z NUMBER;
    l_r NUMBER;
  BEGIN
    LOOP
      SAVEPOINT pell_attempt;  -- @ 15_retry.pell:57
      BEGIN
        l_z := 0;
        l_r := (1 / l_z);
        RETURN l_r;
        EXIT;
      EXCEPTION
        WHEN OTHERS THEN
          IF pell_is_panic(SQLCODE) THEN RAISE; END IF;
          l_pell_attempt := l_pell_attempt + 1;
          ROLLBACK TO pell_attempt;  -- @ 15_retry.pell:57
          IF l_pell_attempt >= 5 THEN RAISE; END IF;
          DBMS_SESSION.SLEEP((1000 / 1000));
      END;
    END LOOP;
  END divide_by_zero;
END retry_demo;
/