-- ======================================================================
-- Generated by pell 0.0.1 from module dyn_demo
--   Source:     compiler/examples/16_dyn_sql.pell
--   SHA-256:    d479084b3f04ec944083456539951a1bc63b56508ecd8877c2d4e69a115721d1
--   pell git:   8e29044
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     dyn_archive_orders
--     dyn_orders
-- ======================================================================

CREATE OR REPLACE PACKAGE dyn_demo AS
  FUNCTION count_in(p_tname IN VARCHAR2, p_st IN VARCHAR2) RETURN NUMBER;
  PROCEDURE set_status(p_tname IN VARCHAR2, p_new_st IN VARCHAR2, p_id IN NUMBER);
END dyn_demo;
/

CREATE OR REPLACE PACKAGE BODY dyn_demo AS

  -- Pinning declarations for dynamic-SQL @touches. Never invoked;
  -- exists so Oracle ALL_DEPENDENCIES tracks references hidden
  -- in EXECUTE IMMEDIATE strings.
  PROCEDURE pell_dep_pinning IS
    CURSOR pin_dyn_archive_orders IS SELECT 1 FROM dyn_archive_orders WHERE 1=0;
    CURSOR pin_dyn_orders IS SELECT 1 FROM dyn_orders WHERE 1=0;
  BEGIN NULL; END pell_dep_pinning;

  FUNCTION count_in(p_tname IN VARCHAR2, p_st IN VARCHAR2) RETURN NUMBER IS
    l_n NUMBER;
  BEGIN
    EXECUTE IMMEDIATE ('select count(*) from ' || p_tname || ' where status = :st') INTO l_n USING p_st;
    RETURN l_n;
  END count_in;

  PROCEDURE set_status(p_tname IN VARCHAR2, p_new_st IN VARCHAR2, p_id IN NUMBER) IS
  BEGIN
    EXECUTE IMMEDIATE ('update ' || p_tname || ' set status = :new_st where id = :id') USING p_new_st, p_id;
  END set_status;
END dyn_demo;
/