-- ======================================================================
-- Generated by pell 0.0.1 from module pivot_demo
--   Source:     compiler/examples/17_pivot.pell
--   SHA-256:    d02489e7b2c0eba32e72a28d76d2febe5fbf878e3c4b555f39b44eacca3f57b3
--   pell git:   7cccd8f
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     pivot_orders
-- ======================================================================

CREATE OR REPLACE PACKAGE pivot_demo AS
  -- enum Region
  region_north CONSTANT VARCHAR2(200) := 'NORTH';
  region_south CONSTANT VARCHAR2(200) := 'SOUTH';
  region_east CONSTANT VARCHAR2(200) := 'EAST';
  region_west CONSTANT VARCHAR2(200) := 'WEST';
  TYPE t_regiontotals IS RECORD (
    product VARCHAR2(4000),
    north NUMBER,
    south NUMBER,
    east NUMBER,
    west NUMBER
  );
  TYPE t_RegionTotals_list IS TABLE OF t_regiontotals INDEX BY PLS_INTEGER;
  FUNCTION list_totals RETURN t_RegionTotals_list;
  FUNCTION region_sales_dyn RETURN SYS_REFCURSOR;
END pivot_demo;
/

CREATE OR REPLACE PACKAGE BODY pivot_demo AS

  -- Pinning declarations for dynamic-SQL @touches. Never invoked;
  -- exists so Oracle ALL_DEPENDENCIES tracks references hidden
  -- in EXECUTE IMMEDIATE strings.
  PROCEDURE pell_dep_pinning IS
    CURSOR pin_pivot_orders IS SELECT 1 FROM pivot_orders WHERE 1=0;
  BEGIN NULL; END pell_dep_pinning;

  FUNCTION list_totals RETURN t_RegionTotals_list IS
    l_rows t_RegionTotals_list;
  BEGIN
    SELECT *
      BULK COLLECT INTO l_rows
      FROM (
  select product, region, sales from pivot_orders
) PIVOT (
  SUM(sales) FOR region IN (
      'NORTH' AS "NORTH",
      'SOUTH' AS "SOUTH",
      'EAST' AS "EAST",
      'WEST' AS "WEST"
  )
);
    RETURN l_rows;
  END list_totals;

  FUNCTION region_sales_dyn RETURN SYS_REFCURSOR IS
    l_pell_pivot_cols VARCHAR2(4000);
    l_pell_pivot_sql  VARCHAR2(32767);
    l_pell_pivot_cur  SYS_REFCURSOR;
  BEGIN
    SELECT LISTAGG('''' || region || ''' AS "' || region || '"', ', ')
             WITHIN GROUP (ORDER BY region)
      INTO l_pell_pivot_cols
      FROM (SELECT DISTINCT region FROM (
    select product, region, sales from pivot_orders
      )) WHERE region IS NOT NULL;
    l_pell_pivot_sql :=
      'SELECT * FROM (' ||
      'select product, region, sales from pivot_orders' ||
      ') PIVOT (SUM(sales) FOR region IN (' ||
      l_pell_pivot_cols ||
      '))';
    OPEN l_pell_pivot_cur FOR l_pell_pivot_sql;
    RETURN l_pell_pivot_cur;
  END region_sales_dyn;
END pivot_demo;
/