-- ======================================================================
-- Generated by pell 0.0.1 from module json_demo
--   Source:     compiler/examples/18_json.pell
--   SHA-256:    74e2e7086de2b57134fa305c945896e367b6ecf379a61c17d059110fdc799f8d
--   pell git:   2b77ce0
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
-- ======================================================================

CREATE OR REPLACE PACKAGE json_demo AS
  TYPE t_user IS RECORD (
    name VARCHAR2(4000),
    age NUMBER
  );
  FUNCTION pack(p_u IN t_user) RETURN JSON;
  FUNCTION unpack_name(p_j IN JSON) RETURN VARCHAR2;
  FUNCTION audit_event(p_action IN VARCHAR2, p_who IN VARCHAR2) RETURN JSON;
  FUNCTION list_things(p_a IN NUMBER, p_b IN NUMBER, p_c IN NUMBER) RETURN JSON;
  FUNCTION extract_text(p_j IN JSON, p_path IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION extract_number(p_j IN JSON, p_path IN VARCHAR2) RETURN NUMBER;
  FUNCTION has_path(p_j IN JSON, p_path IN VARCHAR2) RETURN BOOLEAN;
  FUNCTION parse_json(p_s IN VARCHAR2) RETURN JSON;
  FUNCTION to_text(p_j IN JSON) RETURN VARCHAR2;
  FUNCTION build_simple RETURN JSON;
  FUNCTION build_nested RETURN JSON;
  FUNCTION modify(p_input IN JSON) RETURN JSON;
END json_demo;
/

CREATE OR REPLACE PACKAGE BODY json_demo AS

  FUNCTION pack(p_u IN t_user) RETURN JSON IS
  BEGIN
    RETURN JSON_OBJECT('name' VALUE p_u.name, 'age' VALUE p_u.age RETURNING JSON);
  END pack;

  FUNCTION unpack_name(p_j IN JSON) RETURN VARCHAR2 IS
    l_u t_user;
  BEGIN
    l_u.name := JSON_VALUE(p_j, '$.name');
    l_u.age := JSON_VALUE(p_j, '$.age' RETURNING NUMBER);
    RETURN l_u.name;
  END unpack_name;

  FUNCTION audit_event(p_action IN VARCHAR2, p_who IN VARCHAR2) RETURN JSON IS
  BEGIN
    RETURN JSON_OBJECT('action' VALUE p_action, 'who' VALUE p_who, 'ts' VALUE sysdate() RETURNING JSON);
  END audit_event;

  FUNCTION list_things(p_a IN NUMBER, p_b IN NUMBER, p_c IN NUMBER) RETURN JSON IS
  BEGIN
    RETURN JSON_ARRAY(p_a, p_b, p_c RETURNING JSON);
  END list_things;

  FUNCTION extract_text(p_j IN JSON, p_path IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN JSON_VALUE(p_j, p_path);
  END extract_text;

  FUNCTION extract_number(p_j IN JSON, p_path IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    RETURN JSON_VALUE(p_j, p_path RETURNING NUMBER);
  END extract_number;

  FUNCTION has_path(p_j IN JSON, p_path IN VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN JSON_EXISTS(p_j, p_path);
  END has_path;

  FUNCTION parse_json(p_s IN VARCHAR2) RETURN JSON IS
  BEGIN
    RETURN JSON(p_s);
  END parse_json;

  FUNCTION to_text(p_j IN JSON) RETURN VARCHAR2 IS
  BEGIN
    RETURN JSON_SERIALIZE(p_j);
  END to_text;

  FUNCTION build_simple RETURN JSON IS
    l_j JSON;
  BEGIN
    SELECT JSON_TRANSFORM(JSON_OBJECT(RETURNING JSON),
      SET '$.name' = 'Alice' CREATE ON MISSING,
      SET '$.age' = 30 CREATE ON MISSING,
      SET '$.status' = 'active' CREATE ON MISSING
    ) INTO l_j FROM dual;
    RETURN l_j;
  END build_simple;

  FUNCTION build_nested RETURN JSON IS
    l_j JSON;
  BEGIN
    SELECT JSON_TRANSFORM(JSON_OBJECT(RETURNING JSON),
      SET '$.user' = JSON_OBJECT(RETURNING JSON) CREATE ON MISSING,
      SET '$.user.name' = 'Bob' CREATE ON MISSING,
      SET '$.user.email' = 'bob@example.com' CREATE ON MISSING,
      SET '$.user.address' = JSON_OBJECT(RETURNING JSON) CREATE ON MISSING,
      SET '$.user.address.city' = 'NYC' CREATE ON MISSING,
      SET '$.user.address.zip' = '10001' CREATE ON MISSING,
      SET '$.meta' = JSON_OBJECT(RETURNING JSON) CREATE ON MISSING,
      SET '$.meta.created' = 'today' CREATE ON MISSING
    ) INTO l_j FROM dual;
    RETURN l_j;
  END build_nested;

  FUNCTION modify(p_input IN JSON) RETURN JSON IS
    l_j JSON;
  BEGIN
    SELECT JSON_TRANSFORM(p_input,
      SET '$.updated_at' = 'yes' CREATE ON MISSING,
      REMOVE '$.draft',
      APPEND '$.history' = 'edited'
    ) INTO l_j FROM dual;
    RETURN l_j;
  END modify;
END json_demo;
/