-- ======================================================================
-- Generated by pell 0.0.1 from module json_demo
--   Source:     compiler/examples/18_json.pell
--   SHA-256:    74e2e7086de2b57134fa305c945896e367b6ecf379a61c17d059110fdc799f8d
--   pell git:   1daa948
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
-- ======================================================================

CREATE OR REPLACE PACKAGE json_demo AS
  TYPE t_user IS RECORD (
    name VARCHAR2(4000),
    age NUMBER
  );
  FUNCTION pack(p_u IN t_user) RETURN JSON;
  FUNCTION unpack_name(p_j IN JSON) RETURN VARCHAR2;
  FUNCTION audit_event(p_action IN VARCHAR2, p_who IN VARCHAR2) RETURN JSON;
  FUNCTION list_things(p_a IN NUMBER, p_b IN NUMBER, p_c IN NUMBER) RETURN JSON;
  FUNCTION extract_text(p_j IN JSON, p_path IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION extract_number(p_j IN JSON, p_path IN VARCHAR2) RETURN NUMBER;
  FUNCTION has_path(p_j IN JSON, p_path IN VARCHAR2) RETURN BOOLEAN;
  FUNCTION parse_json(p_s IN VARCHAR2) RETURN JSON;
  FUNCTION to_text(p_j IN JSON) RETURN VARCHAR2;
  FUNCTION build_simple RETURN JSON;
  FUNCTION build_nested RETURN JSON;
  FUNCTION modify(p_input IN JSON) RETURN JSON;
END json_demo;
/

CREATE OR REPLACE PACKAGE BODY json_demo AS

  FUNCTION pack(p_u IN t_user) RETURN JSON IS
  BEGIN
    RETURN JSON_OBJECT('name' VALUE p_u.name, 'age' VALUE p_u.age RETURNING JSON);
  END pack;

  FUNCTION unpack_name(p_j IN JSON) RETURN VARCHAR2 IS
    l_u t_user;
  BEGIN
    l_u.name := JSON_VALUE(p_j, '$.name');
    l_u.age := JSON_VALUE(p_j, '$.age' RETURNING NUMBER);
    RETURN l_u.name;
  END unpack_name;

  FUNCTION audit_event(p_action IN VARCHAR2, p_who IN VARCHAR2) RETURN JSON IS
  BEGIN
    RETURN JSON_OBJECT('action' VALUE p_action, 'who' VALUE p_who, 'ts' VALUE sysdate() RETURNING JSON);
  END audit_event;

  FUNCTION list_things(p_a IN NUMBER, p_b IN NUMBER, p_c IN NUMBER) RETURN JSON IS
  BEGIN
    RETURN JSON_ARRAY(p_a, p_b, p_c RETURNING JSON);
  END list_things;

  FUNCTION extract_text(p_j IN JSON, p_path IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN JSON_VALUE(p_j, p_path);
  END extract_text;

  FUNCTION extract_number(p_j IN JSON, p_path IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    RETURN JSON_VALUE(p_j, p_path RETURNING NUMBER);
  END extract_number;

  FUNCTION has_path(p_j IN JSON, p_path IN VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN JSON_EXISTS(p_j, p_path);
  END has_path;

  FUNCTION parse_json(p_s IN VARCHAR2) RETURN JSON IS
  BEGIN
    RETURN JSON(p_s);
  END parse_json;

  FUNCTION to_text(p_j IN JSON) RETURN VARCHAR2 IS
  BEGIN
    RETURN JSON_SERIALIZE(p_j);
  END to_text;

  FUNCTION build_simple RETURN JSON IS
    l_j JSON;
    l_pell_jobj_0 JSON_OBJECT_T;
  BEGIN
    l_pell_jobj_0 := JSON_OBJECT_T(JSON_OBJECT(RETURNING JSON));
    l_pell_jobj_0.put('name', 'Alice');
    l_pell_jobj_0.put('age', 30);
    l_pell_jobj_0.put('status', 'active');
    l_j := l_pell_jobj_0.to_json();
    RETURN l_j;
  END build_simple;

  FUNCTION build_nested RETURN JSON IS
    l_j JSON;
    l_pell_jobj_0 JSON_OBJECT_T;
    l_pell_jobj_1 JSON_OBJECT_T;
    l_pell_jobj_2 JSON_OBJECT_T;
    l_pell_jobj_3 JSON_OBJECT_T;
    l_pell_jobj_4 JSON_OBJECT_T;
    l_pell_jobj_5 JSON_OBJECT_T;
    l_pell_jobj_6 JSON_OBJECT_T;
    l_pell_jobj_7 JSON_OBJECT_T;
  BEGIN
    l_pell_jobj_0 := JSON_OBJECT_T(JSON_OBJECT(RETURNING JSON));
    IF NOT l_pell_jobj_0.has('user') THEN
      l_pell_jobj_0.put('user', JSON_OBJECT_T());
    END IF;
    l_pell_jobj_1 := l_pell_jobj_0.get_object('user');
    l_pell_jobj_1.put('name', 'Bob');
    l_pell_jobj_0.put('user', l_pell_jobj_1);
    IF NOT l_pell_jobj_0.has('user') THEN
      l_pell_jobj_0.put('user', JSON_OBJECT_T());
    END IF;
    l_pell_jobj_2 := l_pell_jobj_0.get_object('user');
    l_pell_jobj_2.put('email', 'bob@example.com');
    l_pell_jobj_0.put('user', l_pell_jobj_2);
    IF NOT l_pell_jobj_0.has('user') THEN
      l_pell_jobj_0.put('user', JSON_OBJECT_T());
    END IF;
    l_pell_jobj_3 := l_pell_jobj_0.get_object('user');
    IF NOT l_pell_jobj_3.has('address') THEN
      l_pell_jobj_3.put('address', JSON_OBJECT_T());
    END IF;
    l_pell_jobj_4 := l_pell_jobj_3.get_object('address');
    l_pell_jobj_4.put('city', 'NYC');
    l_pell_jobj_3.put('address', l_pell_jobj_4);
    l_pell_jobj_0.put('user', l_pell_jobj_3);
    IF NOT l_pell_jobj_0.has('user') THEN
      l_pell_jobj_0.put('user', JSON_OBJECT_T());
    END IF;
    l_pell_jobj_5 := l_pell_jobj_0.get_object('user');
    IF NOT l_pell_jobj_5.has('address') THEN
      l_pell_jobj_5.put('address', JSON_OBJECT_T());
    END IF;
    l_pell_jobj_6 := l_pell_jobj_5.get_object('address');
    l_pell_jobj_6.put('zip', '10001');
    l_pell_jobj_5.put('address', l_pell_jobj_6);
    l_pell_jobj_0.put('user', l_pell_jobj_5);
    IF NOT l_pell_jobj_0.has('meta') THEN
      l_pell_jobj_0.put('meta', JSON_OBJECT_T());
    END IF;
    l_pell_jobj_7 := l_pell_jobj_0.get_object('meta');
    l_pell_jobj_7.put('created', 'today');
    l_pell_jobj_0.put('meta', l_pell_jobj_7);
    l_j := l_pell_jobj_0.to_json();
    RETURN l_j;
  END build_nested;

  FUNCTION modify(p_input IN JSON) RETURN JSON IS
    l_j JSON;
    l_pell_jobj_0 JSON_OBJECT_T;
    l_pell_jarr_1 JSON_ARRAY_T;
  BEGIN
    l_pell_jobj_0 := JSON_OBJECT_T(p_input);
    l_pell_jobj_0.put('updated_at', 'yes');
    l_pell_jobj_0.remove('draft');
    IF l_pell_jobj_0.has('history') THEN
      l_pell_jarr_1 := l_pell_jobj_0.get_array('history');
    ELSE
      l_pell_jarr_1 := JSON_ARRAY_T();
    END IF;
    l_pell_jarr_1.append('edited');
    l_pell_jobj_0.put('history', l_pell_jarr_1);
    l_j := l_pell_jobj_0.to_json();
    RETURN l_j;
  END modify;
END json_demo;
/