-- ======================================================================
-- Generated by pell 0.0.1 from module jq_demo
--   Source:     compiler/examples/19_jq.pell
--   SHA-256:    5c3e5fc8e661196ce373e388f599b0f1255e2dd5c17858d6c7cdcafdb45b4798
--   pell git:   b3f4f0f
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
-- ======================================================================

CREATE OR REPLACE PACKAGE jq_demo AS
  TYPE t_user IS RECORD (
    name VARCHAR2(4000),
    age NUMBER
  );
  TYPE t_text_list IS TABLE OF VARCHAR2(4000) INDEX BY PLS_INTEGER;
  TYPE t_User_list IS TABLE OF t_user INDEX BY PLS_INTEGER;
  FUNCTION adult_names(p_j IN JSON) RETURN t_text_list;
  FUNCTION first_names(p_j IN JSON) RETURN t_text_list;
  FUNCTION all_users(p_j IN JSON) RETURN t_User_list;
  FUNCTION working_age(p_j IN JSON) RETURN t_text_list;
END jq_demo;
/

CREATE OR REPLACE PACKAGE BODY jq_demo AS

  FUNCTION adult_names(p_j IN JSON) RETURN t_text_list IS
    l_names t_text_list;
  BEGIN
    SELECT jt.v
      BULK COLLECT INTO l_names
      FROM JSON_TABLE(p_j, '$.users[*]'
    COLUMNS (v VARCHAR2(4000) PATH '$.name', f0 NUMBER PATH '$.age')) jt
  WHERE jt.f0 >= 18;
    RETURN l_names;
  END adult_names;

  FUNCTION first_names(p_j IN JSON) RETURN t_text_list IS
    l_names t_text_list;
  BEGIN
    SELECT jt.v
      BULK COLLECT INTO l_names
      FROM JSON_TABLE(p_j, '$[*]'
    COLUMNS (v VARCHAR2(4000) PATH '$.name')) jt;
    RETURN l_names;
  END first_names;

  FUNCTION all_users(p_j IN JSON) RETURN t_User_list IS
    l_users t_User_list;
  BEGIN
    SELECT jt.name, jt.age
      BULK COLLECT INTO l_users
      FROM JSON_TABLE(p_j, '$.users[*]'
    COLUMNS (name VARCHAR2(4000) PATH '$.name', age NUMBER PATH '$.age')) jt;
    RETURN l_users;
  END all_users;

  FUNCTION working_age(p_j IN JSON) RETURN t_text_list IS
    l_names t_text_list;
  BEGIN
    SELECT jt.v
      BULK COLLECT INTO l_names
      FROM JSON_TABLE(p_j, '$.users[*]'
    COLUMNS (v VARCHAR2(4000) PATH '$.name', f0 NUMBER PATH '$.age')) jt
  WHERE jt.f0 >= 18 AND jt.f0 <= 65;
    RETURN l_names;
  END working_age;
END jq_demo;
/