-- ======================================================================
-- Generated by pell 0.0.1 from module re_demo
--   Source:     compiler/examples/20_re.pell
--   SHA-256:    2ea1ff174c59af499f7ee7b2e7d9fad3b15bc613bb70c69ec333618b965dbcad
--   pell git:   49d3402
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     re
-- ======================================================================

CREATE OR REPLACE PACKAGE re_demo AS
  TYPE t_text_list IS TABLE OF VARCHAR2(4000) INDEX BY PLS_INTEGER;
  FUNCTION is_email(p_s IN VARCHAR2) RETURN BOOLEAN;
  FUNCTION first_number(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION all_numbers(p_s IN VARCHAR2) RETURN t_text_list;
  FUNCTION redact_digits(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION words(p_s IN VARCHAR2) RETURN t_text_list;
END re_demo;
/

CREATE OR REPLACE PACKAGE BODY re_demo AS

  FUNCTION pell_re_find_all(p_s VARCHAR2, p_pat VARCHAR2) RETURN t_text_list IS
    src pell_re.t_text_list := pell_re.find_all(p_s, p_pat);
    out t_text_list;
  BEGIN
    IF src.COUNT = 0 THEN RETURN out; END IF;
    FOR i IN src.FIRST .. src.LAST LOOP
      out(i) := src(i);
    END LOOP;
    RETURN out;
  END pell_re_find_all;

  FUNCTION pell_re_split(p_s VARCHAR2, p_pat VARCHAR2) RETURN t_text_list IS
    src pell_re.t_text_list := pell_re.split(p_s, p_pat);
    out t_text_list;
  BEGIN
    IF src.COUNT = 0 THEN RETURN out; END IF;
    FOR i IN src.FIRST .. src.LAST LOOP
      out(i) := src(i);
    END LOOP;
    RETURN out;
  END pell_re_split;

  FUNCTION is_email(p_s IN VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN pell_re.matches(p_s, '\A[A-Za-z0-9._%+\-]+@[A-Za-z0-9\-]+(\.[A-Za-z0-9\-]+)*\.[A-Za-z]{2,}\z');
  END is_email;

  FUNCTION first_number(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN pell_re.find(p_s, '\d+');
  END first_number;

  FUNCTION all_numbers(p_s IN VARCHAR2) RETURN t_text_list IS
  BEGIN
    RETURN pell_re_find_all(p_s, '\d+');
  END all_numbers;

  FUNCTION redact_digits(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN pell_re.replace_all(p_s, '\d', '*');
  END redact_digits;

  FUNCTION words(p_s IN VARCHAR2) RETURN t_text_list IS
  BEGIN
    RETURN pell_re_split(p_s, '\s+');
  END words;
END re_demo;
/