-- ======================================================================
-- Generated by pell 0.0.1 from module re_capture_demo
--   Source:     compiler/examples/21_re_capture.pell
--   SHA-256:    3111a0cd8209c42b3b0619d6daa5a27eccb9b20c09afb2fed5c72ecd83aa6e6b
--   pell git:   3088760
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     re
-- ======================================================================

CREATE OR REPLACE PACKAGE re_capture_demo AS
  TYPE t_phone IS RECORD (
    area VARCHAR2(4000),
    prefix VARCHAR2(4000),
    line VARCHAR2(4000)
  );
  TYPE t_email IS RECORD (
    user VARCHAR2(4000),
    domain VARCHAR2(4000)
  );
  TYPE t_kv IS RECORD (
    k VARCHAR2(4000),
    v VARCHAR2(4000)
  );
  FUNCTION parse_phone(p_s IN VARCHAR2) RETURN t_phone;
  FUNCTION parse_email(p_s IN VARCHAR2) RETURN t_email;
  FUNCTION parse_kv(p_s IN VARCHAR2) RETURN t_kv;
END re_capture_demo;
/

CREATE OR REPLACE PACKAGE BODY re_capture_demo AS

  FUNCTION parse_phone(p_s IN VARCHAR2) RETURN t_phone IS
    l_p t_phone;
    l_pell_caps_0 pell_re.t_capture_map;
  BEGIN
    l_pell_caps_0 := pell_re.capture_by_name(p_s, '(?<area>\d{3})-(?<prefix>\d{3})-(?<line>\d{4})');
    IF l_pell_caps_0.EXISTS('area') THEN
      l_p.area := l_pell_caps_0('area').match_text;
    END IF;
    IF l_pell_caps_0.EXISTS('prefix') THEN
      l_p.prefix := l_pell_caps_0('prefix').match_text;
    END IF;
    IF l_pell_caps_0.EXISTS('line') THEN
      l_p.line := l_pell_caps_0('line').match_text;
    END IF;
    RETURN l_p;
  END parse_phone;

  FUNCTION parse_email(p_s IN VARCHAR2) RETURN t_email IS
    l_e t_email;
    l_pell_caps_0 pell_re.t_capture_map;
  BEGIN
    l_pell_caps_0 := pell_re.capture_by_name(p_s, '(?<user>\w+)@(?<domain>[\w.]+)');
    IF l_pell_caps_0.EXISTS('user') THEN
      l_e.user := l_pell_caps_0('user').match_text;
    END IF;
    IF l_pell_caps_0.EXISTS('domain') THEN
      l_e.domain := l_pell_caps_0('domain').match_text;
    END IF;
    RETURN l_e;
  END parse_email;

  FUNCTION parse_kv(p_s IN VARCHAR2) RETURN t_kv IS
    l_kv t_kv;
    l_pell_caps_0 pell_re.t_capture_map;
  BEGIN
    l_pell_caps_0 := pell_re.capture_by_name(p_s, '(?<k>\w+)=(?<v>\S+)');
    IF l_pell_caps_0.EXISTS('k') THEN
      l_kv.k := l_pell_caps_0('k').match_text;
    END IF;
    IF l_pell_caps_0.EXISTS('v') THEN
      l_kv.v := l_pell_caps_0('v').match_text;
    END IF;
    RETURN l_kv;
  END parse_kv;
END re_capture_demo;
/