-- ======================================================================
-- Generated by pell 0.0.1 from module collections_linked_list
--   Source:     compiler/examples/22_linked_list.pell
--   SHA-256:    2e07501cd0e7c84454f2ec2f34b5ecc89341fac5d67b310f18bfddf85de5fffc
--   pell git:   6ceeb3a
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     dual
-- ======================================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE t_intlist FORCE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE OR REPLACE TYPE t_intlist AS OBJECT (
  sys_tag_ NUMBER,
  NOT INSTANTIABLE MEMBER FUNCTION len RETURN NUMBER,
  NOT INSTANTIABLE MEMBER FUNCTION sum RETURN NUMBER,
  NOT INSTANTIABLE MEMBER FUNCTION has(p_needle IN NUMBER) RETURN BOOLEAN,
  NOT INSTANTIABLE MEMBER FUNCTION empty RETURN BOOLEAN
) NOT INSTANTIABLE NOT FINAL;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE t_cons FORCE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE OR REPLACE TYPE t_cons UNDER t_intlist (
  head NUMBER,
  tail t_intlist,
  OVERRIDING MEMBER FUNCTION len RETURN NUMBER,
  OVERRIDING MEMBER FUNCTION sum RETURN NUMBER,
  OVERRIDING MEMBER FUNCTION has(p_needle IN NUMBER) RETURN BOOLEAN,
  OVERRIDING MEMBER FUNCTION empty RETURN BOOLEAN
);
/
CREATE OR REPLACE TYPE BODY t_cons AS
  OVERRIDING MEMBER FUNCTION len RETURN NUMBER IS
  BEGIN
    RETURN (1 + SELF.tail.len());
  END;

  OVERRIDING MEMBER FUNCTION sum RETURN NUMBER IS
  BEGIN
    RETURN (SELF.head + SELF.tail.sum());
  END;

  OVERRIDING MEMBER FUNCTION has(p_needle IN NUMBER) RETURN BOOLEAN IS
  BEGIN
    IF (SELF.head = p_needle) THEN
      RETURN TRUE;
    END IF;
    RETURN SELF.tail.has(p_needle);
  END;

  OVERRIDING MEMBER FUNCTION empty RETURN BOOLEAN IS
  BEGIN
    RETURN FALSE;
  END;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE t_nil FORCE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE OR REPLACE TYPE t_nil UNDER t_intlist (
  OVERRIDING MEMBER FUNCTION len RETURN NUMBER,
  OVERRIDING MEMBER FUNCTION sum RETURN NUMBER,
  OVERRIDING MEMBER FUNCTION has(p_needle IN NUMBER) RETURN BOOLEAN,
  OVERRIDING MEMBER FUNCTION empty RETURN BOOLEAN
);
/
CREATE OR REPLACE TYPE BODY t_nil AS
  OVERRIDING MEMBER FUNCTION len RETURN NUMBER IS
  BEGIN
    RETURN 0;
  END;

  OVERRIDING MEMBER FUNCTION sum RETURN NUMBER IS
  BEGIN
    RETURN 0;
  END;

  OVERRIDING MEMBER FUNCTION has(p_needle IN NUMBER) RETURN BOOLEAN IS
  BEGIN
    RETURN FALSE;
  END;

  OVERRIDING MEMBER FUNCTION empty RETURN BOOLEAN IS
  BEGIN
    RETURN TRUE;
  END;
END;
/

CREATE OR REPLACE PACKAGE collections_linked_list AS
  TYPE t_summary IS RECORD (
    count NUMBER,
    total NUMBER,
    contains_zero BOOLEAN
  );
  TYPE t_number_list IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  FUNCTION nil RETURN t_intlist;
  FUNCTION cons(p_h IN NUMBER, p_t IN t_intlist) RETURN t_intlist;
  FUNCTION from_list(p_xs IN t_number_list) RETURN t_intlist;
  FUNCTION reversed(p_xs IN t_intlist) RETURN t_intlist;
  FUNCTION summarize(p_xs IN t_intlist) RETURN t_summary;
END collections_linked_list;
/

CREATE OR REPLACE PACKAGE BODY collections_linked_list AS

  FUNCTION nil RETURN t_intlist IS
  BEGIN
    RETURN t_nil(2);
  END nil;

  FUNCTION cons(p_h IN NUMBER, p_t IN t_intlist) RETURN t_intlist IS
  BEGIN
    RETURN t_cons(1, p_h, p_t);
  END cons;

  FUNCTION from_list(p_xs IN t_number_list) RETURN t_intlist IS
    l_ys t_number_list;
    l_acc t_intlist;
    l_pos NUMBER;
  BEGIN
    l_ys := p_xs;
    l_acc := t_nil(2);
    FOR j IN l_ys.FIRST .. l_ys.LAST LOOP
      l_pos := ((l_ys.LAST - j) + l_ys.FIRST);
      l_acc := t_cons(1, l_ys(l_pos), l_acc);
    END LOOP;
    RETURN l_acc;
  END from_list;

  FUNCTION reversed(p_xs IN t_intlist) RETURN t_intlist IS
    l_cur t_intlist;
    l_acc t_intlist;
    l_bound NUMBER;
    l_guard t_number_list;
  BEGIN
    l_cur := p_xs;
    l_acc := t_nil(2);
    l_bound := p_xs.len();
    select level
      BULK COLLECT INTO l_guard
      FROM dual connect by level <= l_bound;
    FOR k IN l_guard.FIRST .. l_guard.LAST LOOP
      IF l_cur.sys_tag_ = 1 THEN
        DECLARE
          l_h NUMBER;
          l_t t_intlist;
        BEGIN
          l_h := TREAT((l_cur) AS t_cons).head;
          l_t := TREAT((l_cur) AS t_cons).tail;
          l_acc := t_cons(1, l_h, l_acc);
          l_cur := l_t;
        END;
      ELSIF l_cur.sys_tag_ = 2 THEN
        NULL;
      END IF;
    END LOOP;
    RETURN l_acc;
  END reversed;

  FUNCTION summarize(p_xs IN t_intlist) RETURN t_summary IS
    l_ret_1 t_summary;
  BEGIN
    l_ret_1.count := p_xs.len();
    l_ret_1.total := p_xs.sum();
    l_ret_1.contains_zero := p_xs.has(0);
    RETURN l_ret_1;
  END summarize;
END collections_linked_list;
/