-- ======================================================================
-- Generated by pell 0.0.1 from module datetime
--   Source:     compiler/examples/23_datetime.pell
--   SHA-256:    606d2e2d5e853c0c93d653ca1c644daf8cb3351278a1f3bb95c6e974bdd31c15
--   Target:     Oracle 23
--   Schema:     std
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     dual
-- ======================================================================

CREATE OR REPLACE PACKAGE std.datetime AS
  FUNCTION now RETURN TIMESTAMP;
  FUNCTION utc_now RETURN TIMESTAMP;
  FUNCTION today RETURN TIMESTAMP;
  FUNCTION convert_tz(p_ts IN TIMESTAMP, p_src_tz IN VARCHAR2, p_dst_tz IN VARCHAR2) RETURN TIMESTAMP;
  FUNCTION to_utc(p_ts IN TIMESTAMP, p_src_tz IN VARCHAR2) RETURN TIMESTAMP;
  FUNCTION from_utc(p_ts IN TIMESTAMP, p_dst_tz IN VARCHAR2) RETURN TIMESTAMP;
  FUNCTION seconds_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER;
  FUNCTION subseconds_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER;
  FUNCTION minutes_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER;
  FUNCTION hours_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER;
  FUNCTION days_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER;
  FUNCTION epoch(p_ts IN TIMESTAMP) RETURN NUMBER;
  FUNCTION from_epoch(p_secs IN NUMBER) RETURN TIMESTAMP;
  FUNCTION format_iso(p_ts IN TIMESTAMP) RETURN VARCHAR2;
  FUNCTION parse_iso(p_s IN VARCHAR2) RETURN TIMESTAMP;
  FUNCTION add_days(p_ts IN TIMESTAMP, p_n IN NUMBER) RETURN TIMESTAMP;
  FUNCTION add_seconds(p_ts IN TIMESTAMP, p_n IN NUMBER) RETURN TIMESTAMP;
  FUNCTION add_months_to(p_ts IN TIMESTAMP, p_n IN NUMBER) RETURN TIMESTAMP;
  FUNCTION start_of_day(p_ts IN TIMESTAMP) RETURN TIMESTAMP;
  FUNCTION start_of_month(p_ts IN TIMESTAMP) RETURN TIMESTAMP;
  FUNCTION end_of_month(p_ts IN TIMESTAMP) RETURN TIMESTAMP;
  FUNCTION start_of_week(p_ts IN TIMESTAMP) RETURN TIMESTAMP;
  FUNCTION day_of_week(p_ts IN TIMESTAMP) RETURN NUMBER;
  FUNCTION day_name(p_ts IN TIMESTAMP) RETURN VARCHAR2;
  FUNCTION is_weekend(p_ts IN TIMESTAMP) RETURN BOOLEAN;
  FUNCTION year_of(p_ts IN TIMESTAMP) RETURN NUMBER;
  FUNCTION month_of(p_ts IN TIMESTAMP) RETURN NUMBER;
  FUNCTION day_of(p_ts IN TIMESTAMP) RETURN NUMBER;
  FUNCTION hour_of(p_ts IN TIMESTAMP) RETURN NUMBER;
  FUNCTION days_in_month(p_ts IN TIMESTAMP) RETURN NUMBER;
  FUNCTION is_leap_year(p_ts IN TIMESTAMP) RETURN BOOLEAN;
END datetime;
/

CREATE OR REPLACE PACKAGE BODY std.datetime AS

  -- Forward declarations (private fns; lets them be
  -- called before their definition in this body).
  FUNCTION cast_to_timestamp(p_d IN DATE) RETURN TIMESTAMP;

  FUNCTION now RETURN TIMESTAMP IS
  BEGIN
    RETURN systimestamp();
  END now;

  FUNCTION utc_now RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(sys_extract_utc(systimestamp) as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END utc_now;

  FUNCTION today RETURN TIMESTAMP IS
  BEGIN
    RETURN cast_to_timestamp(trunc(sysdate()));
  END today;

  FUNCTION cast_to_timestamp(p_d IN DATE) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(p_d as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END cast_to_timestamp;

  FUNCTION convert_tz(p_ts IN TIMESTAMP, p_src_tz IN VARCHAR2, p_dst_tz IN VARCHAR2) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(from_tz(p_ts, p_src_tz) at time zone p_dst_tz as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END convert_tz;

  FUNCTION to_utc(p_ts IN TIMESTAMP, p_src_tz IN VARCHAR2) RETURN TIMESTAMP IS
  BEGIN
    RETURN convert_tz(p_ts, p_src_tz, 'UTC');
  END to_utc;

  FUNCTION from_utc(p_ts IN TIMESTAMP, p_dst_tz IN VARCHAR2) RETURN TIMESTAMP IS
  BEGIN
    RETURN convert_tz(p_ts, 'UTC', p_dst_tz);
  END from_utc;

  FUNCTION seconds_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER IS
    l_d INTERVAL DAY(9) TO SECOND(9);
    l_exact NUMBER;
  BEGIN
    l_d := (p_b - p_a);
    l_exact := ((((EXTRACT(DAY FROM l_d) * 86400) + (EXTRACT(HOUR FROM l_d) * 3600)) + (EXTRACT(MINUTE FROM l_d) * 60)) + EXTRACT(SECOND FROM l_d));
    RETURN trunc(l_exact);
  END seconds_between;

  FUNCTION subseconds_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER IS
    l_d INTERVAL DAY(9) TO SECOND(9);
  BEGIN
    l_d := (p_b - p_a);
    RETURN ((((EXTRACT(DAY FROM l_d) * 86400) + (EXTRACT(HOUR FROM l_d) * 3600)) + (EXTRACT(MINUTE FROM l_d) * 60)) + EXTRACT(SECOND FROM l_d));
  END subseconds_between;

  FUNCTION minutes_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER IS
  BEGIN
    RETURN (seconds_between(p_a, p_b) / 60);
  END minutes_between;

  FUNCTION hours_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER IS
  BEGIN
    RETURN (seconds_between(p_a, p_b) / 3600);
  END hours_between;

  FUNCTION days_between(p_a IN TIMESTAMP, p_b IN TIMESTAMP) RETURN NUMBER IS
  BEGIN
    RETURN (seconds_between(p_a, p_b) / 86400);
  END days_between;

  FUNCTION epoch(p_ts IN TIMESTAMP) RETURN NUMBER IS
    l_origin TIMESTAMP;
  BEGIN
    BEGIN
      select cast(from_tz(timestamp '1970-01-01 00:00:00', 'UTC') as timestamp)
      INTO l_origin
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN seconds_between(l_origin, p_ts);
  END epoch;

  FUNCTION from_epoch(p_secs IN NUMBER) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(from_tz(timestamp '1970-01-01 00:00:00', 'UTC')
                    + numtodsinterval(p_secs, 'SECOND') as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END from_epoch;

  FUNCTION format_iso(p_ts IN TIMESTAMP) RETURN VARCHAR2 IS
  BEGIN
    RETURN to_char(p_ts, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"');
  END format_iso;

  FUNCTION parse_iso(p_s IN VARCHAR2) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(to_timestamp_tz(p_s, 'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM') as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END parse_iso;

  FUNCTION add_days(p_ts IN TIMESTAMP, p_n IN NUMBER) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast((cast(p_ts as date) + p_n) as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END add_days;

  FUNCTION add_seconds(p_ts IN TIMESTAMP, p_n IN NUMBER) RETURN TIMESTAMP IS
  BEGIN
    RETURN (p_ts + numtodsinterval(p_n, 'SECOND'));
  END add_seconds;

  FUNCTION add_months_to(p_ts IN TIMESTAMP, p_n IN NUMBER) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(add_months(cast(p_ts as date), p_n) as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END add_months_to;

  FUNCTION start_of_day(p_ts IN TIMESTAMP) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(trunc(cast(p_ts as date)) as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END start_of_day;

  FUNCTION start_of_month(p_ts IN TIMESTAMP) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(trunc(cast(p_ts as date), 'MM') as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END start_of_month;

  FUNCTION end_of_month(p_ts IN TIMESTAMP) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(trunc(last_day(cast(p_ts as date))) as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END end_of_month;

  FUNCTION start_of_week(p_ts IN TIMESTAMP) RETURN TIMESTAMP IS
    l_r TIMESTAMP;
  BEGIN
    BEGIN
      select cast(trunc(cast(p_ts as date), 'IW') as timestamp)
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END start_of_week;

  FUNCTION day_of_week(p_ts IN TIMESTAMP) RETURN NUMBER IS
    l_r NUMBER;
  BEGIN
    BEGIN
      select trunc(cast(p_ts as date)) - trunc(cast(p_ts as date), 'IW') + 1
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END day_of_week;

  FUNCTION day_name(p_ts IN TIMESTAMP) RETURN VARCHAR2 IS
    l_r VARCHAR2(4000);
  BEGIN
    BEGIN
      select to_char(cast(p_ts as date), 'fmDay', 'NLS_DATE_LANGUAGE=ENGLISH')
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END day_name;

  FUNCTION is_weekend(p_ts IN TIMESTAMP) RETURN BOOLEAN IS
  BEGIN
    RETURN (day_of_week(p_ts) >= 6);
  END is_weekend;

  FUNCTION year_of(p_ts IN TIMESTAMP) RETURN NUMBER IS
  BEGIN
    RETURN to_number(to_char(p_ts, 'YYYY'));
  END year_of;

  FUNCTION month_of(p_ts IN TIMESTAMP) RETURN NUMBER IS
  BEGIN
    RETURN to_number(to_char(p_ts, 'MM'));
  END month_of;

  FUNCTION day_of(p_ts IN TIMESTAMP) RETURN NUMBER IS
  BEGIN
    RETURN to_number(to_char(p_ts, 'DD'));
  END day_of;

  FUNCTION hour_of(p_ts IN TIMESTAMP) RETURN NUMBER IS
  BEGIN
    RETURN to_number(to_char(p_ts, 'HH24'));
  END hour_of;

  FUNCTION days_in_month(p_ts IN TIMESTAMP) RETURN NUMBER IS
    l_r NUMBER;
  BEGIN
    BEGIN
      select to_number(to_char(last_day(cast(p_ts as date)), 'DD'))
      INTO l_r
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END days_in_month;

  FUNCTION is_leap_year(p_ts IN TIMESTAMP) RETURN BOOLEAN IS
    l_feb_days NUMBER;
  BEGIN
    BEGIN
      select to_number(to_char(last_day(trunc(cast(p_ts as date), 'YYYY') + 31), 'DD'))
      INTO l_feb_days
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN (l_feb_days = 29);
  END is_leap_year;
END datetime;
/