-- ======================================================================
-- Generated by pell 0.0.1 from module text_utils
--   Source:     compiler/examples/24_strings.pell
--   SHA-256:    8bcb4a1ba7a002496684fbe358217bd864adfa00d46f77b3fc31d97d3cd78890
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     dual
-- ======================================================================

CREATE OR REPLACE PACKAGE text_utils AS
  TYPE t_text_list IS TABLE OF VARCHAR2(4000) INDEX BY PLS_INTEGER;
  FUNCTION len(p_s IN VARCHAR2) RETURN NUMBER;
  FUNCTION trim_ws(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION to_lower(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION to_upper(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION substring(p_s IN VARCHAR2, p_start IN NUMBER, p_length IN NUMBER) RETURN VARCHAR2;
  FUNCTION is_blank(p_s IN VARCHAR2) RETURN BOOLEAN;
  FUNCTION has(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN BOOLEAN;
  FUNCTION replace_all(p_s IN VARCHAR2, p_from_ IN VARCHAR2, p_to_ IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION left_pad(p_s IN VARCHAR2, p_width IN NUMBER, p_ch IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION right_pad(p_s IN VARCHAR2, p_width IN NUMBER, p_ch IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION split(p_s IN VARCHAR2, p_delim IN VARCHAR2) RETURN t_text_list;
  FUNCTION count_of(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN NUMBER;
  FUNCTION reversed(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION index_of(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN NUMBER;
  FUNCTION before(p_s IN VARCHAR2, p_sep IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION after(p_s IN VARCHAR2, p_sep IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION text_between(p_s IN VARCHAR2, p_open IN VARCHAR2, p_close IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION strip_prefix(p_s IN VARCHAR2, p_prefix IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION strip_suffix(p_s IN VARCHAR2, p_suffix IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION repeat_text(p_s IN VARCHAR2, p_n IN NUMBER) RETURN VARCHAR2;
  FUNCTION title_case(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION join(p_parts IN t_text_list, p_delim IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION ellipsize(p_s IN VARCHAR2, p_max_len IN NUMBER) RETURN VARCHAR2;
  FUNCTION squish(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION camel_to_snake(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION snake_to_camel(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION default_if_blank(p_s IN VARCHAR2, p_dflt IN VARCHAR2) RETURN VARCHAR2;
END text_utils;
/

CREATE OR REPLACE PACKAGE BODY text_utils AS

  FUNCTION pell_split_text(p_s VARCHAR2, p_delim VARCHAR2) RETURN t_text_list IS
    l_result t_text_list;
    l_idx PLS_INTEGER := 0;
  BEGIN
    IF p_s IS NULL OR p_delim IS NULL THEN RETURN l_result; END IF;
    FOR rec IN (
      SELECT REGEXP_SUBSTR(p_s, '[^' || p_delim || ']+', 1, LEVEL) AS part
      FROM dual
      CONNECT BY LEVEL <= REGEXP_COUNT(p_s, p_delim) + 1
    ) LOOP
      IF rec.part IS NOT NULL THEN
        l_idx := l_idx + 1;
        l_result(l_idx) := rec.part;
      END IF;
    END LOOP;
    RETURN l_result;
  END pell_split_text;

  FUNCTION len(p_s IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    RETURN length(p_s);
  END len;

  FUNCTION trim_ws(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ltrim(rtrim(p_s));
  END trim_ws;

  FUNCTION to_lower(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN lower(p_s);
  END to_lower;

  FUNCTION to_upper(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN upper(p_s);
  END to_upper;

  FUNCTION substring(p_s IN VARCHAR2, p_start IN NUMBER, p_length IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN substr(p_s, p_start, p_length);
  END substring;

  FUNCTION is_blank(p_s IN VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN ((p_s IS NULL OR LENGTH(p_s) = 0) OR (trim_ws(p_s) IS NULL OR LENGTH(trim_ws(p_s)) = 0));
  END is_blank;

  FUNCTION has(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN (INSTR(p_haystack, p_needle) > 0);
  END has;

  FUNCTION replace_all(p_s IN VARCHAR2, p_from_ IN VARCHAR2, p_to_ IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN replace(p_s, p_from_, p_to_);
  END replace_all;

  FUNCTION left_pad(p_s IN VARCHAR2, p_width IN NUMBER, p_ch IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN lpad(p_s, p_width, p_ch);
  END left_pad;

  FUNCTION right_pad(p_s IN VARCHAR2, p_width IN NUMBER, p_ch IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN rpad(p_s, p_width, p_ch);
  END right_pad;

  FUNCTION split(p_s IN VARCHAR2, p_delim IN VARCHAR2) RETURN t_text_list IS
    l_parts t_text_list;
  BEGIN
    l_parts := pell_split_text(p_s, p_delim);
    RETURN l_parts;
  END split;

  FUNCTION count_of(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN NUMBER IS
    l_n NUMBER;
  BEGIN
    BEGIN
      select regexp_count(p_haystack, p_needle)
      INTO l_n
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_n;
  END count_of;

  FUNCTION reversed(p_s IN VARCHAR2) RETURN VARCHAR2 IS
    l_pell_ret_1 VARCHAR2(4000);
  BEGIN
    BEGIN
      select reverse(p_s)
      INTO l_pell_ret_1
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_pell_ret_1;
  END reversed;

  FUNCTION index_of(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    RETURN nvl(instr(p_haystack, p_needle), 0);
  END index_of;

  FUNCTION before(p_s IN VARCHAR2, p_sep IN VARCHAR2) RETURN VARCHAR2 IS
    l_i NUMBER;
  BEGIN
    l_i := nvl(instr(p_s, p_sep), 0);
    IF (l_i = 0) THEN
      RETURN p_s;
    END IF;
    RETURN substr(p_s, 1, (l_i - 1));
  END before;

  FUNCTION after(p_s IN VARCHAR2, p_sep IN VARCHAR2) RETURN VARCHAR2 IS
    l_i NUMBER;
  BEGIN
    l_i := nvl(instr(p_s, p_sep), 0);
    IF (l_i = 0) THEN
      RETURN '';
    END IF;
    RETURN substr(p_s, (l_i + length(p_sep)));
  END after;

  FUNCTION text_between(p_s IN VARCHAR2, p_open IN VARCHAR2, p_close IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN before(after(p_s, p_open), p_close);
  END text_between;

  FUNCTION strip_prefix(p_s IN VARCHAR2, p_prefix IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF (p_s LIKE p_prefix || '%') THEN
      RETURN substr(p_s, (length(p_prefix) + 1));
    END IF;
    RETURN p_s;
  END strip_prefix;

  FUNCTION strip_suffix(p_s IN VARCHAR2, p_suffix IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF (p_s LIKE '%' || p_suffix) THEN
      RETURN substr(p_s, 1, (length(p_s) - length(p_suffix)));
    END IF;
    RETURN p_s;
  END strip_suffix;

  FUNCTION repeat_text(p_s IN VARCHAR2, p_n IN NUMBER) RETURN VARCHAR2 IS
    l_acc VARCHAR2(4000);
  BEGIN
    l_acc := '';
    FOR i IN 1 .. p_n LOOP
      l_acc := (l_acc || p_s);
    END LOOP;
    RETURN l_acc;
  END repeat_text;

  FUNCTION title_case(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN initcap(p_s);
  END title_case;

  FUNCTION join(p_parts IN t_text_list, p_delim IN VARCHAR2) RETURN VARCHAR2 IS
    l_acc VARCHAR2(4000);
    l_seen NUMBER;
    i_part PLS_INTEGER;
    l_part_iter VARCHAR2(4000);
  BEGIN
    l_acc := '';
    l_seen := 0;
    i_part := p_parts.FIRST;
    WHILE i_part IS NOT NULL LOOP
      l_part_iter := p_parts(i_part);
      IF (l_seen > 0) THEN
        l_acc := (l_acc || p_delim);
      END IF;
      l_acc := (l_acc || l_part_iter);
      l_seen := (l_seen + 1);
      i_part := p_parts.NEXT(i_part);
    END LOOP;
    RETURN l_acc;
  END join;

  FUNCTION ellipsize(p_s IN VARCHAR2, p_max_len IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    IF (nvl(length(p_s), 0) <= p_max_len) THEN
      RETURN p_s;
    END IF;
    RETURN (substr(p_s, 1, (p_max_len - 3)) || '...');
  END ellipsize;

  FUNCTION squish(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN trim_ws(regexp_replace(p_s, '\s+', ' '));
  END squish;

  FUNCTION camel_to_snake(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN lower(regexp_replace(p_s, '([a-z0-9])([A-Z])', '\1_\2'));
  END camel_to_snake;

  FUNCTION snake_to_camel(p_s IN VARCHAR2) RETURN VARCHAR2 IS
    l_parts t_text_list;
    l_acc VARCHAR2(4000);
    i_part PLS_INTEGER;
    l_part_iter VARCHAR2(4000);
  BEGIN
    l_parts := pell_split_text(p_s, '_');
    l_acc := '';
    i_part := l_parts.FIRST;
    WHILE i_part IS NOT NULL LOOP
      l_part_iter := l_parts(i_part);
      l_acc := (l_acc || initcap(l_part_iter));
      i_part := l_parts.NEXT(i_part);
    END LOOP;
    RETURN l_acc;
  END snake_to_camel;

  FUNCTION default_if_blank(p_s IN VARCHAR2, p_dflt IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF is_blank(p_s) THEN
      RETURN p_dflt;
    END IF;
    RETURN p_s;
  END default_if_blank;
END text_utils;
/