-- ======================================================================
-- Generated by pell 0.0.1 from module text_utils
--   Source:     compiler/examples/24_strings.pell
--   SHA-256:    087fe78479c0db2e2f2b32f841a94ae0f84fa717c17e676262ad0311fe348f17
--   pell git:   05345b4
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     dual
-- ======================================================================

CREATE OR REPLACE PACKAGE text_utils AS
  TYPE t_text_list IS TABLE OF VARCHAR2(4000) INDEX BY PLS_INTEGER;
  FUNCTION len(p_s IN VARCHAR2) RETURN NUMBER;
  FUNCTION trim_ws(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION to_lower(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION to_upper(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION substring(p_s IN VARCHAR2, p_start IN NUMBER, p_length IN NUMBER) RETURN VARCHAR2;
  FUNCTION is_blank(p_s IN VARCHAR2) RETURN BOOLEAN;
  FUNCTION has(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN BOOLEAN;
  FUNCTION replace_all(p_s IN VARCHAR2, p_from_ IN VARCHAR2, p_to_ IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION left_pad(p_s IN VARCHAR2, p_width IN NUMBER, p_ch IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION right_pad(p_s IN VARCHAR2, p_width IN NUMBER, p_ch IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION split(p_s IN VARCHAR2, p_delim IN VARCHAR2) RETURN t_text_list;
  FUNCTION count_of(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN NUMBER;
  FUNCTION reversed(p_s IN VARCHAR2) RETURN VARCHAR2;
END text_utils;
/

CREATE OR REPLACE PACKAGE BODY text_utils AS

  FUNCTION pell_split_text(p_s VARCHAR2, p_delim VARCHAR2) RETURN t_text_list IS
    l_result t_text_list;
    l_idx PLS_INTEGER := 0;
  BEGIN
    IF p_s IS NULL OR p_delim IS NULL THEN RETURN l_result; END IF;
    FOR rec IN (
      SELECT REGEXP_SUBSTR(p_s, '[^' || p_delim || ']+', 1, LEVEL) AS part
      FROM dual
      CONNECT BY LEVEL <= REGEXP_COUNT(p_s, p_delim) + 1
    ) LOOP
      IF rec.part IS NOT NULL THEN
        l_idx := l_idx + 1;
        l_result(l_idx) := rec.part;
      END IF;
    END LOOP;
    RETURN l_result;
  END pell_split_text;

  FUNCTION len(p_s IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    RETURN length(p_s);
  END len;

  FUNCTION trim_ws(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ltrim(rtrim(p_s));
  END trim_ws;

  FUNCTION to_lower(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN lower(p_s);
  END to_lower;

  FUNCTION to_upper(p_s IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN upper(p_s);
  END to_upper;

  FUNCTION substring(p_s IN VARCHAR2, p_start IN NUMBER, p_length IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN substr(p_s, p_start, p_length);
  END substring;

  FUNCTION is_blank(p_s IN VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN ((p_s IS NULL OR LENGTH(p_s) = 0) OR (trim_ws(p_s) IS NULL OR LENGTH(trim_ws(p_s)) = 0));
  END is_blank;

  FUNCTION has(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN (INSTR(p_haystack, p_needle) > 0);
  END has;

  FUNCTION replace_all(p_s IN VARCHAR2, p_from_ IN VARCHAR2, p_to_ IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN replace(p_s, p_from_, p_to_);
  END replace_all;

  FUNCTION left_pad(p_s IN VARCHAR2, p_width IN NUMBER, p_ch IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN lpad(p_s, p_width, p_ch);
  END left_pad;

  FUNCTION right_pad(p_s IN VARCHAR2, p_width IN NUMBER, p_ch IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN rpad(p_s, p_width, p_ch);
  END right_pad;

  FUNCTION split(p_s IN VARCHAR2, p_delim IN VARCHAR2) RETURN t_text_list IS
    l_parts t_text_list;
  BEGIN
    l_parts := pell_split_text(p_s, p_delim);
    RETURN l_parts;
  END split;

  FUNCTION count_of(p_haystack IN VARCHAR2, p_needle IN VARCHAR2) RETURN NUMBER IS
    l_n NUMBER;
  BEGIN
    BEGIN
      select regexp_count(p_haystack, p_needle)
      INTO l_n
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_n;
  END count_of;

  FUNCTION reversed(p_s IN VARCHAR2) RETURN VARCHAR2 IS
    l_pell_ret_1 VARCHAR2(4000);
  BEGIN
    BEGIN
      select reverse(p_s)
      INTO l_pell_ret_1
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_pell_ret_1;
  END reversed;
END text_utils;
/