-- ======================================================================
-- Generated by pell 0.0.1 from module validation
--   Source:     compiler/examples/25_validation.pell
--   SHA-256:    a737d149d8c1644c29ec606be0dfad979dfa6e7dbc8a8f967a375b0c3ce6f89a
--   pell git:   dd6ae26
--   Target:     Oracle 23
--   Schema:     signups
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     dual
--   packages:
--     pell_runtime
-- ======================================================================

-- Additions to pell_runtime for module validation:
--   (collate these into a single CREATE OR REPLACE PACKAGE pell_runtime)
--   signups_validation_missingfield EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validation_missingfield, -20100);
--   signups_validation_invalidemail EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validation_invalidemail, -20101);
--   signups_validation_ageoutofrange EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validation_ageoutofrange, -20102);
--   signups_validation_tooshort EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validation_tooshort, -20103);
--   signups_validation_toolong EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validation_toolong, -20104);
--   signups_validation_outofrange EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validation_outofrange, -20105);
--   signups_validation_patternmismatch EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validation_patternmismatch, -20106);
--   signups_validation_notoneof EXCEPTION;  -- propagate
--   PRAGMA EXCEPTION_INIT(signups_validation_notoneof, -20107);

CREATE OR REPLACE PACKAGE signups.validation AS
  TYPE t_signupform IS RECORD (
    name VARCHAR2(4000),
    email VARCHAR2(4000),
    age NUMBER
  );
  FUNCTION require_text(p_field IN VARCHAR2, p_value IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION require_email(p_value IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION require_age(p_value IN NUMBER) RETURN NUMBER;
  FUNCTION require_min_length(p_field IN VARCHAR2, p_value IN VARCHAR2, p_min_len IN NUMBER) RETURN VARCHAR2;
  FUNCTION require_max_length(p_field IN VARCHAR2, p_value IN VARCHAR2, p_max_len IN NUMBER) RETURN VARCHAR2;
  FUNCTION require_in_range(p_field IN VARCHAR2, p_value IN NUMBER, p_min IN NUMBER, p_max IN NUMBER) RETURN NUMBER;
  FUNCTION require_pattern(p_field IN VARCHAR2, p_value IN VARCHAR2, p_pattern IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION require_one_of(p_field IN VARCHAR2, p_value IN VARCHAR2, p_allowed IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION validate_signup(p_form IN t_signupform) RETURN t_signupform;
END validation;
/

CREATE OR REPLACE PACKAGE BODY signups.validation AS

  -- Forward declarations (private fns; lets them be
  -- called before their definition in this body).
  FUNCTION get_name(p_form IN t_signupform) RETURN VARCHAR2;

  FUNCTION require_text(p_field IN VARCHAR2, p_value IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF (p_value IS NULL OR LENGTH(p_value) = 0) THEN
      pell_runtime.set_err('signups_validation_missingfield:1', JSON_OBJECT('field' VALUE p_field));
      RAISE pell_runtime.signups_validation_missingfield;
    END IF;
    RETURN p_value;
  END require_text;

  FUNCTION require_email(p_value IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF (p_value IS NULL OR LENGTH(p_value) = 0) THEN
      pell_runtime.set_err('signups_validation_invalidemail:1', JSON_OBJECT('value' VALUE p_value, 'reason' VALUE 'empty'));
      RAISE pell_runtime.signups_validation_invalidemail;
    END IF;
    IF ((INSTR(p_value, '@') > 0) = FALSE) THEN
      pell_runtime.set_err('signups_validation_invalidemail:1', JSON_OBJECT('value' VALUE p_value, 'reason' VALUE 'no @'));
      RAISE pell_runtime.signups_validation_invalidemail;
    END IF;
    IF ((p_value LIKE '%' || '.') OR (p_value LIKE '.' || '%')) THEN
      pell_runtime.set_err('signups_validation_invalidemail:1', JSON_OBJECT('value' VALUE p_value, 'reason' VALUE 'leading/trailing dot'));
      RAISE pell_runtime.signups_validation_invalidemail;
    END IF;
    RETURN p_value;
  END require_email;

  FUNCTION require_age(p_value IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF ((p_value < 13) OR (p_value > 120)) THEN
      pell_runtime.set_err('signups_validation_ageoutofrange:1', JSON_OBJECT('value' VALUE p_value, 'min' VALUE 13, 'max' VALUE 120));
      RAISE pell_runtime.signups_validation_ageoutofrange;
    END IF;
    RETURN p_value;
  END require_age;

  FUNCTION require_min_length(p_field IN VARCHAR2, p_value IN VARCHAR2, p_min_len IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    IF (nvl(length(p_value), 0) < p_min_len) THEN
      pell_runtime.set_err('signups_validation_tooshort:1', JSON_OBJECT('field' VALUE p_field, 'min_len' VALUE p_min_len));
      RAISE pell_runtime.signups_validation_tooshort;
    END IF;
    RETURN p_value;
  END require_min_length;

  FUNCTION require_max_length(p_field IN VARCHAR2, p_value IN VARCHAR2, p_max_len IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    IF (nvl(length(p_value), 0) > p_max_len) THEN
      pell_runtime.set_err('signups_validation_toolong:1', JSON_OBJECT('field' VALUE p_field, 'max_len' VALUE p_max_len));
      RAISE pell_runtime.signups_validation_toolong;
    END IF;
    RETURN p_value;
  END require_max_length;

  FUNCTION require_in_range(p_field IN VARCHAR2, p_value IN NUMBER, p_min IN NUMBER, p_max IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF ((p_value < p_min) OR (p_value > p_max)) THEN
      pell_runtime.set_err('signups_validation_outofrange:1', JSON_OBJECT('field' VALUE p_field, 'value' VALUE p_value, 'min' VALUE p_min, 'max' VALUE p_max));
      RAISE pell_runtime.signups_validation_outofrange;
    END IF;
    RETURN p_value;
  END require_in_range;

  FUNCTION require_pattern(p_field IN VARCHAR2, p_value IN VARCHAR2, p_pattern IN VARCHAR2) RETURN VARCHAR2 IS
    l_matched NUMBER;
  BEGIN
    BEGIN
      select case when regexp_like(p_value, p_pattern) then 1 else 0 end
      INTO l_matched
      FROM dual;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    IF (l_matched = 0) THEN
      pell_runtime.set_err('signups_validation_patternmismatch:1', JSON_OBJECT('field' VALUE p_field, 'value' VALUE p_value, 'pattern' VALUE p_pattern));
      RAISE pell_runtime.signups_validation_patternmismatch;
    END IF;
    RETURN p_value;
  END require_pattern;

  FUNCTION require_one_of(p_field IN VARCHAR2, p_value IN VARCHAR2, p_allowed IN VARCHAR2) RETURN VARCHAR2 IS
    l_padded VARCHAR2(4000);
  BEGIN
    l_padded := ((',' || p_allowed) || ',');
    IF ((INSTR(l_padded, ((',' || p_value) || ',')) > 0) = FALSE) THEN
      pell_runtime.set_err('signups_validation_notoneof:1', JSON_OBJECT('field' VALUE p_field, 'value' VALUE p_value, 'allowed' VALUE p_allowed));
      RAISE pell_runtime.signups_validation_notoneof;
    END IF;
    RETURN p_value;
  END require_one_of;

  FUNCTION validate_signup(p_form IN t_signupform) RETURN t_signupform IS
    l_name VARCHAR2(4000);
    l_email VARCHAR2(4000);
    l_age NUMBER;
    l_ret_1 t_signupform;
  BEGIN
    l_name := get_name(p_form);
    l_email := require_email(p_form.email);
    l_age := require_age(p_form.age);
    l_ret_1.name := l_name;
    l_ret_1.email := l_email;
    l_ret_1.age := l_age;
    RETURN l_ret_1;
  END validate_signup;

  FUNCTION get_name(p_form IN t_signupform) RETURN VARCHAR2 IS
  BEGIN
    RETURN require_text('name', p_form.name);
  END get_name;
END validation;
/