-- ======================================================================
-- Generated by pell 0.0.1 from module orders.paging
--   Source:     compiler/examples/26_pagination.pell
--   SHA-256:    79d1cb369c37bc9965c1631e9fa5d6d4213f3565908509e3bda5e48300c112f3
--   pell git:   3088760
--   Target:     Oracle 23
--   Schema:     orders
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     orders
-- ======================================================================

CREATE OR REPLACE PACKAGE orders.paging AS
  TYPE t_order IS RECORD (
    id NUMBER,
    customer_id NUMBER,
    status VARCHAR2(4000),
    total NUMBER
  );
  TYPE t_Order_list IS TABLE OF t_order INDEX BY PLS_INTEGER;
  FUNCTION page_of(p_status IN VARCHAR2, p_page_number IN NUMBER, p_page_size IN NUMBER) RETURN t_Order_list;
  FUNCTION count_matching(p_status IN VARCHAR2) RETURN NUMBER;
  FUNCTION page_count(p_total IN NUMBER, p_page_size IN NUMBER) RETURN NUMBER;
  FUNCTION has_next_page(p_page_number IN NUMBER, p_page_size IN NUMBER, p_total IN NUMBER) RETURN BOOLEAN;
END paging;
/

CREATE OR REPLACE PACKAGE BODY orders.paging AS

  FUNCTION page_of(p_status IN VARCHAR2, p_page_number IN NUMBER, p_page_size IN NUMBER) RETURN t_Order_list IS
    l_offset_rows NUMBER;
    l_rows t_Order_list;
  BEGIN
    l_offset_rows := ((p_page_number - 1) * p_page_size);
    select id, customer_id, status, total
      BULK COLLECT INTO l_rows
      FROM orders
        where (status = p_status or p_status is null)
        order by id
        offset l_offset_rows rows fetch next p_page_size rows only;
    RETURN l_rows;
  END page_of;

  FUNCTION count_matching(p_status IN VARCHAR2) RETURN NUMBER IS
    l_n NUMBER;
  BEGIN
    BEGIN
      select count(*)
      INTO l_n
      FROM orders
        where (status = p_status or p_status is null);
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_n;
  END count_matching;

  FUNCTION page_count(p_total IN NUMBER, p_page_size IN NUMBER) RETURN NUMBER IS
  BEGIN
    IF (p_total = 0) THEN
      RETURN 0;
    END IF;
    RETURN ceil((p_total / p_page_size));
  END page_count;

  FUNCTION has_next_page(p_page_number IN NUMBER, p_page_size IN NUMBER, p_total IN NUMBER) RETURN BOOLEAN IS
  BEGIN
    RETURN ((p_page_number * p_page_size) < p_total);
  END has_next_page;
END paging;
/