-- ======================================================================
-- Generated by pell 0.0.1 from module csv
--   Source:     compiler/examples/27_csv.pell
--   SHA-256:    633b607d78f2e8ab62a9d051144ec7fa68c94829016a68e067d434b492382947
--   pell git:   dd8ab63
--   Target:     Oracle 23
--   Schema:     data
-- DO NOT EDIT — regenerate with `pell build`
-- ======================================================================

CREATE OR REPLACE PACKAGE data.csv AS
  TYPE t_text_list IS TABLE OF VARCHAR2(4000) INDEX BY PLS_INTEGER;
  FUNCTION parse_line(p_line IN VARCHAR2) RETURN t_text_list;
  FUNCTION parse(p_doc IN VARCHAR2) RETURN JSON;
  FUNCTION row_count(p_p IN JSON) RETURN NUMBER;
  FUNCTION col_count(p_p IN JSON, p_r IN NUMBER) RETURN NUMBER;
  FUNCTION cell(p_p IN JSON, p_r IN NUMBER, p_c IN NUMBER) RETURN VARCHAR2;
  FUNCTION parse_with_header(p_doc IN VARCHAR2) RETURN JSON;
  FUNCTION field(p_p IN JSON, p_r IN NUMBER, p_key IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION quote_field(p_s IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION to_line(p_cells IN t_text_list) RETURN VARCHAR2;
  FUNCTION to_csv(p_p IN JSON) RETURN VARCHAR2;
END csv;
/

CREATE OR REPLACE PACKAGE BODY data.csv AS

  FUNCTION parse_line(p_line IN VARCHAR2) RETURN t_text_list IS
    l_cells t_text_list;
    l_cur VARCHAR2(4000);
    l_in_quotes BOOLEAN;
    l_skip NUMBER;
    l_n NUMBER;
    l_ch VARCHAR2(4000);
  BEGIN
    l_cur := '';
    l_in_quotes := FALSE;
    l_skip := 0;
    l_n := nvl(length(p_line), 0);
    FOR idx IN 1 .. l_n LOOP
      IF (l_skip > 0) THEN
        l_skip := (l_skip - 1);
      ELSE
        l_ch := substr(p_line, idx, 1);
        IF l_in_quotes THEN
          IF (l_ch = '"') THEN
            IF ((idx < l_n) AND (substr(p_line, (idx + 1), 1) = '"')) THEN
              l_cur := (l_cur || '"');
              l_skip := 1;
            ELSE
              l_in_quotes := FALSE;
            END IF;
          ELSE
            l_cur := (l_cur || l_ch);
          END IF;
        ELSE
          IF (l_ch = '"') THEN
            l_in_quotes := TRUE;
          ELSE
            IF (l_ch = ',') THEN
              l_cells(l_cells.COUNT + 1) := l_cur;
              l_cur := '';
            ELSE
              l_cur := (l_cur || l_ch);
            END IF;
          END IF;
        END IF;
      END IF;
    END LOOP;
    l_cells(l_cells.COUNT + 1) := l_cur;
    RETURN l_cells;
  END parse_line;

  FUNCTION parse(p_doc IN VARCHAR2) RETURN JSON IS
    l_acc JSON;
    l_row JSON;
    l_cur VARCHAR2(4000);
    l_in_quotes BOOLEAN;
    l_pending BOOLEAN;
    l_nrows NUMBER;
    l_ncells NUMBER;
    l_skip NUMBER;
    l_n NUMBER;
    l_ch VARCHAR2(4000);
    l_pell_jobj_0 JSON_OBJECT_T;
    l_pell_jarr_1 JSON_ARRAY_T;
    l_pell_jobj_2 JSON_OBJECT_T;
    l_pell_jarr_3 JSON_ARRAY_T;
    l_pell_jobj_4 JSON_OBJECT_T;
    l_pell_jarr_5 JSON_ARRAY_T;
    l_pell_jobj_6 JSON_OBJECT_T;
    l_pell_jarr_7 JSON_ARRAY_T;
    l_pell_jobj_8 JSON_OBJECT_T;
    l_pell_jarr_9 JSON_ARRAY_T;
    l_done JSON;
    l_pell_jobj_10 JSON_OBJECT_T;
  BEGIN
    l_acc := JSON_OBJECT(RETURNING JSON);
    l_row := JSON_OBJECT(RETURNING JSON);
    l_cur := '';
    l_in_quotes := FALSE;
    l_pending := FALSE;
    l_nrows := 0;
    l_ncells := 0;
    l_skip := 0;
    l_n := nvl(length(p_doc), 0);
    FOR idx IN 1 .. l_n LOOP
      IF (l_skip > 0) THEN
        l_skip := (l_skip - 1);
      ELSE
        l_ch := substr(p_doc, idx, 1);
        IF l_in_quotes THEN
          IF (l_ch = '"') THEN
            IF ((idx < l_n) AND (substr(p_doc, (idx + 1), 1) = '"')) THEN
              l_cur := (l_cur || '"');
              l_skip := 1;
            ELSE
              l_in_quotes := FALSE;
            END IF;
          ELSE
            l_cur := (l_cur || l_ch);
          END IF;
        ELSE
          IF (l_ch = '"') THEN
            l_in_quotes := TRUE;
            l_pending := TRUE;
          ELSE
            IF (l_ch = ',') THEN
              l_pell_jobj_0 := JSON_OBJECT_T(l_row);
              IF l_pell_jobj_0.has('c') THEN
                l_pell_jarr_1 := l_pell_jobj_0.get_array('c');
              ELSE
                l_pell_jarr_1 := JSON_ARRAY_T();
              END IF;
              l_pell_jarr_1.append(l_cur);
              l_pell_jobj_0.put('c', l_pell_jarr_1);
              l_row := l_pell_jobj_0.to_json();
              l_ncells := (l_ncells + 1);
              l_cur := '';
              l_pending := TRUE;
            ELSE
              IF ((l_ch = '') OR (l_ch = '
')) THEN
                IF (((l_ch = '') AND (idx < l_n)) AND (substr(p_doc, (idx + 1), 1) = '
')) THEN
                  l_skip := 1;
                END IF;
                IF l_pending THEN
                  l_pell_jobj_2 := JSON_OBJECT_T(l_row);
                  IF l_pell_jobj_2.has('c') THEN
                    l_pell_jarr_3 := l_pell_jobj_2.get_array('c');
                  ELSE
                    l_pell_jarr_3 := JSON_ARRAY_T();
                  END IF;
                  l_pell_jarr_3.append(l_cur);
                  l_pell_jobj_2.put('c', l_pell_jarr_3);
                  l_pell_jobj_2.put('w', (l_ncells + 1));
                  l_row := l_pell_jobj_2.to_json();
                  l_pell_jobj_4 := JSON_OBJECT_T(l_acc);
                  IF l_pell_jobj_4.has('rows') THEN
                    l_pell_jarr_5 := l_pell_jobj_4.get_array('rows');
                  ELSE
                    l_pell_jarr_5 := JSON_ARRAY_T();
                  END IF;
                  l_pell_jarr_5.append(l_row);
                  l_pell_jobj_4.put('rows', l_pell_jarr_5);
                  l_acc := l_pell_jobj_4.to_json();
                  l_nrows := (l_nrows + 1);
                END IF;
                l_row := JSON_OBJECT(RETURNING JSON);
                l_cur := '';
                l_ncells := 0;
                l_pending := FALSE;
              ELSE
                l_cur := (l_cur || l_ch);
                l_pending := TRUE;
              END IF;
            END IF;
          END IF;
        END IF;
      END IF;
    END LOOP;
    IF l_pending THEN
      l_pell_jobj_6 := JSON_OBJECT_T(l_row);
      IF l_pell_jobj_6.has('c') THEN
        l_pell_jarr_7 := l_pell_jobj_6.get_array('c');
      ELSE
        l_pell_jarr_7 := JSON_ARRAY_T();
      END IF;
      l_pell_jarr_7.append(l_cur);
      l_pell_jobj_6.put('c', l_pell_jarr_7);
      l_pell_jobj_6.put('w', (l_ncells + 1));
      l_row := l_pell_jobj_6.to_json();
      l_pell_jobj_8 := JSON_OBJECT_T(l_acc);
      IF l_pell_jobj_8.has('rows') THEN
        l_pell_jarr_9 := l_pell_jobj_8.get_array('rows');
      ELSE
        l_pell_jarr_9 := JSON_ARRAY_T();
      END IF;
      l_pell_jarr_9.append(l_row);
      l_pell_jobj_8.put('rows', l_pell_jarr_9);
      l_acc := l_pell_jobj_8.to_json();
      l_nrows := (l_nrows + 1);
    END IF;
    l_pell_jobj_10 := JSON_OBJECT_T(l_acc);
    l_pell_jobj_10.put('n', l_nrows);
    l_done := l_pell_jobj_10.to_json();
    RETURN l_done;
  END parse;

  FUNCTION row_count(p_p IN JSON) RETURN NUMBER IS
  BEGIN
    RETURN nvl(JSON_VALUE(p_p, '$.n' RETURNING NUMBER), 0);
  END row_count;

  FUNCTION col_count(p_p IN JSON, p_r IN NUMBER) RETURN NUMBER IS
    l_path VARCHAR2(4000);
  BEGIN
    l_path := (('$.rows[' || TO_CHAR((p_r - 1))) || '].w');
    RETURN nvl(JSON_VALUE(p_p, l_path RETURNING NUMBER), 0);
  END col_count;

  FUNCTION cell(p_p IN JSON, p_r IN NUMBER, p_c IN NUMBER) RETURN VARCHAR2 IS
    l_path VARCHAR2(4000);
  BEGIN
    l_path := (((('$.rows[' || TO_CHAR((p_r - 1))) || '].c[') || TO_CHAR((p_c - 1))) || ']');
    RETURN JSON_VALUE(p_p, l_path);
  END cell;

  FUNCTION parse_with_header(p_doc IN VARCHAR2) RETURN JSON IS
    l_raw JSON;
    l_total NUMBER;
    l_acc JSON;
    l_nrows NUMBER;
    l_ncols NUMBER;
    l_obj JSON;
    l_key VARCHAR2(4000);
    l_pell_jobj_0 JSON_OBJECT_T;
    l_pell_jobj_1 JSON_OBJECT_T;
    l_pell_jarr_2 JSON_ARRAY_T;
    l_done JSON;
    l_pell_jobj_3 JSON_OBJECT_T;
  BEGIN
    l_raw := parse(p_doc);
    l_total := row_count(l_raw);
    l_acc := JSON_OBJECT(RETURNING JSON);
    l_nrows := 0;
    IF (l_total >= 1) THEN
      l_ncols := col_count(l_raw, 1);
      FOR r IN 2 .. l_total LOOP
        l_obj := JSON_OBJECT(RETURNING JSON);
        FOR c IN 1 .. l_ncols LOOP
          l_key := cell(l_raw, 1, c);
          l_pell_jobj_0 := JSON_OBJECT_T(l_obj);
          l_pell_jobj_0.put(l_key, cell(l_raw, r, c));
          l_obj := l_pell_jobj_0.to_json();
        END LOOP;
        l_pell_jobj_1 := JSON_OBJECT_T(l_acc);
        IF l_pell_jobj_1.has('rows') THEN
          l_pell_jarr_2 := l_pell_jobj_1.get_array('rows');
        ELSE
          l_pell_jarr_2 := JSON_ARRAY_T();
        END IF;
        l_pell_jarr_2.append(l_obj);
        l_pell_jobj_1.put('rows', l_pell_jarr_2);
        l_acc := l_pell_jobj_1.to_json();
        l_nrows := (l_nrows + 1);
      END LOOP;
    END IF;
    l_pell_jobj_3 := JSON_OBJECT_T(l_acc);
    l_pell_jobj_3.put('n', l_nrows);
    l_done := l_pell_jobj_3.to_json();
    RETURN l_done;
  END parse_with_header;

  FUNCTION field(p_p IN JSON, p_r IN NUMBER, p_key IN VARCHAR2) RETURN VARCHAR2 IS
    l_path VARCHAR2(4000);
  BEGIN
    l_path := ((('$.rows[' || TO_CHAR((p_r - 1))) || '].') || p_key);
    RETURN JSON_VALUE(p_p, l_path);
  END field;

  FUNCTION quote_field(p_s IN VARCHAR2) RETURN VARCHAR2 IS
    l_doubled VARCHAR2(4000);
  BEGIN
    IF (((INSTR(p_s, ',') > 0) OR (INSTR(p_s, '"') > 0)) OR (INSTR(p_s, '
') > 0)) THEN
      l_doubled := replace(p_s, '"', '""');
      RETURN ('"' || l_doubled || '"');
    END IF;
    RETURN p_s;
  END quote_field;

  FUNCTION to_line(p_cells IN t_text_list) RETURN VARCHAR2 IS
    l_line VARCHAR2(4000);
    l_seen NUMBER;
    i_c PLS_INTEGER;
    l_c_iter VARCHAR2(4000);
  BEGIN
    l_line := '';
    l_seen := 0;
    i_c := p_cells.FIRST;
    WHILE i_c IS NOT NULL LOOP
      l_c_iter := p_cells(i_c);
      IF (l_seen > 0) THEN
        l_line := (l_line || ',');
      END IF;
      l_line := (l_line || quote_field(nvl(l_c_iter, '')));
      l_seen := (l_seen + 1);
      i_c := p_cells.NEXT(i_c);
    END LOOP;
    RETURN l_line;
  END to_line;

  FUNCTION to_csv(p_p IN JSON) RETURN VARCHAR2 IS
    l_acc VARCHAR2(4000);
    l_nrows NUMBER;
    l_line VARCHAR2(4000);
    l_ncols NUMBER;
  BEGIN
    l_acc := '';
    l_nrows := row_count(p_p);
    FOR r IN 1 .. l_nrows LOOP
      l_line := '';
      l_ncols := col_count(p_p, r);
      FOR c IN 1 .. l_ncols LOOP
        IF (c > 1) THEN
          l_line := (l_line || ',');
        END IF;
        l_line := (l_line || quote_field(nvl(cell(p_p, r, c), '')));
      END LOOP;
      IF (r > 1) THEN
        l_acc := (l_acc || '
');
      END IF;
      l_acc := (l_acc || l_line);
    END LOOP;
    RETURN l_acc;
  END to_csv;
END csv;
/