-- ======================================================================
-- Generated by pell 0.0.1 from module repl_demo
--   Source:     compiler/examples/28_repl_demo.pell
--   SHA-256:    e9d60a71439b33940f741bc688c6b2e76bdff8843ef58c19e025a56d194a39e0
--   pell git:   0f8ffda
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   packages:
--     catalog
-- ======================================================================

CREATE OR REPLACE PACKAGE repl_demo AS
  TYPE t_employee IS RECORD (
    id NUMBER,
    name VARCHAR2(4000),
    level NUMBER
  );
  TYPE t_text_list IS TABLE OF VARCHAR2(4000) INDEX BY PLS_INTEGER;
  FUNCTION promote(p_e IN t_employee) RETURN t_employee;
  FUNCTION greet(p_name IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION audit_msg(p_action IN VARCHAR2, p_target IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION display_tables RETURN t_text_list;
  FUNCTION display_tree(p_name IN VARCHAR2) RETURN t_text_list;
  FUNCTION zxh(p_emp IN t_employee) RETURN VARCHAR2;
END repl_demo;
/

CREATE OR REPLACE PACKAGE BODY repl_demo AS

  FUNCTION promote(p_e IN t_employee) RETURN t_employee IS
    l_ret_1 t_employee;
  BEGIN
    l_ret_1.id := p_e.id;
    l_ret_1.name := p_e.name;
    l_ret_1.level := (p_e.level + 1);
    RETURN l_ret_1;
  END promote;

  FUNCTION greet(p_name IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ('hello, ' || p_name || '!');
  END greet;

  FUNCTION audit_msg(p_action IN VARCHAR2, p_target IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ('[' || sysdate() || '] action=' || p_action || ' target=' || p_target);
  END audit_msg;

  FUNCTION display_tables RETURN t_text_list IS
    l_pell_ret_1 t_text_list;
    l_pell_listadapter_1 catalog.t_text_list;
  BEGIN
    l_pell_listadapter_1 := catalog.list_tables();
    DECLARE
      l_i PLS_INTEGER;
    BEGIN
      l_i := l_pell_listadapter_1.FIRST;
      WHILE l_i IS NOT NULL LOOP
        l_pell_ret_1(l_i) := l_pell_listadapter_1(l_i);
        l_i := l_pell_listadapter_1.NEXT(l_i);
      END LOOP;
    END;
    RETURN l_pell_ret_1;
  END display_tables;

  FUNCTION display_tree(p_name IN VARCHAR2) RETURN t_text_list IS
    l_a t_text_list;
    l_pell_listadapter_0 catalog.t_text_list;
  BEGIN
    l_pell_listadapter_0 := catalog.list_tables();
    DECLARE
      l_i PLS_INTEGER;
    BEGIN
      l_i := l_pell_listadapter_0.FIRST;
      WHILE l_i IS NOT NULL LOOP
        l_a(l_i) := l_pell_listadapter_0(l_i);
        l_i := l_pell_listadapter_0.NEXT(l_i);
      END LOOP;
    END;
    RETURN l_a;
  END display_tree;

  FUNCTION zxh(p_emp IN t_employee) RETURN VARCHAR2 IS
    l__ t_text_list;
  BEGIN
    l__ := display_tables();
    RETURN ('hello, ' || p_emp.name || '!');
  END zxh;
END repl_demo;
/