-- ======================================================================
-- Generated by pell 0.0.1 from module dyn_demo
--   Source:     compiler/examples/29_dyn_cursor.pell
--   SHA-256:    61f6f042d7c71876c1c076f182d061b175aff4671548b3f528fe7c90c05812a7
--   pell git:   b3f4f0f
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     pivot_orders
-- ======================================================================

CREATE OR REPLACE PACKAGE dyn_demo AS
  FUNCTION region_sales RETURN SYS_REFCURSOR;
  PROCEDURE dump;
  PROCEDURE east_vs_west;
END dyn_demo;
/

CREATE OR REPLACE PACKAGE BODY dyn_demo AS

  -- Pinning declarations for dynamic-SQL @touches. Never invoked;
  -- exists so Oracle ALL_DEPENDENCIES tracks references hidden
  -- in EXECUTE IMMEDIATE strings.
  PROCEDURE pell_dep_pinning IS
    CURSOR pin_pivot_orders IS SELECT 1 FROM pivot_orders WHERE 1=0;
  BEGIN NULL; END pell_dep_pinning;

  FUNCTION region_sales RETURN SYS_REFCURSOR IS
    l_pell_pivot_cols VARCHAR2(4000);
    l_pell_pivot_sql  VARCHAR2(32767);
    l_pell_pivot_cur  SYS_REFCURSOR;
  BEGIN
    SELECT LISTAGG('''' || region || ''' AS "' || region || '"', ', ')
             WITHIN GROUP (ORDER BY region)
      INTO l_pell_pivot_cols
      FROM (SELECT DISTINCT region FROM (
    select product, region, sales from pivot_orders
      )) WHERE region IS NOT NULL;
    l_pell_pivot_sql :=
      'SELECT * FROM (' ||
      'select product, region, sales from pivot_orders' ||
      ') PIVOT (SUM(sales) FOR region IN (' ||
      l_pell_pivot_cols ||
      '))';
    OPEN l_pell_pivot_cur FOR l_pell_pivot_sql;
    RETURN l_pell_pivot_cur;
  END region_sales;

  PROCEDURE dump IS
    l_pell_cur_1 SYS_REFCURSOR;
    l_pell_dyn_cur_1 PLS_INTEGER;
    l_pell_col_cnt_1 PLS_INTEGER;
    l_pell_desc_1 DBMS_SQL.DESC_TAB;
    l_pell_idx_1 PLS_INTEGER;
    l_pell_row_1 JSON;
    l_pell_jobj_1 JSON_OBJECT_T;
    l_pell_buf_str_1 VARCHAR2(4000);
    l_pell_buf_num_1 NUMBER;
    l_pell_buf_dt_1 DATE;
    l_pell_buf_ts_1 TIMESTAMP;
    l_pell_col_name_1 VARCHAR2(128);
  BEGIN
    l_pell_cur_1 := region_sales();
    l_pell_dyn_cur_1 := DBMS_SQL.TO_CURSOR_NUMBER(l_pell_cur_1);
    DBMS_SQL.DESCRIBE_COLUMNS(l_pell_dyn_cur_1, l_pell_col_cnt_1, l_pell_desc_1);
    FOR l_pell_idx_1 IN 1 .. l_pell_col_cnt_1 LOOP
      IF l_pell_desc_1(l_pell_idx_1).col_type = 2 THEN
        DBMS_SQL.DEFINE_COLUMN(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_num_1);
      ELSIF l_pell_desc_1(l_pell_idx_1).col_type = 12 THEN
        DBMS_SQL.DEFINE_COLUMN(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_dt_1);
      ELSIF l_pell_desc_1(l_pell_idx_1).col_type IN (180, 181, 231) THEN
        DBMS_SQL.DEFINE_COLUMN(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_ts_1);
      ELSE
        DBMS_SQL.DEFINE_COLUMN(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_str_1, 4000);
      END IF;
    END LOOP;
    WHILE DBMS_SQL.FETCH_ROWS(l_pell_dyn_cur_1) > 0 LOOP
      l_pell_jobj_1 := NEW JSON_OBJECT_T();
      FOR l_pell_idx_1 IN 1 .. l_pell_col_cnt_1 LOOP
        l_pell_col_name_1 := l_pell_desc_1(l_pell_idx_1).col_name;
        IF l_pell_desc_1(l_pell_idx_1).col_type = 2 THEN
          DBMS_SQL.COLUMN_VALUE(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_num_1);
          IF l_pell_buf_num_1 IS NULL THEN l_pell_jobj_1.put_null(l_pell_col_name_1);
          ELSE l_pell_jobj_1.put(l_pell_col_name_1, l_pell_buf_num_1); END IF;
        ELSIF l_pell_desc_1(l_pell_idx_1).col_type = 12 THEN
          DBMS_SQL.COLUMN_VALUE(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_dt_1);
          IF l_pell_buf_dt_1 IS NULL THEN l_pell_jobj_1.put_null(l_pell_col_name_1);
          ELSE l_pell_jobj_1.put(l_pell_col_name_1, TO_CHAR(l_pell_buf_dt_1, 'YYYY-MM-DD"T"HH24:MI:SS')); END IF;
        ELSIF l_pell_desc_1(l_pell_idx_1).col_type IN (180, 181, 231) THEN
          DBMS_SQL.COLUMN_VALUE(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_ts_1);
          IF l_pell_buf_ts_1 IS NULL THEN l_pell_jobj_1.put_null(l_pell_col_name_1);
          ELSE l_pell_jobj_1.put(l_pell_col_name_1, TO_CHAR(l_pell_buf_ts_1, 'YYYY-MM-DD"T"HH24:MI:SS.FF6')); END IF;
        ELSE
          DBMS_SQL.COLUMN_VALUE(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_str_1);
          IF l_pell_buf_str_1 IS NULL THEN l_pell_jobj_1.put_null(l_pell_col_name_1);
          ELSE l_pell_jobj_1.put(l_pell_col_name_1, l_pell_buf_str_1); END IF;
        END IF;
      END LOOP;
      l_pell_row_1 := l_pell_jobj_1.to_json();
      dbms_output.put_line(JSON_SERIALIZE(l_pell_row_1));
    END LOOP;
    DBMS_SQL.CLOSE_CURSOR(l_pell_dyn_cur_1);
  END dump;

  PROCEDURE east_vs_west IS
    l_pell_cur_1 SYS_REFCURSOR;
    l_pell_dyn_cur_1 PLS_INTEGER;
    l_pell_col_cnt_1 PLS_INTEGER;
    l_pell_desc_1 DBMS_SQL.DESC_TAB;
    l_pell_idx_1 PLS_INTEGER;
    l_pell_row_1 JSON;
    l_pell_jobj_1 JSON_OBJECT_T;
    l_pell_buf_str_1 VARCHAR2(4000);
    l_pell_buf_num_1 NUMBER;
    l_pell_buf_dt_1 DATE;
    l_pell_buf_ts_1 TIMESTAMP;
    l_pell_col_name_1 VARCHAR2(128);
    l_product VARCHAR2(4000);
    l_east NUMBER;
    l_west NUMBER;
  BEGIN
    l_pell_cur_1 := region_sales();
    l_pell_dyn_cur_1 := DBMS_SQL.TO_CURSOR_NUMBER(l_pell_cur_1);
    DBMS_SQL.DESCRIBE_COLUMNS(l_pell_dyn_cur_1, l_pell_col_cnt_1, l_pell_desc_1);
    FOR l_pell_idx_1 IN 1 .. l_pell_col_cnt_1 LOOP
      IF l_pell_desc_1(l_pell_idx_1).col_type = 2 THEN
        DBMS_SQL.DEFINE_COLUMN(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_num_1);
      ELSIF l_pell_desc_1(l_pell_idx_1).col_type = 12 THEN
        DBMS_SQL.DEFINE_COLUMN(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_dt_1);
      ELSIF l_pell_desc_1(l_pell_idx_1).col_type IN (180, 181, 231) THEN
        DBMS_SQL.DEFINE_COLUMN(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_ts_1);
      ELSE
        DBMS_SQL.DEFINE_COLUMN(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_str_1, 4000);
      END IF;
    END LOOP;
    WHILE DBMS_SQL.FETCH_ROWS(l_pell_dyn_cur_1) > 0 LOOP
      l_pell_jobj_1 := NEW JSON_OBJECT_T();
      FOR l_pell_idx_1 IN 1 .. l_pell_col_cnt_1 LOOP
        l_pell_col_name_1 := l_pell_desc_1(l_pell_idx_1).col_name;
        IF l_pell_desc_1(l_pell_idx_1).col_type = 2 THEN
          DBMS_SQL.COLUMN_VALUE(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_num_1);
          IF l_pell_buf_num_1 IS NULL THEN l_pell_jobj_1.put_null(l_pell_col_name_1);
          ELSE l_pell_jobj_1.put(l_pell_col_name_1, l_pell_buf_num_1); END IF;
        ELSIF l_pell_desc_1(l_pell_idx_1).col_type = 12 THEN
          DBMS_SQL.COLUMN_VALUE(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_dt_1);
          IF l_pell_buf_dt_1 IS NULL THEN l_pell_jobj_1.put_null(l_pell_col_name_1);
          ELSE l_pell_jobj_1.put(l_pell_col_name_1, TO_CHAR(l_pell_buf_dt_1, 'YYYY-MM-DD"T"HH24:MI:SS')); END IF;
        ELSIF l_pell_desc_1(l_pell_idx_1).col_type IN (180, 181, 231) THEN
          DBMS_SQL.COLUMN_VALUE(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_ts_1);
          IF l_pell_buf_ts_1 IS NULL THEN l_pell_jobj_1.put_null(l_pell_col_name_1);
          ELSE l_pell_jobj_1.put(l_pell_col_name_1, TO_CHAR(l_pell_buf_ts_1, 'YYYY-MM-DD"T"HH24:MI:SS.FF6')); END IF;
        ELSE
          DBMS_SQL.COLUMN_VALUE(l_pell_dyn_cur_1, l_pell_idx_1, l_pell_buf_str_1);
          IF l_pell_buf_str_1 IS NULL THEN l_pell_jobj_1.put_null(l_pell_col_name_1);
          ELSE l_pell_jobj_1.put(l_pell_col_name_1, l_pell_buf_str_1); END IF;
        END IF;
      END LOOP;
      l_pell_row_1 := l_pell_jobj_1.to_json();
      l_product := JSON_VALUE(l_pell_row_1, '$.PRODUCT');
      l_east := JSON_VALUE(l_pell_row_1, '$.EAST' RETURNING NUMBER);
      l_west := JSON_VALUE(l_pell_row_1, '$.WEST' RETURNING NUMBER);
      dbms_output.put_line((l_product || ': east=' || TO_CHAR(l_east) || ' west=' || TO_CHAR(l_west)));
    END LOOP;
    DBMS_SQL.CLOSE_CURSOR(l_pell_dyn_cur_1);
  END east_vs_west;
END dyn_demo;
/