-- ======================================================================
-- Generated by pell 0.0.1 from module mermaid
--   Source:     compiler/examples/31_mermaid.pell
--   SHA-256:    ed6deb382fe5cd33f373d6b3cd4cdb447ca0c129f15de9826b6c28b007c19dfc
--   pell git:   dd8ab63
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
-- ======================================================================

CREATE OR REPLACE PACKAGE mermaid AS
  FUNCTION esc(p_label IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION flowchart(p_direction IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION node(p_id IN VARCHAR2, p_label IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION rounded(p_id IN VARCHAR2, p_label IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION decision(p_id IN VARCHAR2, p_label IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION link(p_from_id IN VARCHAR2, p_to_id IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION link_labeled(p_from_id IN VARCHAR2, p_to_id IN VARCHAR2, p_label IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION classify(p_id IN VARCHAR2, p_cls IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION class_def(p_name IN VARCHAR2, p_css IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION fence(p_body IN VARCHAR2) RETURN VARCHAR2;
END mermaid;
/

CREATE OR REPLACE PACKAGE BODY mermaid AS

  -- Forward declarations (private fns; lets them be
  -- called before their definition in this body).
  FUNCTION nl RETURN VARCHAR2;

  FUNCTION nl RETURN VARCHAR2 IS
  BEGIN
    RETURN chr(10);
  END nl;

  FUNCTION esc(p_label IN VARCHAR2) RETURN VARCHAR2 IS
    l_no_quote VARCHAR2(4000);
    l_no_lbrack VARCHAR2(4000);
    l_no_rbrack VARCHAR2(4000);
  BEGIN
    l_no_quote := replace(p_label, chr(34), chr(39));
    l_no_lbrack := replace(l_no_quote, '[', '(');
    l_no_rbrack := replace(l_no_lbrack, ']', ')');
    RETURN replace(l_no_rbrack, chr(10), '<br/>');
  END esc;

  FUNCTION flowchart(p_direction IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN (('flowchart ' || p_direction) || nl());
  END flowchart;

  FUNCTION node(p_id IN VARCHAR2, p_label IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ((((('    ' || p_id) || '["') || esc(p_label)) || '"]') || nl());
  END node;

  FUNCTION rounded(p_id IN VARCHAR2, p_label IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ((((('    ' || p_id) || '("') || esc(p_label)) || '")') || nl());
  END rounded;

  FUNCTION decision(p_id IN VARCHAR2, p_label IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ((((((('    ' || p_id) || chr(123)) || '"') || esc(p_label)) || '"') || chr(125)) || nl());
  END decision;

  FUNCTION link(p_from_id IN VARCHAR2, p_to_id IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN (((('    ' || p_from_id) || ' --> ') || p_to_id) || nl());
  END link;

  FUNCTION link_labeled(p_from_id IN VARCHAR2, p_to_id IN VARCHAR2, p_label IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN (((((('    ' || p_from_id) || ' -->|') || esc(p_label)) || '| ') || p_to_id) || nl());
  END link_labeled;

  FUNCTION classify(p_id IN VARCHAR2, p_cls IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN (((('    class ' || p_id) || ' ') || p_cls) || nl());
  END classify;

  FUNCTION class_def(p_name IN VARCHAR2, p_css IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN (((('    classDef ' || p_name) || ' ') || p_css) || nl());
  END class_def;

  FUNCTION fence(p_body IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ((('```mermaid' || nl()) || p_body) || '```');
  END fence;
END mermaid;
/