-- ======================================================================
-- Generated by pell 0.0.1 from module explain_plan
--   Source:     compiler/examples/32_explain_plan.pell
--   SHA-256:    c8cdc719361097852acd8c4606b7b0cb1dd331fadfdca1980ae35a3ba7645954
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     all_tab_col_statistics
--     all_tables
--     plan_table
--     v
--   packages:
--     catalog
--     dbms_output
--     mermaid
-- ======================================================================

CREATE OR REPLACE PACKAGE explain_plan AS
  FUNCTION explain_op(p_operation IN VARCHAR2, p_options IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION as_mermaid(p_stmt_id IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION as_tree(p_stmt_id IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION as_story(p_stmt_id IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION analyze(p_query IN VARCHAR2) RETURN VARCHAR2;
  PROCEDURE explain_for(p_stmt_id IN VARCHAR2, p_query IN VARCHAR2);
  PROCEDURE show(p_query IN VARCHAR2);
END explain_plan;
/

CREATE OR REPLACE PACKAGE BODY explain_plan AS

  -- Pinning declarations for dynamic-SQL @touches. Never invoked;
  -- exists so Oracle ALL_DEPENDENCIES tracks references hidden
  -- in EXECUTE IMMEDIATE strings.
  PROCEDURE pell_dep_pinning IS
    CURSOR pin_plan_table IS SELECT 1 FROM plan_table WHERE 1=0;
  BEGIN NULL; END pell_dep_pinning;

  -- Forward declarations (private fns; lets them be
  -- called before their definition in this body).
  FUNCTION op_class(p_operation IN VARCHAR2, p_options IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION index_label(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION object_label(p_owner IN VARCHAR2, p_name IN VARCHAR2, p_is_index IN NUMBER) RETURN VARCHAR2;
  FUNCTION step_notes(p_operation IN VARCHAR2, p_options IN VARCHAR2, p_has_access IN NUMBER, p_access IN VARCHAR2, p_has_filter IN NUMBER, p_filter IN VARCHAR2, p_rows_in IN NUMBER, p_rows_out IN NUMBER, p_pad IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION cardinality_tail(p_rows_out IN NUMBER, p_cost IN NUMBER) RETURN VARCHAR2;
  FUNCTION op_label(p_operation IN VARCHAR2, p_options IN VARCHAR2, p_has_opt IN NUMBER, p_has_obj IN NUMBER, p_owner IN VARCHAR2, p_name IN VARCHAR2, p_is_index IN NUMBER) RETURN VARCHAR2;
  FUNCTION table_rows(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN NUMBER;
  FUNCTION col_ndv(p_owner IN VARCHAR2, p_name IN VARCHAR2, p_col IN VARCHAR2) RETURN NUMBER;

  FUNCTION explain_op(p_operation IN VARCHAR2, p_options IN VARCHAR2) RETURN VARCHAR2 IS
    l_op VARCHAR2(4000);
    l_opt VARCHAR2(4000);
  BEGIN
    l_op := upper(p_operation);
    l_opt := upper(p_options);
    IF (l_op = 'SELECT STATEMENT') THEN
      RETURN 'The query result.';
    END IF;
    IF ((l_op = 'TABLE ACCESS') AND (l_opt = 'FULL')) THEN
      RETURN 'Reads every row of the table (full scan) — fine for small tables, costly for big ones.';
    END IF;
    IF ((l_op = 'TABLE ACCESS') AND (INSTR(l_opt, 'ROWID') > 0)) THEN
      RETURN 'Fetches table rows directly by rowid, handed up from an index.';
    END IF;
    IF ((l_op = 'INDEX') AND (l_opt = 'UNIQUE SCAN')) THEN
      RETURN 'Pinpoints a single row through a unique index — the fastest lookup.';
    END IF;
    IF ((l_op = 'INDEX') AND (INSTR(l_opt, 'RANGE') > 0)) THEN
      RETURN 'Walks a contiguous range of index entries.';
    END IF;
    IF ((l_op = 'INDEX') AND (INSTR(l_opt, 'FULL') > 0)) THEN
      RETURN 'Scans the whole index in order.';
    END IF;
    IF ((l_op = 'INDEX') AND (INSTR(l_opt, 'SKIP') > 0)) THEN
      RETURN 'Uses a composite index without its leading column (skip scan).';
    END IF;
    IF (l_op = 'NESTED LOOPS') THEN
      RETURN 'For each row from the first input, probes the second — good when the first input is small.';
    END IF;
    IF (l_op = 'HASH JOIN') THEN
      RETURN 'Builds a hash table from one input, then probes it with the other — good for large joins.';
    END IF;
    IF (l_op = 'MERGE JOIN') THEN
      RETURN 'Merges two already-sorted inputs.';
    END IF;
    IF ((l_op = 'SORT') AND (l_opt = 'ORDER BY')) THEN
      RETURN 'Sorts rows to satisfy ORDER BY.';
    END IF;
    IF ((l_op = 'SORT') AND (INSTR(l_opt, 'AGGREGATE') > 0)) THEN
      RETURN 'Collapses all rows into one aggregate (COUNT/SUM/…).';
    END IF;
    IF ((l_op = 'SORT') AND (INSTR(l_opt, 'UNIQUE') > 0)) THEN
      RETURN 'Sorts and removes duplicates (DISTINCT / set op).';
    END IF;
    IF ((l_op = 'HASH') AND (INSTR(l_opt, 'GROUP') > 0)) THEN
      RETURN 'Groups rows with a hash table for GROUP BY.';
    END IF;
    IF ((l_op = 'SORT') AND (INSTR(l_opt, 'GROUP') > 0)) THEN
      RETURN 'Groups rows by sorting them for GROUP BY.';
    END IF;
    IF (l_op = 'FILTER') THEN
      RETURN 'Keeps only rows passing a predicate.';
    END IF;
    IF (l_op = 'COUNT') THEN
      RETURN 'Counts / numbers rows (e.g. ROWNUM).';
    END IF;
    IF (l_op = 'VIEW') THEN
      RETURN 'Materializes an inline view or subquery.';
    END IF;
    IF (l_op = 'PARTITION RANGE') THEN
      RETURN 'Prunes to the relevant table partitions.';
    END IF;
    IF (l_op = 'CONNECT BY') THEN
      RETURN 'Walks a hierarchy (CONNECT BY).';
    END IF;
    RETURN p_operation;
  END explain_op;

  FUNCTION op_class(p_operation IN VARCHAR2, p_options IN VARCHAR2) RETURN VARCHAR2 IS
    l_op VARCHAR2(4000);
    l_opt VARCHAR2(4000);
  BEGIN
    l_op := upper(p_operation);
    l_opt := upper(p_options);
    IF ((l_op = 'TABLE ACCESS') AND (l_opt = 'FULL')) THEN
      RETURN 'fullscan';
    END IF;
    IF (l_op = 'INDEX') THEN
      RETURN 'index';
    END IF;
    IF ((INSTR(l_op, 'JOIN') > 0) OR (l_op = 'NESTED LOOPS')) THEN
      RETURN 'join';
    END IF;
    RETURN 'plain';
  END op_class;

  FUNCTION as_mermaid(p_stmt_id IN VARCHAR2) RETURN VARCHAR2 IS
    l_buf VARCHAR2(4000);
    l_nid VARCHAR2(4000);
  BEGIN
    l_buf := mermaid.flowchart('TD');
    l_buf := (l_buf || mermaid.class_def('fullscan', 'fill:#ffe0e0,stroke:#cc0000'));
    l_buf := (l_buf || mermaid.class_def('index', 'fill:#e0ffe0,stroke:#009900'));
    l_buf := (l_buf || mermaid.class_def('join', 'fill:#e0e8ff,stroke:#3355cc'));
    FOR row IN (
      select id,
                     nvl(parent_id, -1) as parent_id,
                     operation,
                     nvl(options, ' ') as options,
                     operation
                       || case when options is not null then ' ' || options else '' end
                       || case when object_name is not null then chr(10) || object_name else '' end
                       || case when cardinality is not null then chr(10) || 'rows=' || cardinality else '' end
                       || case when cost is not null then ' cost=' || cost else '' end
                       as label
                from plan_table
               where statement_id = p_stmt_id
               order by id
    ) LOOP
      l_nid := ('n' || row.id);
      l_buf := (l_buf || mermaid.node(l_nid, row.label));
      l_buf := (l_buf || mermaid.classify(l_nid, op_class(row.operation, row.options)));
      IF (row.parent_id >= 0) THEN
        l_buf := (l_buf || mermaid.link(('n' || row.parent_id), l_nid));
      END IF;
    END LOOP;
    RETURN l_buf;
  END as_mermaid;

  FUNCTION index_label(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN VARCHAR2 IS
    l_d catalog.t_indexdetail;
    l_uniq VARCHAR2(4000);
  BEGIN
    l_d := catalog.index_detail(p_owner, p_name);
    IF (l_d.cols_found = 0) THEN
      RETURN p_name;
    END IF;
    l_uniq := 'non-unique';
    IF (l_d.uniqueness = 'UNIQUE') THEN
      l_uniq := 'unique';
    END IF;
    RETURN (l_d.table_name || '(' || l_d.cols || ') ' || l_uniq);
  END index_label;

  FUNCTION object_label(p_owner IN VARCHAR2, p_name IN VARCHAR2, p_is_index IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    IF (p_is_index = 1) THEN
      RETURN index_label(p_owner, p_name);
    END IF;
    RETURN p_name;
  END object_label;

  FUNCTION step_notes(p_operation IN VARCHAR2, p_options IN VARCHAR2, p_has_access IN NUMBER, p_access IN VARCHAR2, p_has_filter IN NUMBER, p_filter IN VARCHAR2, p_rows_in IN NUMBER, p_rows_out IN NUMBER, p_pad IN VARCHAR2) RETURN VARCHAR2 IS
    l_notes VARCHAR2(4000);
    l_extra VARCHAR2(4000);
    l_removed NUMBER;
  BEGIN
    l_notes := (((p_pad || '-> ') || explain_op(p_operation, p_options)) || chr(10));
    IF (p_has_access = 1) THEN
      l_notes := ((((l_notes || p_pad) || 'accessed by: ') || p_access) || chr(10));
    END IF;
    IF (p_has_filter = 1) THEN
      l_extra := '';
      IF (((p_rows_in > 0) AND (p_rows_out >= 0)) AND (p_rows_in > p_rows_out)) THEN
        l_removed := (p_rows_in - p_rows_out);
        l_extra := (' (discards ' || TO_CHAR(l_removed) || ' of ' || TO_CHAR(p_rows_in) || ')');
      END IF;
      l_notes := (((((l_notes || p_pad) || 'filtered by:  ') || p_filter) || l_extra) || chr(10));
    END IF;
    RETURN l_notes;
  END step_notes;

  FUNCTION cardinality_tail(p_rows_out IN NUMBER, p_cost IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    IF ((p_rows_out >= 0) AND (p_cost >= 0)) THEN
      RETURN ('   ' || TO_CHAR(p_rows_out) || ' rows, cost ' || TO_CHAR(p_cost));
    END IF;
    IF (p_rows_out >= 0) THEN
      RETURN ('   ' || TO_CHAR(p_rows_out) || ' rows');
    END IF;
    IF (p_cost >= 0) THEN
      RETURN ('   cost ' || TO_CHAR(p_cost));
    END IF;
    RETURN '';
  END cardinality_tail;

  FUNCTION op_label(p_operation IN VARCHAR2, p_options IN VARCHAR2, p_has_opt IN NUMBER, p_has_obj IN NUMBER, p_owner IN VARCHAR2, p_name IN VARCHAR2, p_is_index IN NUMBER) RETURN VARCHAR2 IS
    l_label VARCHAR2(4000);
  BEGIN
    l_label := p_operation;
    IF (p_has_opt = 1) THEN
      l_label := (p_operation || ' ' || p_options);
    END IF;
    IF (p_has_obj = 1) THEN
      l_label := ((l_label || '  ') || object_label(p_owner, p_name, p_is_index));
    END IF;
    RETURN l_label;
  END op_label;

  FUNCTION as_tree(p_stmt_id IN VARCHAR2) RETURN VARCHAR2 IS
    l_buf VARCHAR2(4000);
    l_head VARCHAR2(4000);
  BEGIN
    l_buf := '';
    FOR row IN (
      select p.id,
                     p.depth,
                     p.operation,
                     nvl(p.options, ' ') as options,
                     case when p.options is null then 0 else 1 end as has_opt,
                     case when p.object_name is null then 0 else 1 end as has_obj,
                     case when p.object_type like 'INDEX%' then 1 else 0 end as is_index,
                     nvl(p.object_owner, user) as object_owner,
                     nvl(p.object_name, ' ') as object_name,
                     nvl(p.cardinality, -1) as rows_out,
                     nvl(p.cost, -1) as cost,
                     case when p.access_predicates is null then 0 else 1 end as has_access,
                     nvl(replace(p.access_predicates, chr(34), ''), ' ') as access_pred,
                     case when p.filter_predicates is null then 0 else 1 end as has_filter,
                     nvl(replace(p.filter_predicates, chr(34), ''), ' ') as filter_pred,
                     nvl((select sum(c.cardinality) from plan_table c
                            where c.statement_id = p.statement_id and c.parent_id = p.id), -1) as rows_in,
                     rpad(' ', p.depth * 2, ' ') as indent
                from plan_table p
               where p.statement_id = p_stmt_id
               order by p.id
    ) LOOP
      l_head := op_label(row.operation, row.options, row.has_opt, row.has_obj, row.object_owner, row.object_name, row.is_index);
      l_buf := ((((l_buf || row.indent) || l_head) || cardinality_tail(row.rows_out, row.cost)) || chr(10));
      l_buf := (l_buf || step_notes(row.operation, row.options, row.has_access, row.access_pred, row.has_filter, row.filter_pred, row.rows_in, row.rows_out, (row.indent || '    ')));
    END LOOP;
    RETURN l_buf;
  END as_tree;

  FUNCTION as_story(p_stmt_id IN VARCHAR2) RETURN VARCHAR2 IS
    l_hdr_rows NUMBER;
    l_hdr_cost NUMBER;
    l_buf VARCHAR2(4000);
    l_step NUMBER;
    l_prev_parent NUMBER;
    l_head VARCHAR2(4000);
  BEGIN
    BEGIN
      select nvl(max(case when id = 0 then cardinality end), -1) as v
      INTO l_hdr_rows
      FROM plan_table where statement_id = p_stmt_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    BEGIN
      select nvl(max(case when id = 0 then cost end), -1) as v
      INTO l_hdr_cost
      FROM plan_table where statement_id = p_stmt_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    l_buf := 'How Oracle runs this';
    IF (l_hdr_rows >= 0) THEN
      l_buf := (l_buf || (' — ' || TO_CHAR(l_hdr_rows) || ' rows out'));
    END IF;
    IF (l_hdr_cost >= 0) THEN
      l_buf := (l_buf || (', cost ' || TO_CHAR(l_hdr_cost)));
    END IF;
    l_buf := ((l_buf || chr(10)) || chr(10));
    l_step := 0;
    l_prev_parent := -99;
    FOR row IN (
      select p.id,
                     nvl(p.parent_id, -1) as parent_id,
                     p.operation,
                     nvl(p.options, ' ') as options,
                     case when p.options is null then 0 else 1 end as has_opt,
                     case when p.object_name is null then 0 else 1 end as has_obj,
                     case when p.object_type like 'INDEX%' then 1 else 0 end as is_index,
                     nvl(p.object_owner, user) as object_owner,
                     nvl(p.object_name, ' ') as object_name,
                     nvl(p.cardinality, -1) as rows_out,
                     nvl(p.cost, -1) as cost,
                     case when p.access_predicates is null then 0 else 1 end as has_access,
                     nvl(replace(p.access_predicates, chr(34), ''), ' ') as access_pred,
                     case when p.filter_predicates is null then 0 else 1 end as has_filter,
                     nvl(replace(p.filter_predicates, chr(34), ''), ' ') as filter_pred,
                     nvl((select sum(c.cardinality) from plan_table c
                            where c.statement_id = p.statement_id and c.parent_id = p.id), -1) as rows_in
                from plan_table p
               where p.statement_id = p_stmt_id
               order by nvl((select min(n.id) from plan_table n
                               where n.statement_id = p.statement_id
                                 and n.id > p.id and n.depth <= p.depth) - 1,
                            (select max(m.id) from plan_table m
                              where m.statement_id = p.statement_id)) asc,
                        p.id desc
    ) LOOP
      IF ((l_step > 0) AND (row.id <> l_prev_parent)) THEN
        l_buf := ((l_buf || '   --- meanwhile, the other input ---') || chr(10));
      END IF;
      l_step := (l_step + 1);
      l_head := op_label(row.operation, row.options, row.has_opt, row.has_obj, row.object_owner, row.object_name, row.is_index);
      l_buf := ((((l_buf || (TO_CHAR(l_step) || '  ')) || l_head) || cardinality_tail(row.rows_out, row.cost)) || chr(10));
      l_buf := (l_buf || step_notes(row.operation, row.options, row.has_access, row.access_pred, row.has_filter, row.filter_pred, row.rows_in, row.rows_out, '     '));
      l_prev_parent := row.parent_id;
    END LOOP;
    RETURN l_buf;
  END as_story;

  FUNCTION table_rows(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN NUMBER IS
    l_r NUMBER;
  BEGIN
    BEGIN
      select nvl(max(num_rows), -1) as v
      INTO l_r
      FROM all_tables where owner = p_owner and table_name = p_name;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END table_rows;

  FUNCTION col_ndv(p_owner IN VARCHAR2, p_name IN VARCHAR2, p_col IN VARCHAR2) RETURN NUMBER IS
    l_r NUMBER;
  BEGIN
    BEGIN
      select nvl(max(num_distinct), -1) as v
      INTO l_r
      FROM all_tab_col_statistics
         where owner = p_owner and table_name = p_name and column_name = p_col;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_r;
  END col_ndv;

  FUNCTION analyze(p_query IN VARCHAR2) RETURN VARCHAR2 IS
    l_returned NUMBER;
    l_buf VARCHAR2(4000);
    l_found NUMBER;
    l_head VARCHAR2(4000);
    l_nums VARCHAR2(4000);
    l_flag VARCHAR2(4000);
    l_nrows NUMBER;
    l_why VARCHAR2(4000);
    l_ndv NUMBER;
  BEGIN
    EXECUTE IMMEDIATE ('select /*+ gather_plan_statistics */ count(*) from (' || p_query || ') pelldeepprobe_src') INTO l_returned;
    l_buf := (('Deep analysis — executed; the query returns ' || TO_CHAR(l_returned) || ' row(s).') || chr(10));
    l_buf := (((l_buf || 'Optimizer estimate vs actual rows, per step:') || chr(10)) || chr(10));
    l_found := 0;
    FOR row IN (
      select p.id,
                     p.depth,
                     p.operation,
                     nvl(p.options, ' ') as options,
                     case when p.options is null then 0 else 1 end as has_opt,
                     case when p.object_name is null then 0 else 1 end as has_obj,
                     case when p.object_type like 'INDEX%' then 1 else 0 end as is_index,
                     case when p.object_type like 'TABLE%' then 1 else 0 end as is_table,
                     nvl(p.object_owner, user) as object_owner,
                     nvl(p.object_name, ' ') as object_name,
                     nvl(p.cardinality, -1) as est_rows,
                     nvl(p.last_output_rows, -1) as act_rows,
                     case when p.cardinality is not null and p.last_output_rows is not null
                               and p.last_output_rows > 0
                          then round(greatest(p.cardinality, p.last_output_rows)
                                     / greatest(least(p.cardinality, p.last_output_rows), 1))
                          else -1 end as misfactor,
                     case when nvl(p.cardinality, 0) > nvl(p.last_output_rows, 0) then 1 else 0 end as over_est,
                     case when p.access_predicates is null then 0 else 1 end as has_access,
                     nvl(replace(p.access_predicates, chr(34), ''), ' ') as access_pred,
                     case when p.filter_predicates is null then 0 else 1 end as has_filter,
                     nvl(replace(p.filter_predicates, chr(34), ''), ' ') as filter_pred,
                     nvl(regexp_substr(p.filter_predicates, '"([^"]+)"', 1, 1, null, 1), ' ') as filter_col,
                     case when regexp_substr(p.filter_predicates, '"([^"]+)"', 1, 1, null, 1) is null
                          then 0 else 1 end as has_filter_col,
                     rpad(' ', p.depth * 2, ' ') as indent
                from v$sql_plan_statistics_all p
               where (p.sql_id, p.child_number) = (
                       select s.sql_id, s.child_number from v$sql s
                        where s.sql_text like '%pelldeep' || 'probe_src%'
                        order by s.last_active_time desc, s.child_number desc
                        fetch first 1 row only)
               order by p.id
    ) LOOP
      l_found := 1;
      l_head := op_label(row.operation, row.options, row.has_opt, row.has_obj, row.object_owner, row.object_name, row.is_index);
      l_nums := '';
      IF (row.est_rows >= 0) THEN
        l_nums := ('   est ' || row.est_rows);
      END IF;
      IF (row.act_rows >= 0) THEN
        IF (row.est_rows >= 0) THEN
          l_nums := (l_nums || (', actual ' || row.act_rows));
        ELSE
          l_nums := ('   actual ' || row.act_rows);
        END IF;
      END IF;
      l_flag := '';
      IF (row.misfactor >= 10) THEN
        IF (row.over_est = 1) THEN
          l_flag := ('   << over-estimated ' || row.misfactor || 'x >>');
        ELSE
          l_flag := ('   << under-estimated ' || row.misfactor || 'x >>');
        END IF;
      END IF;
      l_buf := (((((l_buf || row.indent) || l_head) || l_nums) || l_flag) || chr(10));
      l_buf := ((((l_buf || row.indent) || '    -> ') || explain_op(row.operation, row.options)) || chr(10));
      IF (row.has_access = 1) THEN
        l_buf := ((((l_buf || row.indent) || '    accessed by: ') || row.access_pred) || chr(10));
      END IF;
      IF (row.has_filter = 1) THEN
        l_buf := ((((l_buf || row.indent) || '    filtered by:  ') || row.filter_pred) || chr(10));
      END IF;
      IF (row.is_table = 1) THEN
        l_nrows := table_rows(row.object_owner, row.object_name);
        IF (l_nrows >= 0) THEN
          l_why := ('table has ' || TO_CHAR(l_nrows) || ' rows');
          IF (row.has_filter_col = 1) THEN
            l_ndv := col_ndv(row.object_owner, row.object_name, row.filter_col);
            IF (l_ndv >= 1) THEN
              l_why := (l_why || ('; ' || row.filter_col || ' has ' || TO_CHAR(l_ndv) || ' distinct value(s)'));
            END IF;
          END IF;
          l_buf := ((((l_buf || row.indent) || '    stats: ') || l_why) || chr(10));
        END IF;
      END IF;
    END LOOP;
    IF (l_found = 0) THEN
      l_buf := (((l_buf || '  (no row-source statistics found — the query may have failed to ') || 'execute, or SELECT on V$SQL_PLAN_STATISTICS_ALL isn''t granted)') || chr(10));
    END IF;
    RETURN l_buf;
  END analyze;

  PROCEDURE explain_for(p_stmt_id IN VARCHAR2, p_query IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE ('delete from plan_table where statement_id = ''' || p_stmt_id || '''');
    EXECUTE IMMEDIATE ('explain plan set statement_id = ''' || p_stmt_id || ''' for ' || p_query);
  END explain_for;

  PROCEDURE show(p_query IN VARCHAR2) IS
  BEGIN
    explain_for('pell_show', p_query);
    dbms_output.put_line(as_story('pell_show'));
    dbms_output.put_line('  ---- plan structure ----');
    dbms_output.put_line(as_tree('pell_show'));
  END show;
END explain_plan;
/