-- ======================================================================
-- Generated by pell 0.0.1 from module explain_plan
--   Source:     compiler/examples/32_explain_plan.pell
--   SHA-256:    8e50eb968a7d959e15a93359c12c88de66f4d19dbbe98f715c81964abd1741d5
--   pell git:   5e9521e
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     plan_table
--   packages:
--     dbms_output
--     mermaid
-- ======================================================================

CREATE OR REPLACE PACKAGE explain_plan AS
  FUNCTION explain_op(p_operation IN VARCHAR2, p_options IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION as_mermaid(p_stmt_id IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION as_tree(p_stmt_id IN VARCHAR2) RETURN VARCHAR2;
  PROCEDURE explain_for(p_stmt_id IN VARCHAR2, p_query IN VARCHAR2);
  PROCEDURE show(p_query IN VARCHAR2);
END explain_plan;
/

CREATE OR REPLACE PACKAGE BODY explain_plan AS

  -- Pinning declarations for dynamic-SQL @touches. Never invoked;
  -- exists so Oracle ALL_DEPENDENCIES tracks references hidden
  -- in EXECUTE IMMEDIATE strings.
  PROCEDURE pell_dep_pinning IS
    CURSOR pin_plan_table IS SELECT 1 FROM plan_table WHERE 1=0;
  BEGIN NULL; END pell_dep_pinning;

  -- Forward declarations (private fns; lets them be
  -- called before their definition in this body).
  FUNCTION op_class(p_operation IN VARCHAR2, p_options IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION explain_op(p_operation IN VARCHAR2, p_options IN VARCHAR2) RETURN VARCHAR2 IS
    l_op VARCHAR2(4000);
    l_opt VARCHAR2(4000);
  BEGIN
    l_op := upper(p_operation);
    l_opt := upper(p_options);
    IF (l_op = 'SELECT STATEMENT') THEN
      RETURN 'The query result.';
    END IF;
    IF ((l_op = 'TABLE ACCESS') AND (l_opt = 'FULL')) THEN
      RETURN 'Reads every row of the table (full scan) — fine for small tables, costly for big ones.';
    END IF;
    IF ((l_op = 'TABLE ACCESS') AND (INSTR(l_opt, 'ROWID') > 0)) THEN
      RETURN 'Fetches table rows directly by rowid, handed up from an index.';
    END IF;
    IF ((l_op = 'INDEX') AND (l_opt = 'UNIQUE SCAN')) THEN
      RETURN 'Pinpoints a single row through a unique index — the fastest lookup.';
    END IF;
    IF ((l_op = 'INDEX') AND (INSTR(l_opt, 'RANGE') > 0)) THEN
      RETURN 'Walks a contiguous range of index entries.';
    END IF;
    IF ((l_op = 'INDEX') AND (INSTR(l_opt, 'FULL') > 0)) THEN
      RETURN 'Scans the whole index in order.';
    END IF;
    IF ((l_op = 'INDEX') AND (INSTR(l_opt, 'SKIP') > 0)) THEN
      RETURN 'Uses a composite index without its leading column (skip scan).';
    END IF;
    IF (l_op = 'NESTED LOOPS') THEN
      RETURN 'For each row from the first input, probes the second — good when the first input is small.';
    END IF;
    IF (l_op = 'HASH JOIN') THEN
      RETURN 'Builds a hash table from one input, then probes it with the other — good for large joins.';
    END IF;
    IF (l_op = 'MERGE JOIN') THEN
      RETURN 'Merges two already-sorted inputs.';
    END IF;
    IF ((l_op = 'SORT') AND (l_opt = 'ORDER BY')) THEN
      RETURN 'Sorts rows to satisfy ORDER BY.';
    END IF;
    IF ((l_op = 'SORT') AND (INSTR(l_opt, 'AGGREGATE') > 0)) THEN
      RETURN 'Collapses all rows into one aggregate (COUNT/SUM/…).';
    END IF;
    IF ((l_op = 'SORT') AND (INSTR(l_opt, 'UNIQUE') > 0)) THEN
      RETURN 'Sorts and removes duplicates (DISTINCT / set op).';
    END IF;
    IF ((l_op = 'HASH') AND (INSTR(l_opt, 'GROUP') > 0)) THEN
      RETURN 'Groups rows with a hash table for GROUP BY.';
    END IF;
    IF ((l_op = 'SORT') AND (INSTR(l_opt, 'GROUP') > 0)) THEN
      RETURN 'Groups rows by sorting them for GROUP BY.';
    END IF;
    IF (l_op = 'FILTER') THEN
      RETURN 'Keeps only rows passing a predicate.';
    END IF;
    IF (l_op = 'COUNT') THEN
      RETURN 'Counts / numbers rows (e.g. ROWNUM).';
    END IF;
    IF (l_op = 'VIEW') THEN
      RETURN 'Materializes an inline view or subquery.';
    END IF;
    IF (l_op = 'PARTITION RANGE') THEN
      RETURN 'Prunes to the relevant table partitions.';
    END IF;
    IF (l_op = 'CONNECT BY') THEN
      RETURN 'Walks a hierarchy (CONNECT BY).';
    END IF;
    RETURN p_operation;
  END explain_op;

  FUNCTION op_class(p_operation IN VARCHAR2, p_options IN VARCHAR2) RETURN VARCHAR2 IS
    l_op VARCHAR2(4000);
    l_opt VARCHAR2(4000);
  BEGIN
    l_op := upper(p_operation);
    l_opt := upper(p_options);
    IF ((l_op = 'TABLE ACCESS') AND (l_opt = 'FULL')) THEN
      RETURN 'fullscan';
    END IF;
    IF (l_op = 'INDEX') THEN
      RETURN 'index';
    END IF;
    IF ((INSTR(l_op, 'JOIN') > 0) OR (l_op = 'NESTED LOOPS')) THEN
      RETURN 'join';
    END IF;
    RETURN 'plain';
  END op_class;

  FUNCTION as_mermaid(p_stmt_id IN VARCHAR2) RETURN VARCHAR2 IS
    l_buf VARCHAR2(4000);
    l_nid VARCHAR2(4000);
  BEGIN
    l_buf := mermaid.flowchart('TD');
    l_buf := (l_buf || mermaid.class_def('fullscan', 'fill:#ffe0e0,stroke:#cc0000'));
    l_buf := (l_buf || mermaid.class_def('index', 'fill:#e0ffe0,stroke:#009900'));
    l_buf := (l_buf || mermaid.class_def('join', 'fill:#e0e8ff,stroke:#3355cc'));
    FOR row IN (
      select id,
                     nvl(parent_id, -1) as parent_id,
                     operation,
                     nvl(options, ' ') as options,
                     operation
                       || case when options is not null then ' ' || options else '' end
                       || case when object_name is not null then chr(10) || object_name else '' end
                       || case when cardinality is not null then chr(10) || 'rows=' || cardinality else '' end
                       || case when cost is not null then ' cost=' || cost else '' end
                       as label
                from plan_table
               where statement_id = p_stmt_id
               order by id
    ) LOOP
      l_nid := ('n' || row.id);
      l_buf := (l_buf || mermaid.node(l_nid, row.label));
      l_buf := (l_buf || mermaid.classify(l_nid, op_class(row.operation, row.options)));
      IF (row.parent_id >= 0) THEN
        l_buf := (l_buf || mermaid.link(('n' || row.parent_id), l_nid));
      END IF;
    END LOOP;
    RETURN l_buf;
  END as_mermaid;

  FUNCTION as_tree(p_stmt_id IN VARCHAR2) RETURN VARCHAR2 IS
    l_buf VARCHAR2(4000);
  BEGIN
    l_buf := '';
    FOR row IN (
      select depth,
                     operation,
                     nvl(options, ' ') as options,
                     rpad(' ', depth * 2, ' ') as indent,
                     operation
                       || case when options is not null then ' ' || options else '' end
                       || case when object_name is not null then ' ' || object_name else '' end
                       || case when cardinality is not null then ' (rows=' || cardinality else '' end
                       || case when cost is not null then ' cost=' || cost || ')'
                               when cardinality is not null then ')' else '' end
                       as step
                from plan_table
               where statement_id = p_stmt_id
               order by id
    ) LOOP
      l_buf := (((l_buf || row.indent) || row.step) || chr(10));
      l_buf := ((((l_buf || row.indent) || '    -> ') || explain_op(row.operation, row.options)) || chr(10));
    END LOOP;
    RETURN l_buf;
  END as_tree;

  PROCEDURE explain_for(p_stmt_id IN VARCHAR2, p_query IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE ('delete from plan_table where statement_id = ''' || p_stmt_id || '''');
    EXECUTE IMMEDIATE ('explain plan set statement_id = ''' || p_stmt_id || ''' for ' || p_query);
  END explain_for;

  PROCEDURE show(p_query IN VARCHAR2) IS
  BEGIN
    explain_for('pell_show', p_query);
    dbms_output.put_line(as_tree('pell_show'));
    dbms_output.put_line(mermaid.fence(as_mermaid('pell_show')));
  END show;
END explain_plan;
/