-- ======================================================================
-- Generated by pell 0.0.1 from module stat_diff
--   Source:     compiler/examples/33_stat_diff.pell
--   SHA-256:    4eaaefd07eaec7b566ef46d2292ca50a5a7e85f06cfbb0e57d9f7fe4573c4b83
--   pell git:   5e9521e
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     v
--   packages:
--     dbms_output
-- ======================================================================

CREATE OR REPLACE PACKAGE stat_diff AS
  FUNCTION snapshot RETURN JSON;
  FUNCTION report(p_before IN JSON, p_after IN JSON) RETURN VARCHAR2;
  PROCEDURE around(p_query IN VARCHAR2);
END stat_diff;
/

CREATE OR REPLACE PACKAGE BODY stat_diff AS

  -- Forward declarations (private fns; lets them be
  -- called before their definition in this body).
  FUNCTION delta_line(p_label IN VARCHAR2, p_before IN JSON, p_after IN JSON, p_key IN VARCHAR2) RETURN VARCHAR2;

  FUNCTION snapshot RETURN JSON IS
    l_snap JSON;
  BEGIN
    BEGIN
      select json_objectagg(k value v returning clob) as j
      INTO l_snap
      FROM (
            select case n.name
                     when 'session logical reads'      then 'logical_reads'
                     when 'consistent gets'            then 'consistent_gets'
                     when 'db block gets'              then 'db_block_gets'
                     when 'physical reads'             then 'physical_reads'
                     when 'CPU used by this session'   then 'cpu_centisecs'
                     when 'sorts (memory)'             then 'sorts_memory'
                     when 'sorts (disk)'               then 'sorts_disk'
                     when 'redo size'                  then 'redo_size'
                     when 'execute count'              then 'execute_count'
                     when 'parse count (total)'        then 'parse_count'
                     when 'table scan rows gotten'     then 'table_scan_rows'
                     when 'table fetch by rowid'       then 'fetch_by_rowid'
                   end as k,
                   m.value as v
              from v$mystat m
              join v$statname n on m.statistic# = n.statistic#
             where n.name in (
                     'session logical reads', 'consistent gets',
                     'db block gets', 'physical reads',
                     'CPU used by this session', 'sorts (memory)',
                     'sorts (disk)', 'redo size', 'execute count',
                     'parse count (total)', 'table scan rows gotten',
                     'table fetch by rowid')
          );
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_snap;
  END snapshot;

  FUNCTION delta_line(p_label IN VARCHAR2, p_before IN JSON, p_after IN JSON, p_key IN VARCHAR2) RETURN VARCHAR2 IS
    l_path VARCHAR2(4000);
    l_b NUMBER;
    l_a NUMBER;
    l_d NUMBER;
  BEGIN
    l_path := ('$.' || p_key);
    l_b := JSON_VALUE(p_before, l_path RETURNING NUMBER);
    l_a := JSON_VALUE(p_after, l_path RETURNING NUMBER);
    l_d := (l_a - l_b);
    IF (l_d = 0) THEN
      RETURN '';
    END IF;
    RETURN ((((rpad(p_label, 26, ' ') || lpad(l_b, 14, ' ')) || lpad(l_a, 14, ' ')) || lpad(l_d, 14, ' ')) || chr(10));
  END delta_line;

  FUNCTION report(p_before IN JSON, p_after IN JSON) RETURN VARCHAR2 IS
    l_buf VARCHAR2(4000);
  BEGIN
    l_buf := ((((rpad('statistic', 26, ' ') || lpad('before', 14, ' ')) || lpad('after', 14, ' ')) || lpad('delta', 14, ' ')) || chr(10));
    l_buf := ((l_buf || rpad('-', 64, '-')) || chr(10));
    l_buf := (l_buf || delta_line('logical reads (LIO)', p_before, p_after, 'logical_reads'));
    l_buf := (l_buf || delta_line('consistent gets', p_before, p_after, 'consistent_gets'));
    l_buf := (l_buf || delta_line('db block gets', p_before, p_after, 'db_block_gets'));
    l_buf := (l_buf || delta_line('physical reads', p_before, p_after, 'physical_reads'));
    l_buf := (l_buf || delta_line('CPU (centisecs)', p_before, p_after, 'cpu_centisecs'));
    l_buf := (l_buf || delta_line('sorts (memory)', p_before, p_after, 'sorts_memory'));
    l_buf := (l_buf || delta_line('sorts (disk)', p_before, p_after, 'sorts_disk'));
    l_buf := (l_buf || delta_line('redo size (bytes)', p_before, p_after, 'redo_size'));
    l_buf := (l_buf || delta_line('executes', p_before, p_after, 'execute_count'));
    l_buf := (l_buf || delta_line('parses', p_before, p_after, 'parse_count'));
    l_buf := (l_buf || delta_line('table scan rows', p_before, p_after, 'table_scan_rows'));
    l_buf := (l_buf || delta_line('rows by rowid', p_before, p_after, 'fetch_by_rowid'));
    RETURN l_buf;
  END report;

  PROCEDURE around(p_query IN VARCHAR2) IS
    l_before JSON;
    l_n NUMBER;
    l_after JSON;
  BEGIN
    l_before := snapshot();
    EXECUTE IMMEDIATE ('select count(*) from (' || p_query || ')') INTO l_n;
    l_after := snapshot();
    dbms_output.put_line(('ran: ' || p_query));
    dbms_output.put_line((('(scanned ' || TO_CHAR(l_n)) || ' rows)'));
    dbms_output.put_line(report(l_before, l_after));
  END around;
END stat_diff;
/