-- ======================================================================
-- Generated by pell 0.0.1 from module table_stats
--   Source:     compiler/examples/34_table_stats.pell
--   SHA-256:    ac2abd40a0467a9deae3c0d0126b205f5d293ab07884d82683e046a67dbd21e9
--   pell git:   49d3402
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     user_tab_col_statistics
--     user_tab_histograms
--     user_tab_statistics
--   packages:
--     dbms_output
-- ======================================================================

CREATE OR REPLACE PACKAGE table_stats AS
  FUNCTION summary(p_table_name IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION column_stats(p_table_name IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION histogram(p_table_name IN VARCHAR2, p_column_name IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION report(p_table_name IN VARCHAR2) RETURN VARCHAR2;
  PROCEDURE show(p_table_name IN VARCHAR2);
END table_stats;
/

CREATE OR REPLACE PACKAGE BODY table_stats AS

  FUNCTION summary(p_table_name IN VARCHAR2) RETURN VARCHAR2 IS
    l_buf VARCHAR2(4000);
  BEGIN
    l_buf := (('TABLE ' || upper(p_table_name)) || chr(10));
    FOR r IN (
      select num_rows,
                     blocks,
                     avg_row_len,
                     sample_size,
                     to_char(last_analyzed, 'YYYY-MM-DD HH24:MI') as analyzed,
                     case when stale_stats = 'YES' then ' (STALE)' else '' end as stale
                from user_tab_statistics
               where table_name = upper(p_table_name)
                 and partition_name is null
    ) LOOP
      l_buf := (((l_buf || '  rows         : ') || r.num_rows) || chr(10));
      l_buf := (((l_buf || '  blocks       : ') || r.blocks) || chr(10));
      l_buf := ((((l_buf || '  avg row len  : ') || r.avg_row_len) || ' bytes') || chr(10));
      l_buf := ((((l_buf || '  last analyzed: ') || r.analyzed) || r.stale) || chr(10));
      l_buf := (((l_buf || '  sample size  : ') || r.sample_size) || chr(10));
    END LOOP;
    RETURN l_buf;
  END summary;

  FUNCTION column_stats(p_table_name IN VARCHAR2) RETURN VARCHAR2 IS
    l_buf VARCHAR2(4000);
  BEGIN
    l_buf := (((((rpad('column', 30, ' ') || rpad('distinct', 12, ' ')) || rpad('nulls', 10, ' ')) || rpad('histogram', 16, ' ')) || 'buckets') || chr(10));
    l_buf := ((l_buf || rpad('-', 75, '-')) || chr(10));
    FOR r IN (
      select column_name,
                     num_distinct,
                     num_nulls,
                     histogram,
                     num_buckets
                from user_tab_col_statistics
               where table_name = upper(p_table_name)
               order by column_name
    ) LOOP
      l_buf := ((((((l_buf || rpad(r.column_name, 30, ' ')) || rpad(r.num_distinct, 12, ' ')) || rpad(r.num_nulls, 10, ' ')) || rpad(r.histogram, 16, ' ')) || r.num_buckets) || chr(10));
    END LOOP;
    RETURN l_buf;
  END column_stats;

  FUNCTION histogram(p_table_name IN VARCHAR2, p_column_name IN VARCHAR2) RETURN VARCHAR2 IS
    l_buf VARCHAR2(4000);
  BEGIN
    l_buf := (((('HISTOGRAM ' || upper(p_table_name)) || '.') || upper(p_column_name)) || chr(10));
    l_buf := ((((l_buf || rpad('endpoint value', 40, ' ')) || rpad('cumulative', 14, ' ')) || 'bucket') || chr(10));
    l_buf := ((l_buf || rpad('-', 62, '-')) || chr(10));
    FOR r IN (
      select nvl(endpoint_actual_value, to_char(endpoint_value)) as val,
                     endpoint_number as cumulative,
                     endpoint_number
                       - nvl(lag(endpoint_number) over (order by endpoint_number), 0)
                       as bucket_count
                from user_tab_histograms
               where table_name = upper(p_table_name)
                 and column_name = upper(p_column_name)
               order by endpoint_number
    ) LOOP
      l_buf := ((((l_buf || rpad(r.val, 40, ' ')) || rpad(r.cumulative, 14, ' ')) || r.bucket_count) || chr(10));
    END LOOP;
    RETURN l_buf;
  END histogram;

  FUNCTION report(p_table_name IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN ((summary(p_table_name) || chr(10)) || column_stats(p_table_name));
  END report;

  PROCEDURE show(p_table_name IN VARCHAR2) IS
  BEGIN
    dbms_output.put_line(report(p_table_name));
  END show;
END table_stats;
/