-- ======================================================================
-- Generated by pell 0.0.1 from module stats_repl
--   Source:     compiler/examples/35_stats_repl.pell
--   SHA-256:    9b25aa2eca2e3feffc90804f8e2d6053fc08bba9ed77c9ec4b3515a823ad559a
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     user_tab_col_statistics
--     user_tab_statistics
--     user_tables
--   packages:
--     dbms_output
-- ======================================================================

CREATE OR REPLACE PACKAGE stats_repl AS
  PROCEDURE overview;
  PROCEDURE stale;
  PROCEDURE histogrammed;
END stats_repl;
/

CREATE OR REPLACE PACKAGE BODY stats_repl AS

  PROCEDURE overview IS
  BEGIN
    dbms_output.put_line((((rpad('table', 30, ' ') || rpad('rows', 12, ' ')) || rpad('blocks', 10, ' ')) || 'last analyzed'));
    dbms_output.put_line(rpad('-', 70, '-'));
    FOR r IN (
      select table_name,
                     nvl(to_char(num_rows), '(none)') as num_rows,
                     nvl(to_char(blocks), '-') as blocks,
                     nvl(to_char(last_analyzed, 'YYYY-MM-DD HH24:MI'),
                         'never gathered') as analyzed
                from user_tables
               order by num_rows desc nulls first
    ) LOOP
      dbms_output.put_line((((rpad(r.table_name, 30, ' ') || rpad(r.num_rows, 12, ' ')) || rpad(r.blocks, 10, ' ')) || r.analyzed));
    END LOOP;
  END overview;

  PROCEDURE stale IS
    l_any NUMBER;
  BEGIN
    l_any := 0;
    FOR r IN (
      select table_name, stale_stats
                from user_tab_statistics
               where partition_name is null
                 and stale_stats = 'YES'
               order by table_name
    ) LOOP
      dbms_output.put_line(('STALE: ' || r.table_name));
      l_any := 1;
    END LOOP;
    IF (l_any = 0) THEN
      dbms_output.put_line('No stale stats — every table is fresh.');
    END IF;
  END stale;

  PROCEDURE histogrammed IS
  BEGIN
    dbms_output.put_line(((rpad('table.column', 44, ' ') || rpad('histogram', 16, ' ')) || 'buckets'));
    dbms_output.put_line(rpad('-', 70, '-'));
    FOR r IN (
      select table_name || '.' || column_name as col,
                     histogram,
                     num_buckets
                from user_tab_col_statistics
               where histogram is not null
                 and histogram != 'NONE'
               order by table_name, column_name
    ) LOOP
      dbms_output.put_line(((rpad(r.col, 44, ' ') || rpad(r.histogram, 16, ' ')) || r.num_buckets));
    END LOOP;
  END histogrammed;
END stats_repl;
/