-- ======================================================================
-- Generated by pell 0.0.1 from module ut_pell_examples
--   Source:     compiler/examples/36_ut_examples.pell
--   SHA-256:    4a9a1f8d64e73138b0cbe5de03f1710de42b3359521412b54afcef74b7b2a7d7
--   pell git:   8f94473
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     hr.employees
--     inventory.skus
--   packages:
--     collections_linked_list
--     explain_plan
--     hello
--     json_demo
--     mermaid
--     staffing
--     stat_diff
--     stock
--     text_utils
--     ut
-- ======================================================================

CREATE OR REPLACE PACKAGE ut_pell_examples AS
  --%suite(pell example vetting — every module behaves, not just compiles)

  --%test(hello::greet greets by name)
  PROCEDURE t_greet;
  --%test(text_utils basics: len/trim/case/contains)
  PROCEDURE t_text_utils;
  --%test(json_demo builds and reads nested documents)
  PROCEDURE t_json_roundtrip;
  --%test(linked_list: build, summarize, reverse)
  PROCEDURE t_linked_list;
  --%test(staffing: find, promote, and the NotFound path)
  PROCEDURE t_staffing;
  --%test(stock::create_sku returns a sequence-assigned id)
  PROCEDURE t_stock;
  --%test(mermaid builders produce well-formed diagram text)
  PROCEDURE t_mermaid;
  --%test(explain_plan explains the common row sources in plain English)
  PROCEDURE t_explain_op;
  --%test(stat_diff snapshots carry the headline statistics)
  PROCEDURE t_stat_diff;
END ut_pell_examples;
/

CREATE OR REPLACE PACKAGE BODY ut_pell_examples AS

  PROCEDURE t_greet IS
  BEGIN
    ut.expect(hello.greet('world')).to_equal('hello, world');
  END t_greet;

  PROCEDURE t_text_utils IS
  BEGIN
    ut.expect(text_utils.len('abc')).to_equal(3);
    ut.expect(text_utils.trim_ws('  x  ')).to_equal('x');
    ut.expect(text_utils.to_upper('abc')).to_equal('ABC');
    ut.expect(text_utils.has('haystack', 'hay')).to_be_true();
    ut.expect(text_utils.is_blank('   ')).to_be_true();
    ut.expect(text_utils.is_blank('x')).to_be_false();
  END t_text_utils;

  PROCEDURE t_json_roundtrip IS
    l_j JSON;
    l_n JSON;
  BEGIN
    l_j := json_demo.build_simple();
    ut.expect(JSON_VALUE(l_j, '$.name')).to_equal('Alice');
    ut.expect(JSON_VALUE(l_j, '$.age' RETURNING NUMBER)).to_equal(30);
    l_n := json_demo.build_nested();
    ut.expect(JSON_VALUE(l_n, '$.user.address.city')).to_equal('NYC');
    ut.expect(json_demo.extract_text(l_n, '$.user.name')).to_equal('Bob');
    ut.expect(json_demo.has_path(l_n, '$.meta.created')).to_be_true();
    ut.expect(json_demo.has_path(l_n, '$.meta.missing')).to_be_false();
  END t_json_roundtrip;

  PROCEDURE t_linked_list IS
    l_l t_intlist;
    l_s collections_linked_list.t_summary;
    l_r t_intlist;
    l_s2 collections_linked_list.t_summary;
  BEGIN
    l_l := collections_linked_list.cons(3, collections_linked_list.cons(1, collections_linked_list.cons(7, collections_linked_list.nil())));
    l_s := collections_linked_list.summarize(l_l);
    ut.expect(l_s.total).to_equal(11);
    ut.expect(l_s.count).to_equal(3);
    l_r := collections_linked_list.reversed(l_l);
    l_s2 := collections_linked_list.summarize(l_r);
    ut.expect(l_s2.total).to_equal(11);
    ut.expect(l_s2.count).to_equal(3);
  END t_linked_list;

  PROCEDURE t_staffing IS
    l_e hr.staffing.t_employee;
    l_e2 hr.staffing.t_employee;
  BEGIN
    delete from hr.employees where id = 9001;
    insert into hr.employees(id, name, email, grade)
               values (9001, 'Test Person', 't@example.com', 3);
    l_e := hr.staffing.find_employee(9001);
    ut.expect(l_e.name).to_equal('Test Person');
    hr.staffing.promote(9001);
    l_e2 := hr.staffing.find_employee(9001);
    ut.expect(l_e2.grade).to_equal(4);
    delete from hr.employees where id = 9001;
  END t_staffing;

  PROCEDURE t_stock IS
    l_id NUMBER;
    l_qty NUMBER;
  BEGIN
    l_id := inventory.stock.create_sku('UT-TEST-1', 5);
    ut.expect(l_id).to_be_not_null();
    BEGIN
      select qty
      INTO l_qty
      FROM inventory.skus where id = l_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    ut.expect(l_qty).to_equal(5);
    delete from inventory.skus where id = l_id;
  END t_stock;

  PROCEDURE t_mermaid IS
    l_d VARCHAR2(4000);
  BEGIN
    l_d := ((mermaid.flowchart('TD') || mermaid.node('a', 'Start')) || mermaid.link('a', 'a'));
    ut.expect(l_d).to_be_like('flowchart TD%a["Start"]%a --> a%');
    ut.expect(mermaid.esc('say "hi" [now]')).to_equal('say ''hi'' (now)');
    ut.expect(mermaid.fence('x')).to_be_like('```mermaid%x%```');
  END t_mermaid;

  PROCEDURE t_explain_op IS
  BEGIN
    ut.expect(explain_plan.explain_op('TABLE ACCESS', 'FULL')).to_be_like('%full scan%');
    ut.expect(explain_plan.explain_op('INDEX', 'UNIQUE SCAN')).to_be_like('%unique index%');
    ut.expect(explain_plan.explain_op('HASH JOIN', ' ')).to_be_like('%hash table%');
  END t_explain_op;

  PROCEDURE t_stat_diff IS
    l_before JSON;
    l_after JSON;
    l_r VARCHAR2(4000);
  BEGIN
    l_before := stat_diff.snapshot();
    ut.expect(JSON_VALUE(l_before, '$.logical_reads' RETURNING NUMBER)).to_be_not_null();
    ut.expect(JSON_VALUE(l_before, '$.consistent_gets' RETURNING NUMBER)).to_be_not_null();
    l_after := stat_diff.snapshot();
    l_r := stat_diff.report(l_before, l_after);
    ut.expect(l_r).to_be_like('%statistic%before%after%delta%');
  END t_stat_diff;
END ut_pell_examples;
/