-- ======================================================================
-- Generated by pell 0.0.1 from module scalar_test
--   Source:     compiler/examples/scalar_test.pell
--   SHA-256:    460965a183ed2a89b33a1a946c934869062cf9cd62bf1b61be295dc9e99b1179
--   pell git:   f840bce
--   Target:     Oracle 23
--   Schema:     (none — unqualified)
-- DO NOT EDIT — regenerate with `pell build`
--
-- Dependencies (extracted from pell source):
--   tables (incl. views/synonyms):
--     emp
--   packages:
--     dbms_output
-- ======================================================================

CREATE OR REPLACE PACKAGE scalar_test AS
  FUNCTION count_emp RETURN NUMBER;
  FUNCTION first_name RETURN VARCHAR2;
  PROCEDURE demo;
END scalar_test;
/

CREATE OR REPLACE PACKAGE BODY scalar_test AS

  FUNCTION count_emp RETURN NUMBER IS
    l_pell_ret_1 NUMBER;
  BEGIN
    BEGIN
      select count(*)
      INTO l_pell_ret_1
      FROM emp;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_pell_ret_1;
  END count_emp;

  FUNCTION first_name RETURN VARCHAR2 IS
    l_n VARCHAR2(4000);
  BEGIN
    BEGIN
      select ename
      INTO l_n
      FROM emp where rownum = 1;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    RETURN l_n;
  END first_name;

  PROCEDURE demo IS
    l_total NUMBER;
  BEGIN
    BEGIN
      select count(*)
      INTO l_total
      FROM emp;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN RAISE;
      WHEN TOO_MANY_ROWS THEN RAISE;
    END;
    dbms_output.put_line('count: ');
  END demo;
END scalar_test;
/